package msg

// Keys of operator-facing texts. Every key must have a text in every catalog;
// TestCatalogsComplete enforces this.
const (
	HelpIntro           Key = "help.intro"
	HelpUsage           Key = "help.usage"
	HelpCommands        Key = "help.commands"
	CmdHelpSummary      Key = "cmd.help.summary"
	CmdVersionSummary   Key = "cmd.version.summary"
	ErrUnknownCommand   Key = "err.unknown_command"
	HintUnknownCommand  Key = "hint.unknown_command"
	ErrInternal         Key = "err.internal"
	ErrUnexpectedArgs   Key = "err.unexpected_args"
	ErrExtraArgs        Key = "err.extra_args"
	ErrUnknownFlag      Key = "err.unknown_flag"
	ErrFlagValue        Key = "err.flag_value"
	ErrHookEventMissing Key = "err.hook_event_missing"
	ErrHookEventUnknown Key = "err.hook_event_unknown"
	HintHookEvents      Key = "hint.hook_events"
	CmdSetupSummary     Key = "cmd.setup.summary"
	ErrSetupToolMissing Key = "err.setup_tool_missing"
	ErrSetupToolUnknown Key = "err.setup_tool_unknown"
	HintSetupTools      Key = "hint.setup_tools"
	SetupInstalled      Key = "setup.installed"
	SetupUpdated        Key = "setup.updated"
	SetupUnchanged      Key = "setup.unchanged"
	SetupDisabled       Key = "setup.disabled"
	ErrToolNotFound     Key = "err.tool_not_found"
	HintToolNotFound    Key = "hint.tool_not_found"
	ErrToolFailed       Key = "err.tool_failed"
	ErrHomeUnknown      Key = "err.home_unknown"
	HintHomeUnknown     Key = "hint.home_unknown"
	ErrIO               Key = "err.io"
	VersionGentry       Key = "version.gentry"
	ErrFlagValueMissing Key = "err.flag_value_missing"
	EventsEmpty         Key = "events.empty"
	EventsNoneAfter     Key = "events.none_after"
	ErrEventsAfter      Key = "err.events_after"
	ErrStateNewer       Key = "err.state_newer"
	HintStateNewer      Key = "hint.state_newer"
	ErrStateUnavailable Key = "err.state_unavailable"
	HintStateUnavail    Key = "hint.state_unavailable"
)
