package msg

// ru is the Russian catalog. Every text is a complete sentence in a formal but
// readable style and starts with a capital letter; errors are printed as they
// are, without a program prefix.
var ru = catalog{
	form:  russianForm,
	forms: 3,
	texts: map[Key]string{
		HelpIntro:               "Gentry ведёт задачи агента по флоу проекта и хранит их состояние.",
		HelpUsage:               "Использование:\n  gentry <команда> [аргументы] [флаги]",
		HelpMore:                "Описание команды выводит gentry <команда> --help.",
		HelpUsageTitle:          "Использование:",
		HelpArgs:                "Аргументы:",
		HelpFlags:               "Флаги:",
		HelpSectionMaint:        "Установка и обслуживание:",
		FlagJSON:                "Вывести результат в формате JSON.",
		CmdVersionDesc:          "Показать версию Gentry.",
		FlagVersionJSON:         "Вывести в формате JSON также версии контракта, схемы хранилища состояния и формата знания.",
		CmdSetupDesc:            "Подключить Gentry к ИИ-инструменту: сформировать плагин и зарегистрировать его. После обновления Gentry команду нужно повторить.",
		ArgTool:                 "<ИИ-инструмент>",
		ArgToolDesc:             "ИИ-инструмент, к которому подключается Gentry. Допустимые значения: %s.",
		ArgNumber:               "<номер>",
		CmdVersionSummary:       "Показать версию Gentry",
		ErrUnknownCommand:       "Неизвестная команда «%s».",
		HintUnknownCommand:      "Перечень команд выводит gentry --help.",
		ErrInternal:             "Внутренняя ошибка Gentry: %v.",
		ErrUnexpectedArgs:       "Команда %s не принимает аргументов.",
		ErrExtraArgs:            "Команде %s переданы лишние аргументы: %s.",
		ErrUnknownFlag:          "Команда %s не поддерживает флаг %s.",
		ErrFlagValue:            "Флаг %s не принимает значения.",
		VersionGentry:           "Версия Gentry: %s",
		ErrHookEventMissing:     "Для команды hook требуется указать событие хука.",
		ErrHookEventUnknown:     "Неизвестное событие хука «%s».",
		HintHookEvents:          "Допустимые значения: %s.",
		CmdSetupSummary:         "Подключить Gentry к ИИ-инструменту",
		ErrSetupToolMissing:     "Для команды setup требуется указать ИИ-инструмент.",
		ErrSetupToolUnknown:     "Неизвестный ИИ-инструмент «%s».",
		HintSetupTools:          "Допустимые значения: %s.",
		SetupInstalled:          "Gentry подключён к Claude Code. Плагин начнёт работать со следующей сессии Claude Code.",
		SetupUpdated:            "Плагин Gentry в Claude Code обновлён. Изменения вступят в силу со следующей сессии Claude Code.",
		SetupUnchanged:          "Gentry уже подключён к Claude Code; изменения не требуются.",
		SetupDisabled:           "Плагин Gentry отключён в Claude Code. Включить его можно командой claude plugin enable gentry@gentry.",
		ErrToolNotFound:         "Программа %s не найдена.",
		HintToolNotFound:        "Установите %s и повторите gentry setup %s.",
		ErrToolFailed:           "Не удалось подключить плагин: команда «%s» завершилась ошибкой: %s.",
		ErrHomeUnknown:          "Не удалось определить папку данных Gentry: переменная GENTRY_HOME не задана, домашняя папка пользователя не найдена.",
		HintHomeUnknown:         "Задайте папку данных переменной окружения GENTRY_HOME.",
		ErrIO:                   "Не удалось записать файлы в %s: %v.",
		ErrFlagValueMissing:     "Для флага %s требуется значение.",
		EventsEmpty:             "Журнал событий пуст.",
		EventsNoneAfter:         "Событий с номером больше %d нет.",
		ErrEventsAfter:          "Значение флага --after должно быть номером события — целым числом не меньше 0. Получено: «%s».",
		ErrStateNewer:           "Хранилище состояния создано более новой версией Gentry: версия схемы %d, эта версия Gentry поддерживает схемы до %d.",
		HintStateNewer:          "Обновите Gentry.",
		ErrStateUnavailable:     "Хранилище состояния %s недоступно: %v.",
		HintStateUnavail:        "Повторите команду. Если ошибка повторяется, проверьте доступ к папке.",
		HelpSectionProjects:     "Проекты и рабочие копии:",
		HelpActions:             "Действия:",
		HelpGroupUsage:          "gentry %s <действие> [аргументы] [флаги]",
		HelpGroupMore:           "Описание действия с аргументами и флагами выводит gentry %s <действие> --help.",
		ErrActionMissing:        "Для команды %s требуется указать действие.",
		ErrActionUnknown:        "Неизвестное действие «%s» команды %s.",
		HintActions:             "Допустимые значения: %s.",
		CmdProjectDesc:          "Подключить проект к Gentry или показать подключённые проекты.",
		CmdProjectSummary:       "Подключить проект к Gentry или показать подключённые проекты",
		CmdProjectAddSummary:    "Подключить проект к Gentry",
		CmdProjectAddDesc:       "Подключить проект к Gentry: связать рабочую копию кода с репозиторием знания и внести в пул основную рабочую копию и ту, в которой выполнена команда. Команда выполняется в рабочей копии кода проекта.",
		ArgProjectID:            "<идентификатор>",
		ArgProjectIDDesc:        "Идентификатор проекта: 2–32 строчные латинские буквы, цифры и дефисы, первая — буква.\nОбязателен, если знание создаётся заново; иначе берётся из знания.",
		ArgPath:                 "<путь>",
		FlagKnowledgeDesc:       "Папка репозитория знания. Если её нет или она пуста, репозиторий создаётся.",
		ArgPrefix:               "<префикс>",
		FlagPrefixDesc:          "Префикс номеров задач: 2–10 заглавных латинских букв.\nПо умолчанию — буквы идентификатора.",
		CmdProjectListSummary:   "Показать подключённые проекты",
		CmdProjectListDesc:      "Показать проекты, подключённые к Gentry на этой машине.",
		ProjectAdded:            "Проект %s подключён к Gentry.",
		ProjectKnowledge:        "Знание проекта: %s.",
		ProjectKnowledgeNew:     "Знание проекта: %s; репозиторий создан.",
		ProjectPrefix:           "Префикс номеров задач: %s.",
		ProjectMainWorktree:     "Основная рабочая копия: %s.",
		ProjectWorktreeAdded:    "Рабочая копия %s также внесена в пул.",
		ProjectUnchanged:        "Проект %s уже подключён; изменения не требуются.",
		ProjectsNone:            "Подключённых проектов нет. Подключить проект можно командой gentry project add.",
		ProjectLine:             "%s — префикс %s, знание %s, основная копия %s",
		ErrKnowledgeFlagMissing: "Для команды project add требуется указать репозиторий знания флагом --knowledge.",
		ErrProjectIDMissing:     "Для нового знания проекта требуется указать идентификатор проекта: gentry project add <идентификатор> --knowledge <путь>.",
		ErrProjectIDInvalid:     "Идентификатор проекта должен состоять из 2–32 строчных латинских букв, цифр и дефисов и начинаться с буквы. Получено: «%s».",
		ErrPrefixUnderivable:    "Префикс номеров задач не удалось получить из идентификатора проекта «%s».",
		HintPrefixUnderivable:   "Укажите префикс флагом --prefix: от 2 до 10 заглавных латинских букв.",
		ErrPrefixInvalid:        "Значение флага --prefix должно состоять из 2–10 заглавных латинских букв. Получено: «%s».",
		ErrNotGitRepo:           "Папка %s не является рабочей копией git.",
		HintNotGitRepo:          "Команда gentry project add выполняется в рабочей копии кода проекта.",
		ErrKnowledgeNotEmpty:    "Папка %s не подходит для знания проекта: она не пуста и не является репозиторием git.",
		ErrKnowledgeForeign:     "Репозиторий %s не подходит для знания проекта: в нём уже есть файлы, но к Gentry он не подключался.",
		HintKnowledgeDir:        "Укажите пустую папку, новый путь или репозиторий знания проекта.",
		ErrKnowledgeNested:      "Знание проекта %s и рабочая копия %s вложены одна в другую.",
		HintKnowledgeNested:     "Знание проекта должно быть отдельным репозиторием вне рабочей копии.",
		ErrKnowledgeBadFile:     "Сведения о проекте в знании %s повреждены: %s.",
		HintKnowledgeBadFile:    "Восстановите их из истории git репозитория знания.",
		ErrKnowledgeNewer:       "Знание проекта %s записано в формате версии %d, эта версия Gentry поддерживает форматы до %d.",
		HintKnowledgeNewer:      "Обновите Gentry.",
		ErrKnowledgeMismatch:    "Указан идентификатор проекта «%s», а в знании записан «%s».",
		HintKnowledgeMismatch:   "Не указывайте идентификатор в команде или укажите идентификатор, записанный в знании.",
		ErrProjectExists:        "Проект %s уже подключён со знанием %s.",
		ErrProjectClone:         "Проект %s уже подключён; его основная рабочая копия — %s.",
		ErrPrefixTaken:          "Префикс %s уже используется проектом %s.",
		HintPrefixTaken:         "Укажите другой префикс флагом --prefix.",
		ErrWorktreeTaken:        "Рабочая копия %s уже внесена в пул проекта %s.",
		HintGitNotFound:         "Установите git и повторите команду.",
		ErrGitFailed:            "Команда «%s» завершилась ошибкой: %s.",
		CauseInfoSyntax:         "их не удаётся прочитать",
		CauseInfoMissing:        "нет поля %s",
		CauseInfoUnknown:        "неизвестное поле «%s»",
		CauseInfoValue:          "недопустимое значение поля %s: «%v»",
	},
	plurals: map[Key][]string{},
}
