package msg

// ru is the Russian catalog. Every text is a complete sentence in a formal but
// readable style and starts with a capital letter; errors are printed as they
// are, without a program prefix.
var ru = catalog{
	form:  russianForm,
	forms: 3,
	texts: map[Key]string{
		HelpIntro:                "Gentry ведёт задачи агента по флоу проекта и хранит их состояние.",
		HelpUsage:                "Использование:\n  gentry <команда> [аргументы] [флаги]",
		HelpMore:                 "Посмотреть описание команды: gentry <команда> --help",
		HelpUsageTitle:           "Использование:",
		HelpArgs:                 "Аргументы:",
		HelpFlags:                "Флаги:",
		HelpSectionMaint:         "Установка и обслуживание:",
		FlagJSON:                 "Вывести результат в формате JSON.",
		CmdVersionDesc:           "Показать версию Gentry.",
		FlagVersionJSON:          "Вывести в формате JSON с версиями контракта, хранилища состояния и формата знания.",
		CmdSetupDesc:             "Подключить Gentry к ИИ-инструменту: сформировать и зарегистрировать плагин.\nПосле обновления Gentry команду нужно повторить.",
		ArgTool:                  "<ИИ-инструмент>",
		ArgToolDesc:              "ИИ-инструмент для подключения.\nДопустимые значения: %s",
		ArgNumber:                "<номер>",
		CmdVersionSummary:        "Показать версию Gentry",
		ErrUnknownCommand:        "Неизвестная команда «%s».",
		HintLine:                 "%s: %s",
		HintUnknownCommand:       "Посмотреть перечень команд",
		ErrInternal:              "Внутренняя ошибка Gentry: %v",
		ErrUnexpectedArgs:        "Команда %s не принимает аргументов.",
		ErrExtraArgs:             "Лишние аргументы команды %s: %s",
		ErrUnknownFlag:           "Команда %s не поддерживает флаг %s.",
		ErrFlagValue:             "Флаг %s не принимает значения.",
		VersionGentry:            "Версия Gentry: %s",
		ErrHookEventMissing:      "Не указано событие хука.",
		ErrHookEventUnknown:      "Неизвестное событие хука «%s».",
		HintHookEvents:           "Допустимые значения: %s",
		CmdSetupSummary:          "Подключить Gentry к ИИ-инструменту",
		ErrSetupToolMissing:      "Не указан ИИ-инструмент.",
		ErrSetupToolUnknown:      "Неизвестный ИИ-инструмент «%s».",
		SetupInstalled:           "Gentry подключён к Claude Code.\nПлагин начнёт работать со следующей сессии.",
		SetupUpdated:             "Плагин Gentry в Claude Code обновлён.\nИзменения вступят в силу со следующей сессии.",
		SetupUnchanged:           "Gentry уже подключён к Claude Code.",
		SetupDisabled:            "Плагин Gentry отключён в Claude Code.",
		HintPluginEnable:         "Включить плагин: claude plugin enable gentry@gentry",
		SetupPermissionAdded:     "Инструменты Gentry разрешены в настройках Claude Code.",
		SetupPermissionFailed:    "Разрешить инструменты Gentry не удалось: настройки Claude Code не прочитаны.",
		SetupPermissionUnwritten: "Разрешить инструменты Gentry не удалось: настройки Claude Code не записаны.",
		SetupSettings:            "Настройки: %s",
		HintSetupPermission:      "Разрешить инструменты вручную: правило %s в permissions.allow",
		SetupSwitched:            "Плагин Gentry в Claude Code переключён на папку данных этой команды.\nИзменения вступят в силу со следующей сессии.\nПрежняя папка плагина: %s",
		FlagSetupSwitch:          "Переключить на папку данных этой команды плагин Gentry в Claude Code,\nподключённый из другой папки данных.",
		ErrPluginElsewhere:       "Плагин Gentry в Claude Code подключён из другой папки данных.\nПапка плагина: %s\nПапка плагина этой команды: %s",
		HintPluginElsewhere:      "Переключить плагин всех сессий Claude Code на папку данных этой команды",
		ErrToolNotFound:          "Программа %s не найдена.",
		HintToolNotFound:         "Установите %s и повторите",
		ErrToolFailed:            "Не удалось подключить плагин, команда «%s» завершилась ошибкой: %s",
		ErrHomeUnknown:           "Не удалось определить папку данных Gentry: нет ни GENTRY_HOME, ни домашней папки пользователя.",
		HintHomeUnknown:          "Задайте папку данных переменной окружения GENTRY_HOME.",
		ErrIO:                    "Не удалось записать файлы в %s: %v",
		ErrFlagValueMissing:      "Не указано значение флага %s.",
		ErrEventsAfter:           "Недопустимое значение флага --after: «%s».",
		ErrStateNewer:            "Хранилище состояния создано более новой версией Gentry: схема %d, поддерживается до %d.",
		HintStateNewer:           "Обновите Gentry.",
		HintStateNewerAgent:      "Сообщить оператору и попросить перезапустить сессию.",
		ErrStateUnavailable:      "Хранилище состояния недоступно: %v",
		HintStateUnavail:         "Повторите команду; если ошибка повторится, проверьте доступ к файлу: %s",
		HelpSectionProjects:      "Проекты и рабочие копии:",
		HelpActions:              "Действия:",
		HelpGroupUsage:           "gentry %s <действие> [аргументы] [флаги]",
		HelpGroupMore:            "Посмотреть описание действия: gentry %s <действие> --help",
		ErrActionMissing:         "Не указано действие команды %s.",
		ErrActionUnknown:         "Неизвестное действие «%s» команды %s.",
		HintActions:              "Посмотреть перечень действий",
		CmdProjectDesc:           "Подключить проект или показать подключённые проекты.",
		CmdProjectSummary:        "Подключить проект или показать подключённые проекты",
		CmdProjectAddSummary:     "Подключить проект",
		CmdProjectAddDesc:        "Подключить проект: связать рабочую копию кода с репозиторием знания.\nВ пул вносятся основная рабочая копия и та, в которой выполнена команда.\nКоманда выполняется в рабочей копии кода проекта.",
		ArgProjectID:             "<идентификатор>",
		ArgProjectIDDesc:         "Идентификатор проекта: 2–32 строчные латинские буквы, цифры и дефисы, первая — буква.\nОбязателен, если знание создаётся заново; иначе берётся из знания.",
		ArgPath:                  "<путь>",
		FlagKnowledgeDesc:        "Папка репозитория знания.\nЕсли её нет или она пуста, репозиторий создаётся.",
		ArgPrefix:                "<префикс>",
		FlagPrefixDesc:           "Префикс номеров задач: 2–10 заглавных латинских букв.\nПо умолчанию — буквы идентификатора.",
		CmdProjectListSummary:    "Показать подключённые проекты",
		CmdProjectListDesc:       "Показать проекты, подключённые на этой машине.",
		ProjectAdded:             "Проект %s подключён.",
		ProjectKnowledge:         "Знание проекта: %s",
		ProjectKnowledgeNew:      "Знание проекта (репозиторий создан): %s",
		ProjectPrefix:            "Префикс номеров задач: %s",
		ProjectMainWorktree:      "Основная рабочая копия: %s",
		ProjectWorktreeAdded:     "Также внесена в пул: %s",
		ProjectUnchanged:         "Проект %s уже подключён.",
		ProjectsNone:             "Подключённых проектов нет.",
		HintProjectAdd:           "Подключить проект",
		ErrKnowledgeFlagMissing:  "Не указан репозиторий знания.",
		ErrProjectIDMissing:      "Для нового знания нужен идентификатор проекта.",
		ErrProjectIDInvalid:      "Недопустимый идентификатор проекта: «%s».",
		ErrPrefixUnderivable:     "Не удалось получить префикс номеров задач из идентификатора «%s».",
		HintPrefixUnderivable:    "Укажите префикс из 2–10 заглавных латинских букв: --prefix <префикс>",
		ErrPrefixInvalid:         "Недопустимое значение флага --prefix: «%s».",
		ErrNotGitRepo:            "Папка не является рабочей копией git: %s",
		HintNotGitRepo:           "Выполните команду в рабочей копии кода проекта.",
		ErrKnowledgeNotEmpty:     "Папка не пуста и не является репозиторием git: %s",
		ErrKnowledgeForeign:      "В репозитории уже есть файлы, но он не является знанием проекта: %s",
		HintKnowledgeDir:         "Укажите пустую папку, новый путь или репозиторий знания проекта.",
		ErrKnowledgeNested:       "Знание проекта и рабочая копия вложены одна в другую:\n  %s\n  %s",
		HintKnowledgeNested:      "Знание проекта должно быть отдельным репозиторием вне рабочей копии.",
		ErrKnowledgeBadFile:      "Сведения о проекте в знании повреждены: %s",
		HintKnowledgeBadFile:     "Восстановите их из истории git репозитория знания: %s",
		ErrKnowledgeNewer:        "Знание проекта записано в более новом формате: версия %d, поддерживается до %d.",
		HintKnowledgeNewer:       "Обновите Gentry.",
		ErrKnowledgeMismatch:     "Указан идентификатор проекта «%s», а в знании записан «%s».",
		HintKnowledgeMismatch:    "Не указывайте идентификатор или укажите «%s».",
		ErrProjectExists:         "Проект %s уже подключён с другим знанием: %s",
		ErrProjectClone:          "Проект %s уже подключён, основная рабочая копия: %s",
		ErrPrefixTaken:           "Префикс %s уже используется проектом %s.",
		HintPrefixTaken:          "Укажите другой префикс: --prefix <префикс>",
		ErrWorktreeTaken:         "Рабочая копия уже в пуле проекта %s: %s",
		HintGitNotFound:          "Установите git и повторите команду.",
		ErrGitFailed:             "Команда «%s» завершилась ошибкой: %s",
		CauseInfoSyntax:          "их не удаётся прочитать",
		CauseInfoMissing:         "нет поля %s",
		CauseInfoUnknown:         "неизвестное поле «%s»",
		CauseInfoValue:           "недопустимое значение поля %s: «%v»",
		ProjectUnpooled:          "Рабочие копии репозитория, не внесённые в пул:",
		HintProjectUnpooled:      "Внести копию в пул",
		HintProjectClone:         "Внести эту копию в пул",
		CmdWorktreeSummary:       "Внести рабочую копию в пул проекта или показать рабочие копии",
		CmdWorktreeDesc:          "Внести рабочую копию в пул проекта или показать рабочие копии.",
		CmdWorktreeAddSummary:    "Внести рабочую копию в пул проекта",
		CmdWorktreeAddDesc:       "Внести рабочую копию в пул проекта.\nКоманда нужна для копий, сделанных после подключения проекта, и для отдельных клонов.",
		ArgWorktreePathDesc:      "Папка рабочей копии; по умолчанию — текущая.",
		FlagWorktreeAddProject:   "Проект, в пул которого вносится копия.\nПо умолчанию определяется по копии или текущей папке.",
		CmdWorktreeListSummary:   "Показать рабочие копии",
		CmdWorktreeListDesc:      "Показать рабочие копии: ветку, занятость и признак основной копии.",
		FlagWorktreeListProject:  "Проект, копии которого нужно показать.\nПо умолчанию — проект текущей папки, вне проекта — все проекты.",
		WorktreeAdded:            "Рабочая копия внесена в пул проекта %s: %s",
		WorktreeUnchanged:        "Рабочая копия уже в пуле проекта %s: %s",
		WorktreesNone:            "Рабочих копий нет.",
		WorktreeMain:             "основная",
		WorktreeFree:             "свободна",
		WorktreeMissing:          "папка не найдена",
		ErrWorktreeKnowledge:     "Папка знания проекта %s не может быть рабочей копией: %s",
		ErrProjectUndetermined:   "Не удалось определить проект для папки %s",
		HintProjectUndetermined:  "Укажите --project или выполните команду в рабочей копии проекта.",
		ErrProjectNotFound:       "Проект «%s» не подключён.",
		HintProjectNotFound:      "Посмотреть перечень проектов",
		ValueNone:                "—",
		ColProject:               "ПРОЕКТ",
		ColPrefix:                "ПРЕФИКС",
		ColKnowledge:             "ЗНАНИЕ",
		ColMainWorktree:          "ОСНОВНАЯ КОПИЯ",
		ColWorktree:              "РАБОЧАЯ КОПИЯ",
		ColBranch:                "ВЕТКА",
		ColState:                 "СОСТОЯНИЕ",
		HintEventsAfter:          "Укажите номер события — целое число не меньше 0.",
		HintKnowledgeFlag:        "Укажите папку знания: --knowledge <путь>",
		HintProjectIDMissing:     "Укажите идентификатор",
		HintProjectIDInvalid:     "Укажите 2–32 строчные латинские буквы, цифры и дефисы, первая — буква.",
		HintPrefixInvalid:        "Укажите от 2 до 10 заглавных латинских букв.",

		// The flow: gentry flow and the problems of a flow.
		HelpSectionProcess:            "Процесс оператора:",
		CmdFlowSummary:                "Показать или изменить флоу проекта",
		CmdFlowDesc:                   "Показать или изменить флоу проекта.\nИзменения в папке флоу — черновик; действующим он становится после применения.",
		CmdFlowShowSummary:            "Показать флоу проекта",
		CmdFlowShowDesc:               "Показать сценарии, этапы и субагентов флоу проекта.\nС флагом объекта выводится этот объект подробно.\nЕсли во флоу есть ошибки, выводится их перечень.",
		ArgScenario:                   "<сценарий>",
		FlagFlowShowProject:           "Проект, флоу которого нужно показать.\nПо умолчанию — проект текущей папки.",
		FlowProject:                   "Проект: %s",
		FlowScenario:                  "Сценарий: %s",
		FlowTitle:                     "Название: %s",
		FlowDefaultPath:               "Путь по умолчанию:",
		FlowConditional:               "Условные переходы:",
		FlowTransition:                "%s → %s: %s",
		FlowTransitionLimit:           "%s → %s, %s: %s",
		FlowEnd:                       "конец",
		FlowProblems:                  "Ошибки:",
		ColScenario:                   "СЦЕНАРИЙ",
		ColTitle:                      "НАЗВАНИЕ",
		ColStage:                      "ЭТАП",
		ColExecutor:                   "ИСПОЛНИТЕЛЬ",
		ColExit:                       "ВЫХОД",
		ColNode:                       "УЗЕЛ",
		ErrFlowNotFound:               "У проекта %s нет флоу.",
		ErrFlowInvalid:                "Во флоу проекта %s есть ошибки.",
		FlowObjCommon:                 "Общие правила флоу",
		FlowObjScenario:               "Сценарий %s",
		FlowObjNode:                   "Сценарий %s, узел %s",
		FlowObjStage:                  "Этап %s",
		FlowObjPart:                   "Фрагмент %s",
		ProblemSyntax:                 "%s: ошибка синтаксиса YAML.",
		ProblemEncoding:               "%s: текст не в кодировке UTF-8.",
		ProblemNotMapping:             "%s: описание должно состоять из полей.",
		ProblemUnknownField:           "%s: неизвестное поле «%s».",
		ProblemUnsupportedField:       "%s: поле «%s» не поддерживается этой версией Gentry.",
		ProblemMissingField:           "%s: не заполнено поле «%s».",
		ProblemNotString:              "%s: значение поля «%s» должно быть строкой.",
		ProblemMaxRounds:              "%s: значение поля «max_rounds» должно быть целым числом больше 0.",
		ProblemInclude:                "%s: значение поля «include» должно быть списком идентификаторов.",
		ProblemNext:                   "%s: значение поля «next» должно быть идентификатором узла или списком переходов.",
		ProblemNodes:                  "%s: значение поля «nodes» должно быть набором узлов.",
		ProblemInvalidID:              "%s: недопустимый идентификатор; допустимы до 64 строчных латинских букв, цифр и дефисов, первая — буква.",
		ProblemExtraFile:              "Файл не относится к флоу: %s",
		ProblemExtraDir:               "Папка не относится к флоу: %s",
		ProblemMissingInstruction:     "%s: нет инструкции.",
		ProblemOrphanInstruction:      "%s: есть инструкция, но нет полей этапа.",
		ProblemNoScenarios:            "Во флоу нет ни одного сценария.",
		ProblemUnknownStage:           "%s: этап %s не найден.",
		ProblemUnknownPart:            "%s: фрагмент %s не найден.",
		ProblemUnknownExecutor:        "%s: субагент %s не найден.",
		ProblemUnknownStart:           "%s: начальный узел %s не найден.",
		ProblemUnknownTarget:          "%s: узел перехода %s не найден.",
		ProblemReservedNode:           "%s: finish обозначает конец сценария и не может быть узлом.",
		ProblemUnreachable:            "%s: узел %s недостижим из начального узла.",
		ProblemDeadEnd:                "%s: из узла %s нельзя дойти до конца сценария.",
		ProblemUnlimitedLoop:          "%s: у цикла %s нет предела возвратов.",
		ProblemLimitOutsideLoop:       "%s: у перехода %s → %s указан предел возвратов, но переход не замыкает цикл.",
		ProblemLimitWithoutCondition:  "%s: у перехода %s → %s с пределом возвратов нет условия.",
		ProblemSeveralDefaults:        "%s: переход без условия может быть только один.",
		ProblemDuplicateTransition:    "%s: два перехода к узлу %s.",
		ArgStage:                      "<этап>",
		ArgAgent:                      "<субагент>",
		ArgPart:                       "<фрагмент>",
		FlagShowScenario:              "Показать сценарий: путь, переходы и узлы.",
		FlagShowStage:                 "Показать этап: поля, фрагменты и инструкцию.",
		FlagShowAgent:                 "Показать субагента: поля и инструкцию.",
		FlagShowPart:                  "Показать фрагмент и его текст.",
		FlagShowDraft:                 "Показать черновик вместо действующего флоу.",
		CmdFlowDiffSummary:            "Показать изменения черновика",
		CmdFlowDiffDesc:               "Показать, чем черновики флоу проекта и библиотеки субагентов отличаются от действующих.\nПодробности со схемами сценариев записываются в файл изменений.",
		FlagFlowDiffProject:           "Проект, черновик которого нужно сравнить.\nПо умолчанию — проект текущей папки.",
		CmdFlowApplySummary:           "Применить черновик флоу",
		CmdFlowApplyDesc:              "Проверить черновик и сделать его действующим флоу на всех машинах.\nЧерновик с ошибками не применяется.",
		FlagFlowApplyProject:          "Проект, черновик которого нужно применить.\nПо умолчанию — проект текущей папки.",
		CmdFlowDiscardSummary:         "Отменить изменения флоу",
		CmdFlowDiscardDesc:            "Вернуть папку флоу к действующему флоу.\nИзменения черновика теряются.",
		FlagFlowDiscardProject:        "Проект, изменения флоу которого нужно отменить.\nПо умолчанию — проект текущей папки.",
		FlowDraftOpened:               "Черновик существует.",
		FlowStage:                     "Этап: %s",
		FlowExecutor:                  "Исполнитель: %s",
		FlowExit:                      "Выход: %s",
		FlowParts:                     "Фрагменты: %s",
		FlowScenarios:                 "Сценарии: %s",
		FlowInstruction:               "Инструкция:",
		FlowAgent:                     "Субагент: %s",
		FlowSource:                    "Источник: %s",
		FlowPurpose:                   "Назначение: %s",
		FlowCapabilities:              "Возможности: %s",
		FlowStages:                    "Этапы: %s",
		FlowPart:                      "Фрагмент: %s",
		FlowText:                      "Текст:",
		FlowSourceProject:             "проект",
		FlowSourceLibrary:             "библиотека",
		ColAgent:                      "СУБАГЕНТ",
		ColSource:                     "ИСТОЧНИК",
		ColStages:                     "ЭТАПЫ",
		FlowChanges:                   "Изменения:",
		FlowChange:                    "%s: %s",
		FlowChangeAdded:               "добавлен",
		FlowChangeModified:            "изменён",
		FlowChangeRemoved:             "удалён",
		FlowCommonAdded:               "добавлены",
		FlowCommonModified:            "изменены",
		FlowCommonRemoved:             "удалены",
		FlowApplied:                   "Изменения флоу применены.",
		FlowDiscarded:                 "Изменения флоу отменены.",
		HintFlowShowDraft:             "Посмотреть черновик",
		HintFlowStage:                 "Посмотреть этап подробно",
		HintFlowApply:                 "Применить черновик",
		ErrFlowObjectNotFound:         "Во флоу проекта %s нет %s «%s».",
		ErrDraftObjectNotFound:        "В черновике флоу проекта %s нет %s «%s».",
		FlowKindScenario:              "сценария",
		FlowKindStage:                 "этапа",
		FlowKindAgent:                 "субагента",
		FlowKindPart:                  "фрагмента",
		HintFlowObjects:               "Посмотреть перечень объектов",
		HintDraftObjects:              "Посмотреть перечень объектов",
		ErrDraftNotFound:              "У проекта %s нет черновика флоу.",
		ErrDraftInvalid:               "В черновике флоу проекта %s есть ошибки.",
		ErrConflictingFlags:           "Флаги %s и %s нельзя указывать вместе.",
		HintCommandHelp:               "Посмотреть описание команды",
		ErrDraftRead:                  "Не удалось прочитать черновик: %s",
		ErrDraftWrite:                 "Не удалось записать черновик: %s",
		ErrLibraryRead:                "Не удалось прочитать библиотеку субагентов: %s",
		FlowObjAgent:                  "Субагент %s",
		FlowObjLibraryAgent:           "Субагент %s из библиотеки",
		ProblemCapabilities:           "%s: значение поля «capabilities» должно быть списком из %s.",
		ProblemOrphanAgentInstruction: "%s: есть инструкция, но нет полей субагента.",
		FlowAppliedAt:                 "Флоу применён: %s",
		FlowDir:                       "Папка флоу: %s",
		ProblemExecutorInDraftLibrary: "%s: субагент %s есть только в черновике библиотеки.",
		ProblemLibraryExtraFile:       "Файл не относится к библиотеке субагентов: %s",
		ProblemLibraryExtraDir:        "Папка не относится к библиотеке субагентов: %s",
		CmdLibrarySummary:             "Применить или отменить изменения библиотеки субагентов",
		CmdLibraryDesc:                "Применить или отменить изменения библиотеки субагентов.\nИзменения в папке библиотеки — черновик; действующей она становится после применения.",
		CmdLibraryDiffSummary:         "Показать изменения библиотеки",
		CmdLibraryDiffDesc:            "Показать, какие субагенты библиотеки изменены после применения.",
		CmdLibraryApplySummary:        "Применить изменения библиотеки",
		CmdLibraryApplyDesc:           "Проверить изменения библиотеки и сделать их действующими на всех машинах.\nИзменения с ошибками не применяются.",
		CmdLibraryDiscardSummary:      "Отменить изменения библиотеки",
		CmdLibraryDiscardDesc:         "Вернуть папку библиотеки к действующей библиотеке.\nИзменения теряются.",
		LibraryAppliedAt:              "Библиотека применена: %s",
		LibraryApplied:                "Изменения библиотеки применены.",
		LibraryDiscarded:              "Изменения библиотеки отменены.",
		LibraryDir:                    "Папка библиотеки: %s",
		HintLibraryApply:              "Применить изменения",
		ErrLibraryDraftNotFound:       "У библиотеки субагентов нет черновика.",
		ErrLibraryDraftInvalid:        "В изменениях библиотеки есть ошибки.",
		ErrLibraryBreaksFlows:         "Изменения библиотеки вносят ошибки во флоу проектов.",
		LibraryFlowProblems:           "Ошибки флоу проекта %s:",
		CmdProcessSummary:             "Синхронизировать процесс оператора между машинами",
		CmdProcessDesc:                "Синхронизировать процесс оператора между машинами.\nПроцесс — флоу проектов и библиотека субагентов; он хранится в git и передаётся через удалённый репозиторий.",
		CmdProcessRemoteSummary:       "Подключить удалённый репозиторий процесса",
		CmdProcessRemoteDesc:          "Подключить удалённый репозиторий процесса или заменить его адрес.\nРепозиторий нужно создать заранее и сделать закрытым.\nЕсли процесс есть и на машине, и в репозитории, они сводятся, а отличия этой машины сохраняются как черновики.",
		ArgRemote:                     "<адрес>",
		ArgRemoteDesc:                 "Адрес git-репозитория.",
		CmdProcessSyncSummary:         "Синхронизировать процесс",
		CmdProcessSyncDesc:            "Получить изменения процесса с других машин и отправить изменения этой машины.",
		CmdProcessStatusSummary:       "Показать состояние процесса",
		CmdProcessStatusDesc:          "Показать удалённый репозиторий, время синхронизации, черновики, неотправленные изменения и конфликты.",
		ProcessRemoteSet:              "Удалённый репозиторий подключён: %s",
		ProcessResultSent:             "Процесс: отправлен в удалённый репозиторий",
		ProcessResultReceived:         "Процесс: получен из удалённого репозитория",
		ProcessResultMerged:           "Процесс: сведён с удалённым репозиторием, отличия этой машины сохранены как черновики",
		ProcessResultUnchanged:        "Процесс: совпадает с удалённым репозиторием",
		ProcessDrafts:                 "Черновики:",
		HintProcessStatus:             "Посмотреть черновики",
		ProcessSynced:                 "Процесс синхронизирован.",
		ProcessReceived:               "Получено:",
		ProcessSent:                   "Отправлено:",
		ProcessRemote:                 "Удалённый репозиторий: %s",
		ProcessNoRemote:               "Удалённый репозиторий не подключён.",
		ProcessSyncedAt:               "Синхронизирован: %s",
		ProcessUnsent:                 "Не отправлено:",
		ProcessConflicts:              "Конфликты:",
		HintProcessRemote:             "Подключить удалённый репозиторий",
		HintProcessSync:               "Синхронизировать",
		KindFlow:                      "флоу %s",
		KindLibrary:                   "библиотека субагентов",
		ErrRemoteMissing:              "Не указан адрес удалённого репозитория.",
		ErrProcessRemoteNotSet:        "Удалённый репозиторий не подключён.",
		ErrRemoteUnavailable:          "Удалённый репозиторий недоступен: %s",
		HintRemoteAccess:              "Проверить доступ: git ls-remote %s",
		ErrRemoteNotProcess:           "Репозиторий не является репозиторием процесса: %s",
		ErrRemoteNewer:                "Процесс в репозитории записан более новой версией Gentry: %s",
		ErrProcessNotProcess:          "Папка процесса содержит другой git-репозиторий: %s",
		ErrProcessNewer:               "Процесс на машине записан более новой версией Gentry: %s",
		ErrProcessBusy:                "Репозиторий процесса используется другой командой Gentry.",
		SyncReceived:                  "Получены изменения с другой машины:",
		SyncSkipped:                   "Синхронизация пропущена: удалённый репозиторий недоступен.",
		SyncDeferred:                  "Отправка отложена: удалённый репозиторий недоступен.",
		SyncFlowConflict:              "Флоу проекта %s изменён на другой машине; изменения этой машины сохранены как черновик.",
		SyncLibraryConflict:           "Библиотека субагентов изменена на другой машине; изменения этой машины сохранены как черновик.",
		SyncConflictDir:               "Версии файлов другой машины: %s",
		SyncBothChanged:               "Изменены на обеих машинах:",
		HintFlowDiffProject:           "Посмотреть отличия",
		HintLibraryDiff:               "Посмотреть отличия",
		SyncFlowRestored:              "Изменение флоу проекта %s, внесённое без Gentry, содержит ошибки и сохранено как черновик.",
		SyncLibraryRestored:           "Изменение библиотеки субагентов, внесённое без Gentry, содержит ошибки и сохранено как черновик.",

		// Tasks: gentry task.
		HelpSectionTasks:     "Задачи:",
		CmdTaskSummary:       "Взять, показать или отменить задачу",
		CmdTaskDesc:          "Взять задачу в работу или отменить её, показать задачу или перечень задач.",
		CmdTaskTakeSummary:   "Взять задачу в работу",
		CmdTaskTakeDesc:      "Взять задачу в работу: зарезервировать рабочую копию, сохранить название, постановку и флоу задачи.\nКопия должна быть в пуле, без задачи и без незакоммиченных изменений.\nОтменённую задачу можно взять заново: укажите её номер в --task.",
		FlagTaskScenario:     "Сценарий задачи.",
		ArgTitle:             "<название>",
		FlagTaskTitle:        "Название задачи — одна строка до 80 знаков.",
		ArgText:              "<текст>",
		FlagTaskStatement:    "Постановка задачи.",
		FlagTaskStatementCLI: "Длинную постановку передайте через --input.",
		FlagTaskWorktree:     "Рабочая копия задачи; по умолчанию — текущая папка.",
		ArgFile:              "<файл>",
		FlagTaskInput:        "Поля задачи одним объектом JSON: task, scenario, title, statement, worktree.\nВместо файла можно указать «-» — стандартный ввод. Вместе с флагами полей не указывается.",
		CmdTaskShowSummary:   "Показать задачу",
		CmdTaskShowDesc:      "Показать задачу: состояние, этап, прогресс, пройденный путь, шаги и артефакты.",
		ArgTask:              "<задача>",
		ArgTaskDesc:          "Номер задачи с префиксом проекта; по умолчанию — задача текущей рабочей копии.",
		CmdTaskListSummary:   "Показать задачи",
		CmdTaskListDesc:      "Показать незавершённые задачи: в работе и ожидающие оператора.",
		FlagTaskListAll:      "Показать все задачи, включая закрытые и отменённые.",
		ArgState:             "<состояние>",
		FlagTaskListState:    "Показать задачи одного состояния.\nДопустимые значения: active — в работе, waiting — ожидает оператора, closed — закрыта, cancelled — отменена",
		FlagTaskListProject:  "Проект, задачи которого нужно показать.\nПо умолчанию — проект текущей папки, вне проекта — все проекты.",
		TaskTaken:            "Задача %s взята.",
		TaskHeading:          "Задача %s: %s",
		TaskTitle:            "Название: %s",
		TaskProject:          "Проект: %s",
		TaskState:            "Состояние: %s",
		TaskScenario:         "Сценарий: %s",
		TaskStage:            "Этап: %s",
		TaskNamed:            "%s (%s)",
		TaskTakenAt:          "Взята: %s",
		TaskFlowApplied:      "Флоу задачи применён: %s",
		TaskSource:           "Постановка записана: %s",
		TaskSourceOperator:   "оператором",
		TaskSourceAgent:      "агентом со слов оператора",
		TaskWorktree:         "Рабочая копия: %s",
		TaskStateActive:      "в работе",
		TaskStateWaiting:     "ожидает оператора",
		TaskStateClosed:      "закрыта",
		TaskStateCancelled:   "отменена",
		HintTaskShow:         "Посмотреть задачу",
		ColNumber:            "НОМЕР",
		TasksNoneOpen:        "Незавершённых задач нет.",
		TasksNone:            "Задач нет.",
		WorktreeTask:         "задача %s",
		ErrWorktreeBusy:      "В рабочей копии уже идёт задача %s: %s",
		ErrWorktreeNotPooled: "Папка не внесена в пул рабочих копий: %s",
		HintWorktreeAdd:      "Внести копию в пул",
		ErrWorktreeDirty:     "В рабочей копии есть незакоммиченные изменения: %s",
		WorktreeChangedFiles: "Изменённые файлы:",
		HintWorktreeDirty:    "Закоммитьте или отмените изменения и повторите команду.",
		ErrScenarioMissing:   "Не указан сценарий задачи.",
		HintFlowScenarios:    "Посмотреть сценарии",
		ErrTitleMissing:      "Не указано название задачи.",
		ErrStatementMissing:  "Не указана постановка задачи.",
		ErrTitleTooLong:      "Название задачи длиннее 80 знаков.",
		ErrTitleMultiline:    "Название задачи состоит из нескольких строк.",
		HintTitle:            "Укажите название одной строкой не длиннее 80 знаков.",
		ErrInputInvalid:      "Не удалось прочитать поля из --input: %s.",
		InputNotFound:        "файл не найден",
		InputUnreadable:      "файл не удаётся прочитать",
		InputNotObject:       "текст не является объектом JSON",
		InputUnknownField:    "неизвестное поле «%s»",
		InputNotString:       "поле «%s» должно быть строкой",
		ErrTaskNotFound:      "Задача %s не найдена.",
		HintTaskListAll:      "Посмотреть все задачи",
		ErrTaskUndetermined:  "В текущей папке нет задачи: %s",
		HintTaskList:         "Посмотреть задачи",
		ErrTaskKeyInvalid:    "Недопустимый номер задачи: «%s».",
		HintTaskKey:          "Укажите номер с префиксом проекта: <префикс>-<число>.",
		ErrFlagValueInvalid:  "Недопустимое значение флага %s: «%s».",

		// The way of a task: gentry stage, step, note, artifact.
		CmdStageSummary:           "Показать этап задачи",
		CmdStageDesc:              "Показать текущий этап задачи.",
		CmdStageShowSummary:       "Показать текущий этап задачи",
		CmdStageShowDesc:          "Показать текущий этап задачи: исполнителя, выход, переходы и инструкцию.",
		CmdStageExitSummary:       "Закрыть этап выходом",
		CmdStageExitDesc:          "Закрыть текущий этап выходом и перейти к следующему.\nЭтап закрывается, когда все его шаги выполнены или сняты.\nНа развилке укажите переход и обоснование.",
		CmdStageSkipSummary:       "Пропустить этап",
		CmdStageSkipDesc:          "Пропустить текущий этап с обоснованием и перейти к следующему.\nНа развилке укажите переход.",
		ArgKind:                   "<вид>",
		ArgNode:                   "<узел>",
		ArgReason:                 "<обоснование>",
		FlagExitKind:              "Вид выхода.\nДопустимые значения: artifact — артефакт задачи, result — результат, negative — отрицательный результат с указанием, где искали",
		FlagExitText:              "Текст выхода.",
		FlagExitArtifact:          "Имя артефакта задачи; указывается для выхода вида artifact.",
		FlagExitTo:                "Узел, к которому нужно перейти; на развилке обязателен.",
		FlagExitReason:            "Почему выбран переход; на развилке обязательно.",
		FlagSkipReason:            "Почему этап пропущен; на развилке — и почему выбран переход.",
		FlagInputFields:           "Поля одним объектом JSON: %s.\nВместо файла можно указать «-» — стандартный ввод. Вместе с флагами полей не указывается.",
		FlagInputOptions:          "Варианты в options — объекты с полями:\n  label — название без номера;\n  description — пояснение;\n  recommended — true у рекомендованного варианта.",
		FlagInputFieldsArgs:       "Поля одним объектом JSON: %s.\nВместо файла можно указать «-» — стандартный ввод. Вместе с аргументами и флагами полей не указывается.",
		CmdStepSummary:            "Задать и отметить шаги этапа",
		CmdStepDesc:               "Задать шаги текущего этапа и отметить их выполнение.",
		CmdStepAddSummary:         "Добавить шаги этапа",
		CmdStepAddDesc:            "Добавить шаги текущего этапа после имеющихся.",
		ArgStep:                   "<шаг>",
		ArgStepDesc:               "Шаг — одна строка до 120 знаков; можно указать несколько шагов.",
		CmdStepDoneSummary:        "Отметить шаг выполненным",
		CmdStepDoneDesc:           "Отметить шаг текущего этапа выполненным.",
		ArgStepNumberDesc:         "Номер шага текущего этапа.",
		ArgCheck:                  "<проверка>",
		FlagStepCheck:             "Как проверен результат шага.",
		CmdStepDropSummary:        "Снять шаг",
		CmdStepDropDesc:           "Снять шаг текущего этапа с обоснованием.\nСнятый шаг остаётся в истории задачи.",
		FlagStepReason:            "Почему шаг снят.",
		CmdNoteSummary:            "Добавить или показать заметки задачи",
		CmdNoteDesc:               "Добавить или показать заметки задачи.",
		CmdNoteAddSummary:         "Добавить заметку к задаче",
		CmdNoteAddDesc:            "Добавить заметку к задаче: то, что нужно учесть дальше.\nЗаметки не изменяются и не удаляются.",
		ArgNoteDesc:               "Текст заметки.",
		CmdArtifactSummary:        "Сохранить артефакт задачи",
		CmdArtifactDesc:           "Сохранить артефакт задачи.",
		CmdArtifactSaveSummary:    "Сохранить артефакт задачи",
		CmdArtifactSaveDesc:       "Сохранить артефакт задачи: копию файла или ссылку.\nАртефакт с тем же именем заменяется.",
		ArgName:                   "<имя>",
		ArgArtifactNameDesc:       "Имя артефакта: латинские буквы, цифры, точка, дефис и подчёркивание.",
		ArgURL:                    "<адрес>",
		FlagArtifactFile:          "Файл, копию которого нужно сохранить.",
		FlagArtifactURL:           "Адрес артефакта, например документа.",
		FlagTaskShowPath:          "Показать пройденный путь подробно: выходы, переходы и шаги.",
		StageRound:                "%s, круг %d",
		StageFinished:             "сценарий пройден",
		StageTask:                 "Задача: %s",
		StagePartText:             "Фрагмент %s:",
		ColTransition:             "ПЕРЕХОД",
		ColCondition:              "УСЛОВИЕ",
		ColReturns:                "ВОЗВРАТЫ",
		StageReturns:              "%d из %d",
		StepNumber:                "Номер шага: %d",
		StepNumbers:               "Номера шагов: %d–%d",
		StepsLeft:                 "Осталось шагов: %d",
		StepsAdded:                "К этапу добавлено шагов: %d.",
		StepMarkedDone:            "Шаг %d выполнен.",
		StepMarkedDropped:         "Шаг %d снят.",
		StepsNone:                 "У этапа нет шагов.",
		ColStepNumber:             "№",
		ColStep:                   "ШАГ",
		ColComment:                "ПОЯСНЕНИЕ",
		StepStatePlanned:          "запланирован",
		StepStateDone:             "выполнен",
		StepStateDropped:          "снят",
		HintStageExit:             "Закрыть этап",
		StageExited:               "Этап «%s» закрыт.",
		StageSkipped:              "Этап «%s» пропущен.",
		ExitKindLine:              "Вид выхода: %s",
		ExitKindArtifact:          "артефакт %s",
		ExitKindResult:            "результат",
		ExitKindNegative:          "отрицательный результат",
		ExitTextLine:              "Выход: %s",
		TransitionLine:            "Переход: %s",
		ReasonLine:                "Обоснование: %s",
		ProgressLine:              "Прогресс: %s",
		ProgressValue:             "%d из %d",
		ProgressRange:             "%d из %d–%d",
		HintStageShow:             "Посмотреть этап",
		NoteAdded:                 "Заметка %d добавлена.",
		ArtifactSaved:             "Артефакт %s сохранён.",
		ArtifactReplaced:          "Артефакт %s заменён.",
		ArtifactFileLine:          "Файл: %s",
		ArtifactURLLine:           "Адрес: %s",
		ColRound:                  "КРУГ",
		ColOutcome:                "ИТОГ",
		OutcomeSkip:               "пропуск",
		OutcomeCurrent:            "идёт",
		CmdNoteListSummary:        "Показать заметки задачи",
		CmdNoteListDesc:           "Показать заметки задачи с этапом, на котором они добавлены.",
		NoteHeading:               "%d. %s:",
		NotesNone:                 "У задачи нет заметок.",
		FlagTaskShowStatement:     "Показать постановку задачи и решения оператора.",
		StatementHeading:          "Постановка задачи %s:",
		HintStatement:             "Посмотреть постановку",
		HintNotes:                 "Посмотреть заметки",
		ColArtifact:               "АРТЕФАКТ",
		ColKind:                   "ВИД",
		ColSaved:                  "СОХРАНЁН",
		ColPlace:                  "МЕСТО",
		ArtifactKindFile:          "файл",
		ArtifactKindLink:          "ссылка",
		OutcomeLine:               "Итог: %s",
		RecordedLine:              "Записано: %s",
		RecordedByAgent:           "агентом",
		ClosedLine:                "Закрыт: %s",
		ErrScenarioFinished:       "Сценарий задачи %s пройден.",
		ErrExitKindMissing:        "Не указан вид выхода.",
		ErrExitTextMissing:        "Не указан текст выхода.",
		ErrExitArtifactMissing:    "Не указан артефакт выхода.",
		ErrForkToMissing:          "На развилке не указан переход.",
		ErrForkReasonMissing:      "На развилке не указано обоснование перехода.",
		ErrReasonMissing:          "Не указано обоснование перехода.",
		HintStageTransitions:      "Посмотреть переходы",
		ErrSkipReasonMissing:      "Не указано обоснование пропуска.",
		ErrTransitionNotFound:     "У этапа «%s» нет перехода к узлу %s.",
		ErrReturnLimit:            "Возвраты к узлу %s исчерпаны.",
		ReturnsLine:               "Возвратов: %d из %d",
		HintOtherTransitions:      "Посмотреть другие переходы",
		ErrStepsEmpty:             "У этапа «%s» нет шагов.",
		HintStepAdd:               "Добавить шаги",
		ErrStepsOpen:              "У этапа есть невыполненные шаги.",
		StepsOpenHeading:          "Невыполненные шаги:",
		HintStepDone:              "Отметить шаг выполненным",
		HintStepDrop:              "Снять шаг",
		ErrStepNotFound:           "У этапа нет шага %d.",
		HintSteps:                 "Посмотреть шаги",
		ErrStepDoneAlready:        "Шаг %d уже выполнен.",
		ErrStepDroppedAlready:     "Шаг %d уже снят.",
		ErrStepNumberInvalid:      "Недопустимый номер шага: «%s».",
		ErrStepNumberMissing:      "Не указан номер шага.",
		ErrStepsMissing:           "Не указан ни один шаг.",
		ErrStepTooLong:            "Шаг длиннее 120 знаков.",
		ErrStepMultiline:          "Шаг состоит из нескольких строк.",
		HintStep:                  "Укажите шаг одной строкой не длиннее 120 знаков.",
		ErrDropReasonMissing:      "Не указано обоснование снятия шага.",
		ErrNoteMissing:            "Не указан текст заметки.",
		ErrArtifactNotFound:       "Артефакт %s не сохранён.",
		HintArtifactSave:          "Сохранить артефакт",
		ErrArtifactNameMissing:    "Не указано имя артефакта.",
		ErrArtifactSourceMissing:  "Не указан файл или адрес артефакта.",
		ErrArtifactNameInvalid:    "Недопустимое имя артефакта: «%s».",
		HintArtifactName:          "Укажите имя из латинских букв, цифр, точки, дефиса и подчёркивания.",
		ErrArtifactURLInvalid:     "Недопустимый адрес артефакта: «%s».",
		HintArtifactURL:           "Укажите адрес с http:// или https:// в начале.",
		ErrArtifactFileNotFound:   "Файл артефакта не найден: %s",
		HintArtifactFile:          "Проверьте путь к файлу и повторите команду.",
		ErrArtifactFileTooLarge:   "Файл артефакта больше 10 МБ: %s",
		HintArtifactLink:          "Сохранить ссылку вместо файла",
		ErrArtifactForKind:        "Артефакт указывается только у выхода вида artifact.",
		ErrInputWithArgs:          "Аргументы команды и --input нельзя указывать вместе.",
		InputNotInteger:           "поле «%s» должно быть целым числом",
		InputNotList:              "поле «%s» должно быть массивом строк",
		InputBadValue:             "недопустимое значение поля «%s»",
		CmdOperatorSummary:        "Записать решение оператора",
		CmdOperatorDesc:           "Записать решение оператора по задаче.",
		CmdOperatorRecordSummary:  "Записать решение оператора",
		CmdOperatorRecordDesc:     "Записать решение оператора по задаче: ответ на вопрос или указание без вопроса.\nСлова оператора указываются дословно.\nВарианты ответа передаются через --input.\nРешения оператора не изменяются и не удаляются; чтобы отменить решение, запишите новое.",
		ArgQuestion:               "<вопрос>",
		ArgAnswer:                 "<ответ>",
		FlagDecisionQuestion:      "Вопрос, на который ответил оператор.",
		FlagDecisionAnswer:        "Ответ или указание оператора дословно.",
		FlagDecisionAllowReturn:   "Узел, к которому оператор разрешил ещё один возврат сверх предела.",
		DecisionRecorded:          "Решение оператора записано.",
		AllowedReturnLine:         "Разрешён возврат: %s",
		DecisionsHeading:          "Решения оператора:",
		DecisionHeading:           "%d. %s, записано %s:",
		DecisionQuestion:          "Вопрос",
		DecisionAnswer:            "Ответ",
		DecisionOptions:           "Варианты:",
		OptionRecommended:         "%s (рекомендован)",
		HintStatementDecisions:    "Посмотреть постановку и решения оператора",
		HintAllowReturn:           "Записать разрешение оператора",
		ErrAnswerMissing:          "Не указан ответ оператора.",
		ErrReturnNotFound:         "У этапа «%s» нет возврата к узлу %s.",
		ErrOptionsQuestionMissing: "Не указан вопрос, к которому относятся варианты.",
		ErrOptionsTooFew:          "Вариантов меньше двух.",
		HintOptionsTooFew:         "Укажите не меньше двух вариантов или ни одного.",
		ErrOptionsRecommendedMany: "Рекомендовано больше одного варианта.",
		HintOptionsRecommended:    "Отметьте рекомендованным не больше одного варианта.",
		ErrOptionLabelEmpty:       "Не указано название варианта %d.",
		ErrOptionLabelMultiline:   "Название варианта %d состоит из нескольких строк.",
		ErrOptionLabelTooLong:     "Название варианта %d длиннее 120 знаков.",
		HintOptionLabel:           "Укажите название варианта одной строкой не длиннее 120 знаков.",
		InputNotObjects:           "поле «%s» должно быть массивом объектов",
		InputBadOption:            "вариант %d должен быть объектом с полями label, description и recommended",
		FlagTaskTask:              "Отменённая задача, которую нужно взять заново.\nНазвание и постановка берутся из неё.",
		CmdTaskCloseSummary:       "Закрыть задачу",
		CmdTaskCloseDesc:          "Закрыть задачу и освободить её рабочую копию.\nЗадача закрывается после прохождения сценария.\nВ рабочей копии не должно быть незакоммиченных изменений.\nЗакрытая задача не изменяется.",
		CmdTaskCancelSummary:      "Отменить задачу",
		CmdTaskCancelDesc:         "Отменить задачу и освободить её рабочую копию.\nВ рабочей копии не должно быть незакоммиченных изменений.\nОтменённую задачу можно взять заново: gentry task take --task <задача>",
		FlagCancelReason:          "Почему задача отменяется.",
		CmdTaskAttemptsSummary:    "Показать попытки задачи",
		CmdTaskAttemptsDesc:       "Показать попытки задачи или одну попытку целиком.\nКаждое взятие отменённой задачи заново начинает следующую попытку.",

		ToolTaskTakeDesc:          "Взять задачу в работу: зарезервировать рабочую копию, сохранить название, постановку и флоу задачи.\nКопия должна быть в пуле, без задачи и без незакоммиченных изменений.\nОтменённую задачу можно взять заново: укажите её номер в поле task.",
		ToolTaskCancelDesc:        "Отменить задачу и освободить её рабочую копию.\nВ рабочей копии не должно быть незакоммиченных изменений.\nОтменённую задачу можно взять заново инструментом task_take.",
		ToolOperatorRecordDesc:    "Записать решение оператора по задаче: ответ на вопрос или указание без вопроса.\nСлова оператора указываются дословно.\nРешения оператора не изменяются и не удаляются; чтобы отменить решение, запишите новое.",
		ErrToolFields:             "Не удалось прочитать поля инструмента: %s.",
		ArgAttempt:                "<попытка>",
		ArgAttemptDesc:            "Номер попытки; без него — перечень попыток.",
		TaskClosed:                "Задача %s закрыта.",
		TaskCancelled:             "Задача %s отменена.",
		WorktreeReleased:          "Рабочая копия освобождена: %s",
		TaskTakenAnew:             "Задача %s взята заново.",
		AttemptLine:               "Попытка: %d",
		TaskClosedByAgent:         "Закрыта агентом: %s",
		TaskClosedByOperator:      "Закрыта оператором: %s",
		TaskCancelledByAgent:      "Отменена агентом: %s",
		TaskCancelledByOperator:   "Отменена оператором: %s",
		CancelReasonLine:          "Обоснование отмены: %s",
		AttemptHeading:            "Задача %s, попытка %d: %s",
		NotesHeading:              "Заметки:",
		ColAttempt:                "ПОПЫТКА",
		ColTaken:                  "ВЗЯТА",
		ColEnded:                  "ЗАВЕРШЕНА",
		ColCancelReason:           "ОБОСНОВАНИЕ ОТМЕНЫ",
		HintTaskClose:             "Закрыть задачу",
		HintTaskAgain:             "Взять задачу заново",
		HintAttempts:              "Посмотреть прежние попытки",
		HintAttemptsList:          "Посмотреть попытки",
		HintAttempt:               "Посмотреть попытку",
		ErrScenarioNotFinished:    "Сценарий задачи %s ещё не пройден.",
		ErrTaskInWork:             "Задача %s уже в работе.",
		ErrTaskProjectMismatch:    "Задача %s относится к другому проекту.",
		TaskProjectLine:           "Проект задачи: %s",
		WorktreeProjectLine:       "Проект рабочей копии: %s",
		HintWorktreeListProject:   "Посмотреть рабочие копии проекта",
		ErrAttemptNotFound:        "У задачи %s нет попытки %s.",
		AttemptsCountLine:         "Попыток: %d",
		SkillWorkingOnTask:        "Взять задачу проекта под Gentry и вести её по флоу до закрытия: этапы, шаги, вопросы и решения оператора. Скилл вызывается, когда оператор ставит задачу в рабочей копии проекта под Gentry, и словами «возьми задачу», «работаем», «продолжай». Отмена задачи в скилл не входит.",
		SkillCancelingTask:        "Отменить задачу проекта под Gentry по слову оператора и разобрать незакоммиченные изменения в её рабочей копии. Скилл вызывается словами «отмени задачу», «брось задачу», «задача больше не нужна».",
		IntroNoTask:               "Задача в этой копии не взята.",
		HintIntroTake:             "Взять задачу, когда оператор её поставит: скилл %s",
		IntroSteps:                "Шаги этапа: выполнено %d из %d",
		IntroNoSteps:              "Шаги этапа: не заданы",
		HintIntroContinue:         "Продолжить задачу по слову оператора: скилл %s",
		IntroPluginStale:          "Плагин Gentry не соответствует программе gentry: скиллы могут описывать прежние команды.",
		HintIntroPluginStale:      "Сообщить оператору и по его слову обновить плагин",
		SkillEditingFlow:          "Показать, написать, поправить и применить флоу проекта под Gentry: сценарии, этапы, фрагменты, субагентов проекта и библиотеки; разобрать конфликт при применении. Скилл вызывается словами «покажи флоу», «какие есть сценарии», «покажи этап», «напиши флоу», «добавь этап», «добавь сценарий», «поправь сценарий», «переименуй этап», «удали этап», «добавь субагента», «поправь субагента», «сделай субагента общим», «примени флоу», «разбери конфликт флоу». Ведение задачи в скилл не входит.",
		DiffReportFile:            "Файл изменений: %s",
		DiffScenarios:             "Сценарии:",
		DiffStages:                "Этапы:",
		DiffParts:                 "Фрагменты:",
		DiffAgents:                "Субагенты проекта:",
		DiffLibraryAgents:         "Субагенты библиотеки:",
		DiffItem:                  "%s: %s",
		DiffStage:                 "%s (%s)",
		DiffReturn:                "возврат «%s → %s»",
		DiffTransition:            "переход «%s → %s»",
		DiffCondition:             "если %s",
		DiffNoCondition:           "без условия",
		DiffInstead:               "%s вместо %d",
		DiffUsedBy:                "касается проектов %s",
		DiffUnused:                "не используется ни одним проектом",
		DiffScenarioUnreadable:    "в сценарии есть ошибки",
		DiffFlowUnchanged:         "Флоу проекта не изменён.",
		DiffLegend:                "Обозначения: + добавлено, ~ изменено, − удалено.",
		HintDiffLibraryApply:      "Применить изменения библиотеки",
		ErrNoDrafts:               "Ни у флоу проекта %s, ни у библиотеки субагентов нет черновика.",
		ReportTitle:               "# Изменения флоу проекта %s",
		ReportProblemsNone:        "Ошибки черновика: нет",
		ReportProblems:            "Ошибки черновика:",
		ReportCreated:             "Файл сформирован: %s",
		ReportSummary:             "## Сводка",
		ColObject:                 "Объект",
		ColChange:                 "Изменение",
		ColField:                  "Поле",
		ColWas:                    "Было",
		ColNow:                    "Стало",
		ReportLegend:              "Обозначения на схемах: зелёный — добавлено, жёлтый — изменено, красный пунктир — удалено. Сплошная стрелка — путь по умолчанию, пунктирная — переход с условием.",
		ReportObjScenario:         "Сценарий «%s» (%s)",
		ReportObjStage:            "Этап «%s» (%s)",
		ReportHeading:             "## %s",
		ReportHeadingChange:       "## %s — %s",
		ReportLibrary:             "## Библиотека субагентов",
		ReportLibraryAgent:        "### Субагент %s — %s",
		ReportProjects:            "Касается проектов: %s",
		ReportChanges:             "Изменения:",
		ReportAdded:               "Добавлен %s.",
		ReportRemoved:             "Удалён %s.",
		ReportModified:            "Изменён %s: %s.",
		ReportNodeAdded:           "Добавлен этап «%s».",
		ReportNodeRemoved:         "Удалён этап «%s».",
		ReportNodeStage:           "В узле %s этап «%s» заменён этапом «%s».",
		ReportNodeStageChanged:    "Изменён этап «%s».",
		ReportTitleChanged:        "Изменено название: «%s» вместо «%s».",
		ReportStartChanged:        "Изменён начальный узел: %s вместо %s.",
		ReportUnreadable:          "Схема не построена: в сценарии есть ошибки.",
		ReportFieldTitle:          "Название",
		ReportFieldExit:           "Выход",
		ReportFieldExecutor:       "Исполнитель",
		ReportFieldParts:          "Фрагменты",
		ReportFieldPurpose:        "Назначение",
		ReportFieldCapabilities:   "Возможности",
		SchemaExecutor:            "исполнитель: %s",
		SchemaOperator:            "оператор",
		SchemaWas:                 "(было %d)",
		ErrReportWrite:            "Не удалось записать файл изменений: %s",
		CmdAgentsSummary:          "Разложить субагентов флоу в рабочие копии",
		CmdAgentsDesc:             "Разложить субагентов флоу в рабочие копии проекта.",
		CmdAgentsSyncSummary:      "Разложить субагентов флоу во все рабочие копии пула проекта",
		CmdAgentsSyncDesc:         "Разложить субагентов флоу во все рабочие копии пула проекта.\nВ копию с задачей раскладываются субагенты снимка флоу задачи, в свободную — субагенты действующего флоу.\nСубагенты, которых нет во флоу, удаляются из копии; субагенты, разложенные не Gentry, не изменяются.",
		FlagAgentsSyncProject:     "Проект, рабочие копии которого нужно разложить.\nПо умолчанию — проект текущей папки.",
		AgentsSynced:              "Субагенты разложены в рабочие копии проекта %s.",
		AgentsInPlace:             "Субагенты в рабочих копиях проекта %s соответствуют флоу.",
		AgentsNextSession:         "Изменения вступят в силу со следующей сессии агента.",
		AgentsWorktreeChanged:     "Субагенты в рабочей копии изменены: %s.",
		AgentsFreeSynced:          "Субагенты разложены в свободные рабочие копии проекта %s.",
		AgentsFreeSyncedAll:       "Субагенты разложены в свободные рабочие копии.",
		AgentsWorktreeMissing:     "папки нет, копия пропущена",
		AgentAdded:                "добавлен %s",
		AgentsAdded:               "добавлены %s",
		AgentUpdated:              "обновлён %s",
		AgentsUpdated:             "обновлены %s",
		AgentRemoved:              "удалён %s",
		AgentsRemoved:             "удалены %s",
		ColTask:                   "ЗАДАЧА",
		ColAgents:                 "СУБАГЕНТЫ",
		ColChanges:                "ИЗМЕНЕНИЯ",
		ColFile:                   "ФАЙЛ",
		ColReason:                 "ПРИЧИНА",
		AgentsReasonTracked:       "файл отслеживается git проекта",
		AgentsReasonForeign:       "файл разложен не Gentry",
		ErrAgentsConflict:         "Субагентов нельзя разложить: файлы с их именами уже есть.",
		HintAgentsConflict:        "Необходимо переименовать субагента во флоу или удалить файл из рабочей копии, затем повторить команду.",
		AgentsConflictWarning:     "Часть субагентов не разложена: файлы с их именами уже есть.",
		HintAgentsConflictWarning: "Разложить субагентов после разбора файлов",
		AgentsSyncFailed:          "Субагентов не удалось разложить.",
		AgentsSyncFailedReason:    "Причина: %s",
		ErrAgentsBusy:             "Субагентов в рабочие копии этого репозитория раскладывает другая команда Gentry.",
		HintAgentsSyncFailed:      "Повторить раскладку",
		AgentFileMark:             "файл разложен из флоу проекта и перезаписывается при раскладке субагентов.",
		ExcludeBlockStart:         "субагенты, разложенные в рабочие копии",
		ExcludeBlockEnd:           "конец блока",
	},
	plurals: map[Key][]string{
		FlowRounds: {"не более %d возврата", "не более %d возвратов", "не более %d возвратов"},
		DiffRounds: {"до %d раза", "до %d раз", "до %d раз"},
	},
}
