package msg

// ru is the Russian catalog. Every text is a complete sentence in a formal but
// readable style and starts with a capital letter; errors are printed as they
// are, without a program prefix.
var ru = catalog{
	form:  russianForm,
	forms: 3,
	texts: map[Key]string{
		HelpIntro:               "Gentry ведёт задачи агента по флоу проекта и хранит их состояние.",
		HelpUsage:               "Использование:\n  gentry <команда> [аргументы] [флаги]",
		HelpMore:                "Посмотреть описание команды: gentry <команда> --help",
		HelpUsageTitle:          "Использование:",
		HelpArgs:                "Аргументы:",
		HelpFlags:               "Флаги:",
		HelpSectionMaint:        "Установка и обслуживание:",
		FlagJSON:                "Вывести результат в формате JSON.",
		CmdVersionDesc:          "Показать версию Gentry.",
		FlagVersionJSON:         "Вывести в формате JSON с версиями контракта, хранилища состояния и формата знания.",
		CmdSetupDesc:            "Подключить Gentry к ИИ-инструменту: сформировать и зарегистрировать плагин.\nПосле обновления Gentry команду нужно повторить.",
		ArgTool:                 "<ИИ-инструмент>",
		ArgToolDesc:             "ИИ-инструмент для подключения.\nДопустимые значения: %s",
		ArgNumber:               "<номер>",
		CmdVersionSummary:       "Показать версию Gentry",
		ErrUnknownCommand:       "Неизвестная команда «%s».",
		HintUnknownCommand:      "Посмотреть перечень команд: gentry --help",
		ErrInternal:             "Внутренняя ошибка Gentry: %v",
		ErrUnexpectedArgs:       "Команда %s не принимает аргументов.",
		ErrExtraArgs:            "Лишние аргументы команды %s: %s",
		ErrUnknownFlag:          "Команда %s не поддерживает флаг %s.",
		ErrFlagValue:            "Флаг %s не принимает значения.",
		VersionGentry:           "Версия Gentry: %s",
		ErrHookEventMissing:     "Не указано событие хука.",
		ErrHookEventUnknown:     "Неизвестное событие хука «%s».",
		HintHookEvents:          "Допустимые значения: %s",
		CmdSetupSummary:         "Подключить Gentry к ИИ-инструменту",
		ErrSetupToolMissing:     "Не указан ИИ-инструмент.",
		ErrSetupToolUnknown:     "Неизвестный ИИ-инструмент «%s».",
		SetupInstalled:          "Gentry подключён к Claude Code.\nПлагин начнёт работать со следующей сессии.",
		SetupUpdated:            "Плагин Gentry в Claude Code обновлён.\nИзменения вступят в силу со следующей сессии.",
		SetupUnchanged:          "Gentry уже подключён к Claude Code.",
		SetupDisabled:           "Плагин Gentry отключён в Claude Code.\n\nВключить плагин: claude plugin enable gentry@gentry",
		ErrToolNotFound:         "Программа %s не найдена.",
		HintToolNotFound:        "Установите %s и повторите: gentry setup %s",
		ErrToolFailed:           "Не удалось подключить плагин, команда «%s» завершилась ошибкой: %s",
		ErrHomeUnknown:          "Не удалось определить папку данных Gentry: нет ни GENTRY_HOME, ни домашней папки пользователя.",
		HintHomeUnknown:         "Задайте папку данных переменной окружения GENTRY_HOME.",
		ErrIO:                   "Не удалось записать файлы в %s: %v",
		ErrFlagValueMissing:     "Не указано значение флага %s.",
		ErrEventsAfter:          "Недопустимое значение флага --after: «%s».",
		ErrStateNewer:           "Хранилище состояния создано более новой версией Gentry: схема %d, поддерживается до %d.",
		HintStateNewer:          "Обновите Gentry.",
		ErrStateUnavailable:     "Хранилище состояния недоступно: %v",
		HintStateUnavail:        "Повторите команду; если ошибка повторится, проверьте доступ к файлу: %s",
		HelpSectionProjects:     "Проекты и рабочие копии:",
		HelpActions:             "Действия:",
		HelpGroupUsage:          "gentry %s <действие> [аргументы] [флаги]",
		HelpGroupMore:           "Посмотреть описание действия: gentry %s <действие> --help",
		ErrActionMissing:        "Не указано действие команды %s.",
		ErrActionUnknown:        "Неизвестное действие «%s» команды %s.",
		HintActions:             "Посмотреть перечень действий: gentry %s --help",
		CmdProjectDesc:          "Подключить проект или показать подключённые проекты.",
		CmdProjectSummary:       "Подключить проект или показать подключённые проекты",
		CmdProjectAddSummary:    "Подключить проект",
		CmdProjectAddDesc:       "Подключить проект: связать рабочую копию кода с репозиторием знания.\nВ пул вносятся основная рабочая копия и та, в которой выполнена команда.\nКоманда выполняется в рабочей копии кода проекта.",
		ArgProjectID:            "<идентификатор>",
		ArgProjectIDDesc:        "Идентификатор проекта: 2–32 строчные латинские буквы, цифры и дефисы, первая — буква.\nОбязателен, если знание создаётся заново; иначе берётся из знания.",
		ArgPath:                 "<путь>",
		FlagKnowledgeDesc:       "Папка репозитория знания.\nЕсли её нет или она пуста, репозиторий создаётся.",
		ArgPrefix:               "<префикс>",
		FlagPrefixDesc:          "Префикс номеров задач: 2–10 заглавных латинских букв.\nПо умолчанию — буквы идентификатора.",
		CmdProjectListSummary:   "Показать подключённые проекты",
		CmdProjectListDesc:      "Показать проекты, подключённые на этой машине.",
		ProjectAdded:            "Проект %s подключён.",
		ProjectKnowledge:        "Знание проекта: %s",
		ProjectKnowledgeNew:     "Знание проекта (репозиторий создан): %s",
		ProjectPrefix:           "Префикс номеров задач: %s",
		ProjectMainWorktree:     "Основная рабочая копия: %s",
		ProjectWorktreeAdded:    "Также внесена в пул: %s",
		ProjectUnchanged:        "Проект %s уже подключён.",
		ProjectsNone:            "Подключённых проектов нет.\n\nПодключить проект: gentry project add",
		ErrKnowledgeFlagMissing: "Не указан репозиторий знания.",
		ErrProjectIDMissing:     "Для нового знания нужен идентификатор проекта.",
		ErrProjectIDInvalid:     "Недопустимый идентификатор проекта: «%s».",
		ErrPrefixUnderivable:    "Не удалось получить префикс номеров задач из идентификатора «%s».",
		HintPrefixUnderivable:   "Укажите префикс из 2–10 заглавных латинских букв: --prefix <префикс>",
		ErrPrefixInvalid:        "Недопустимое значение флага --prefix: «%s».",
		ErrNotGitRepo:           "Папка не является рабочей копией git: %s",
		HintNotGitRepo:          "Выполните команду в рабочей копии кода проекта.",
		ErrKnowledgeNotEmpty:    "Папка не пуста и не является репозиторием git: %s",
		ErrKnowledgeForeign:     "В репозитории уже есть файлы, но он не является знанием проекта: %s",
		HintKnowledgeDir:        "Укажите пустую папку, новый путь или репозиторий знания проекта.",
		ErrKnowledgeNested:      "Знание проекта и рабочая копия вложены одна в другую:\n  %s\n  %s",
		HintKnowledgeNested:     "Знание проекта должно быть отдельным репозиторием вне рабочей копии.",
		ErrKnowledgeBadFile:     "Сведения о проекте в знании повреждены: %s",
		HintKnowledgeBadFile:    "Восстановите их из истории git репозитория знания: %s",
		ErrKnowledgeNewer:       "Знание проекта записано в более новом формате: версия %d, поддерживается до %d.",
		HintKnowledgeNewer:      "Обновите Gentry.",
		ErrKnowledgeMismatch:    "Указан идентификатор проекта «%s», а в знании записан «%s».",
		HintKnowledgeMismatch:   "Не указывайте идентификатор или укажите «%s».",
		ErrProjectExists:        "Проект %s уже подключён с другим знанием: %s",
		ErrProjectClone:         "Проект %s уже подключён, основная рабочая копия: %s",
		ErrPrefixTaken:          "Префикс %s уже используется проектом %s.",
		HintPrefixTaken:         "Укажите другой префикс: --prefix <префикс>",
		ErrWorktreeTaken:        "Рабочая копия уже в пуле проекта %s: %s",
		HintGitNotFound:         "Установите git и повторите команду.",
		ErrGitFailed:            "Команда «%s» завершилась ошибкой: %s",
		CauseInfoSyntax:         "их не удаётся прочитать",
		CauseInfoMissing:        "нет поля %s",
		CauseInfoUnknown:        "неизвестное поле «%s»",
		CauseInfoValue:          "недопустимое значение поля %s: «%v»",
		ProjectUnpooled:         "Рабочие копии репозитория, не внесённые в пул:",
		HintProjectUnpooled:     "Внести копию в пул: gentry worktree add <путь>",
		HintProjectClone:        "Внести эту копию в пул: gentry worktree add --project %s",
		CmdWorktreeSummary:      "Внести рабочую копию в пул проекта или показать рабочие копии",
		CmdWorktreeDesc:         "Внести рабочую копию в пул проекта или показать рабочие копии.",
		CmdWorktreeAddSummary:   "Внести рабочую копию в пул проекта",
		CmdWorktreeAddDesc:      "Внести рабочую копию в пул проекта.\nКоманда нужна для копий, сделанных после подключения проекта, и для отдельных клонов.",
		ArgWorktreePathDesc:     "Папка рабочей копии; по умолчанию — текущая.",
		FlagWorktreeAddProject:  "Проект, в пул которого вносится копия.\nПо умолчанию определяется по копии или текущей папке.",
		CmdWorktreeListSummary:  "Показать рабочие копии",
		CmdWorktreeListDesc:     "Показать рабочие копии: ветку, занятость и признак основной копии.",
		FlagWorktreeListProject: "Проект, копии которого нужно показать.\nПо умолчанию — проект текущей папки, вне проекта — все проекты.",
		WorktreeAdded:           "Рабочая копия внесена в пул проекта %s: %s",
		WorktreeUnchanged:       "Рабочая копия уже в пуле проекта %s: %s",
		WorktreesNone:           "Рабочих копий нет.",
		WorktreeMain:            "основная",
		WorktreeFree:            "свободна",
		WorktreeMissing:         "папка не найдена",
		ErrWorktreeKnowledge:    "Папка знания проекта %s не может быть рабочей копией: %s",
		ErrProjectUndetermined:  "Не удалось определить проект для папки %s",
		HintProjectUndetermined: "Укажите --project или выполните команду в рабочей копии проекта.",
		ErrProjectNotFound:      "Проект «%s» не подключён.",
		HintProjectNotFound:     "Посмотреть перечень проектов: gentry project list",
		ValueNone:               "—",
		ColProject:              "ПРОЕКТ",
		ColPrefix:               "ПРЕФИКС",
		ColKnowledge:            "ЗНАНИЕ",
		ColMainWorktree:         "ОСНОВНАЯ КОПИЯ",
		ColWorktree:             "РАБОЧАЯ КОПИЯ",
		ColBranch:               "ВЕТКА",
		ColState:                "СОСТОЯНИЕ",
		HintEventsAfter:         "Укажите номер события — целое число не меньше 0.",
		HintKnowledgeFlag:       "Укажите папку знания: --knowledge <путь>",
		HintProjectIDMissing:    "Укажите идентификатор: gentry project add <идентификатор> --knowledge <путь>",
		HintProjectIDInvalid:    "Укажите 2–32 строчные латинские буквы, цифры и дефисы, первая — буква.",
		HintPrefixInvalid:       "Укажите от 2 до 10 заглавных латинских букв.",

		// The flow: gentry flow and the problems of a flow.
		HelpSectionProcess:            "Процесс оператора:",
		CmdFlowSummary:                "Показать или изменить флоу проекта",
		CmdFlowDesc:                   "Показать или изменить флоу проекта.\nПравки в папке флоу — черновик; действующим он становится после применения.",
		CmdFlowShowSummary:            "Показать флоу проекта",
		CmdFlowShowDesc:               "Показать сценарии, этапы и субагентов флоу проекта.\nС флагом объекта выводится этот объект подробно.\nЕсли во флоу есть ошибки, выводится их перечень.",
		ArgScenario:                   "<сценарий>",
		FlagFlowShowProject:           "Проект, флоу которого нужно показать.\nПо умолчанию — проект текущей папки.",
		FlowProject:                   "Проект: %s",
		FlowScenario:                  "Сценарий: %s",
		FlowTitle:                     "Название: %s",
		FlowDefaultPath:               "Путь по умолчанию:",
		FlowConditional:               "Условные переходы:",
		FlowTransition:                "%s → %s: %s",
		FlowTransitionLimit:           "%s → %s, %s: %s",
		FlowEnd:                       "конец",
		FlowProblems:                  "Ошибки:",
		ColScenario:                   "СЦЕНАРИЙ",
		ColTitle:                      "НАЗВАНИЕ",
		ColStage:                      "ЭТАП",
		ColExecutor:                   "ИСПОЛНИТЕЛЬ",
		ColExit:                       "ВЫХОД",
		ColNode:                       "УЗЕЛ",
		ErrFlowNotFound:               "У проекта %s нет флоу.",
		ErrFlowInvalid:                "Во флоу проекта %s есть ошибки.",
		FlowObjCommon:                 "Общие правила флоу",
		FlowObjScenario:               "Сценарий %s",
		FlowObjNode:                   "Сценарий %s, узел %s",
		FlowObjStage:                  "Этап %s",
		FlowObjPart:                   "Фрагмент %s",
		ProblemSyntax:                 "%s: ошибка синтаксиса YAML.",
		ProblemEncoding:               "%s: текст не в кодировке UTF-8.",
		ProblemNotMapping:             "%s: описание должно состоять из полей.",
		ProblemUnknownField:           "%s: неизвестное поле «%s».",
		ProblemUnsupportedField:       "%s: поле «%s» не поддерживается этой версией Gentry.",
		ProblemMissingField:           "%s: не заполнено поле «%s».",
		ProblemNotString:              "%s: значение поля «%s» должно быть строкой.",
		ProblemMaxRounds:              "%s: значение поля «max_rounds» должно быть целым числом больше 0.",
		ProblemInclude:                "%s: значение поля «include» должно быть списком идентификаторов.",
		ProblemNext:                   "%s: значение поля «next» должно быть идентификатором узла или списком переходов.",
		ProblemNodes:                  "%s: значение поля «nodes» должно быть набором узлов.",
		ProblemInvalidID:              "%s: недопустимый идентификатор; допустимы до 64 строчных латинских букв, цифр и дефисов, первая — буква.",
		ProblemExtraFile:              "Файл не относится к флоу: %s",
		ProblemExtraDir:               "Папка не относится к флоу: %s",
		ProblemMissingInstruction:     "%s: нет инструкции.",
		ProblemOrphanInstruction:      "%s: есть инструкция, но нет полей этапа.",
		ProblemNoScenarios:            "Во флоу нет ни одного сценария.",
		ProblemUnknownStage:           "%s: этап %s не найден.",
		ProblemUnknownPart:            "%s: фрагмент %s не найден.",
		ProblemUnknownExecutor:        "%s: субагент %s не найден.",
		ProblemUnknownStart:           "%s: начальный узел %s не найден.",
		ProblemUnknownTarget:          "%s: узел перехода %s не найден.",
		ProblemReservedNode:           "%s: finish обозначает конец сценария и не может быть узлом.",
		ProblemUnreachable:            "%s: узел %s недостижим из начального узла.",
		ProblemDeadEnd:                "%s: из узла %s нельзя дойти до конца сценария.",
		ProblemUnlimitedLoop:          "%s: у цикла %s нет предела кругов.",
		ProblemLimitOutsideLoop:       "%s: у перехода %s → %s указан предел кругов, но переход не замыкает цикл.",
		ProblemLimitWithoutCondition:  "%s: у перехода %s → %s с пределом кругов нет условия.",
		ProblemSeveralDefaults:        "%s: переход без условия может быть только один.",
		ProblemDuplicateTransition:    "%s: два перехода к узлу %s.",
		ArgStage:                      "<этап>",
		ArgAgent:                      "<субагент>",
		ArgPart:                       "<фрагмент>",
		FlagShowScenario:              "Показать сценарий: путь, переходы и узлы.",
		FlagShowStage:                 "Показать этап: поля, фрагменты и инструкцию.",
		FlagShowAgent:                 "Показать субагента: поля и инструкцию.",
		FlagShowPart:                  "Показать фрагмент и его текст.",
		FlagShowDraft:                 "Показать черновик вместо действующего флоу.",
		CmdFlowDiffSummary:            "Показать изменения черновика",
		CmdFlowDiffDesc:               "Показать, какие объекты черновика отличаются от действующего флоу.",
		FlagFlowDiffProject:           "Проект, черновик которого нужно сравнить.\nПо умолчанию — проект текущей папки.",
		CmdFlowApplySummary:           "Применить черновик флоу",
		CmdFlowApplyDesc:              "Проверить черновик и сделать его действующим флоу на всех машинах.\nЧерновик с ошибками не применяется.",
		FlagFlowApplyProject:          "Проект, черновик которого нужно применить.\nПо умолчанию — проект текущей папки.",
		CmdFlowDiscardSummary:         "Отменить правки флоу",
		CmdFlowDiscardDesc:            "Вернуть папку флоу к действующему флоу.\nПравки черновика теряются.",
		FlagFlowDiscardProject:        "Проект, правки флоу которого нужно отменить.\nПо умолчанию — проект текущей папки.",
		FlowDraftOpened:               "Черновик существует.",
		FlowStage:                     "Этап: %s",
		FlowExecutor:                  "Исполнитель: %s",
		FlowExit:                      "Выход: %s",
		FlowParts:                     "Фрагменты: %s",
		FlowScenarios:                 "Сценарии: %s",
		FlowInstruction:               "Инструкция:",
		FlowAgent:                     "Субагент: %s",
		FlowSource:                    "Источник: %s",
		FlowPurpose:                   "Назначение: %s",
		FlowCapabilities:              "Возможности: %s",
		FlowStages:                    "Этапы: %s",
		FlowPart:                      "Фрагмент: %s",
		FlowText:                      "Текст:",
		FlowSourceProject:             "проект",
		FlowSourceLibrary:             "библиотека",
		ColAgent:                      "СУБАГЕНТ",
		ColSource:                     "ИСТОЧНИК",
		ColStages:                     "ЭТАПЫ",
		FlowChanges:                   "Изменения:",
		FlowChange:                    "%s: %s",
		FlowChangeAdded:               "добавлен",
		FlowChangeModified:            "изменён",
		FlowChangeRemoved:             "удалён",
		FlowCommonAdded:               "добавлены",
		FlowCommonModified:            "изменены",
		FlowCommonRemoved:             "удалены",
		FlowApplied:                   "Правки флоу применены.",
		FlowDiscarded:                 "Правки флоу отменены.",
		HintFlowShowDraft:             "Посмотреть черновик: gentry flow show --draft",
		HintFlowStage:                 "Посмотреть этап подробно: gentry flow show --stage <этап>",
		HintFlowApply:                 "Применить черновик: gentry flow apply",
		ErrFlowObjectNotFound:         "Во флоу проекта %s нет %s «%s».",
		ErrDraftObjectNotFound:        "В черновике флоу проекта %s нет %s «%s».",
		FlowKindScenario:              "сценария",
		FlowKindStage:                 "этапа",
		FlowKindAgent:                 "субагента",
		FlowKindPart:                  "фрагмента",
		HintFlowObjects:               "Посмотреть перечень объектов: gentry flow show",
		HintDraftObjects:              "Посмотреть перечень объектов: gentry flow show --draft",
		ErrDraftNotFound:              "У проекта %s нет черновика флоу.",
		ErrDraftInvalid:               "В черновике флоу проекта %s есть ошибки.",
		ErrConflictingFlags:           "Флаги %s и %s нельзя указывать вместе.",
		HintCommandHelp:               "Посмотреть описание команды: gentry %s --help",
		ErrDraftRead:                  "Не удалось прочитать черновик: %s",
		ErrDraftWrite:                 "Не удалось записать черновик: %s",
		ErrLibraryRead:                "Не удалось прочитать библиотеку субагентов: %s",
		FlowObjAgent:                  "Субагент %s",
		FlowObjLibraryAgent:           "Субагент %s из библиотеки",
		ProblemCapabilities:           "%s: значение поля «capabilities» должно быть списком из %s.",
		ProblemOrphanAgentInstruction: "%s: есть инструкция, но нет полей субагента.",
		FlowAppliedAt:                 "Флоу применён: %s",
		FlowDir:                       "Папка флоу: %s",
		ProblemExecutorInDraftLibrary: "%s: субагент %s есть только в черновике библиотеки.",
		ProblemLibraryExtraFile:       "Файл не относится к библиотеке субагентов: %s",
		ProblemLibraryExtraDir:        "Папка не относится к библиотеке субагентов: %s",
		CmdLibrarySummary:             "Применить или отменить правки библиотеки субагентов",
		CmdLibraryDesc:                "Применить или отменить правки библиотеки субагентов.\nПравки в папке библиотеки — черновик; действующей она становится после применения.",
		CmdLibraryDiffSummary:         "Показать изменения библиотеки",
		CmdLibraryDiffDesc:            "Показать, какие субагенты библиотеки изменены после применения.",
		CmdLibraryApplySummary:        "Применить правки библиотеки",
		CmdLibraryApplyDesc:           "Проверить правки библиотеки и сделать их действующими на всех машинах.\nПравки с ошибками не применяются.",
		CmdLibraryDiscardSummary:      "Отменить правки библиотеки",
		CmdLibraryDiscardDesc:         "Вернуть папку библиотеки к действующей библиотеке.\nПравки теряются.",
		LibraryAppliedAt:              "Библиотека применена: %s",
		LibraryApplied:                "Правки библиотеки применены.",
		LibraryDiscarded:              "Правки библиотеки отменены.",
		LibraryDir:                    "Папка библиотеки: %s",
		HintLibraryApply:              "Применить правки: gentry library apply",
		ErrLibraryDraftNotFound:       "У библиотеки субагентов нет черновика.",
		ErrLibraryDraftInvalid:        "В правках библиотеки есть ошибки.",
		CmdProcessSummary:             "Синхронизировать процесс оператора между машинами",
		CmdProcessDesc:                "Синхронизировать процесс оператора между машинами.\nПроцесс — флоу проектов и библиотека субагентов; он хранится в git и передаётся через удалённый репозиторий.",
		CmdProcessRemoteSummary:       "Подключить удалённый репозиторий процесса",
		CmdProcessRemoteDesc:          "Подключить удалённый репозиторий процесса или заменить его адрес.\nРепозиторий создаётся заранее, закрытым.\nЕсли процесс есть и на машине, и в репозитории, они сводятся; отличия машины становятся черновиками.",
		ArgRemote:                     "<адрес>",
		ArgRemoteDesc:                 "Адрес git-репозитория.",
		CmdProcessSyncSummary:         "Синхронизировать процесс",
		CmdProcessSyncDesc:            "Получить изменения процесса с других машин и отправить изменения этой машины.",
		CmdProcessStatusSummary:       "Показать состояние процесса",
		CmdProcessStatusDesc:          "Показать удалённый репозиторий, время синхронизации, черновики, неотправленные изменения и конфликты.",
		ProcessRemoteSet:              "Удалённый репозиторий подключён: %s",
		ProcessResultSent:             "Процесс: отправлен в удалённый репозиторий",
		ProcessResultReceived:         "Процесс: получен из удалённого репозитория",
		ProcessResultMerged:           "Процесс: сведён с удалённым, отличия этой машины стали черновиками",
		ProcessResultUnchanged:        "Процесс: совпадает с удалённым",
		ProcessDrafts:                 "Черновики:",
		HintProcessStatus:             "Посмотреть черновики: gentry process status",
		ProcessSynced:                 "Процесс синхронизирован.",
		ProcessReceived:               "Получено:",
		ProcessSent:                   "Отправлено:",
		ProcessRemote:                 "Удалённый репозиторий: %s",
		ProcessSyncedAt:               "Синхронизирован: %s",
		ProcessUnsent:                 "Не отправлено:",
		ProcessConflicts:              "Конфликты:",
		HintProcessRemote:             "Подключить удалённый репозиторий: gentry process remote <адрес>",
		HintProcessSync:               "Синхронизировать: gentry process sync",
		KindFlow:                      "флоу %s",
		KindLibrary:                   "библиотека субагентов",
		ErrRemoteMissing:              "Не указан адрес удалённого репозитория.",
		ErrProcessRemoteNotSet:        "Удалённый репозиторий процесса не подключён.",
		ErrRemoteUnavailable:          "Удалённый репозиторий недоступен: %s",
		HintRemoteAccess:              "Проверить доступ: git ls-remote %s",
		ErrRemoteNotProcess:           "Репозиторий не является репозиторием процесса: %s",
		ErrRemoteNewer:                "Процесс в репозитории записан более новой версией Gentry: %s",
		ErrProcessNotProcess:          "Папка процесса занята другим репозиторием: %s",
		ErrProcessNewer:               "Процесс на машине записан более новой версией Gentry: %s",
		ErrProcessBusy:                "Репозиторий процесса занят другой командой Gentry.",
		SyncReceived:                  "Получены изменения с другой машины:",
		SyncSkipped:                   "Синхронизация пропущена: удалённый репозиторий недоступен.",
		SyncDeferred:                  "Отправка отложена: удалённый репозиторий недоступен.",
		SyncFlowConflict:              "Флоу проекта %s изменён на другой машине; правки этой машины стали черновиком.",
		SyncLibraryConflict:           "Библиотека субагентов изменена на другой машине; правки этой машины стали черновиком.",
		SyncConflictDir:               "Варианты другой машины: %s",
		SyncBothChanged:               "Изменены на обеих машинах:",
		HintFlowDiffProject:           "Посмотреть отличия: gentry flow diff --project %s",
		HintLibraryDiff:               "Посмотреть отличия: gentry library diff",
		SyncFlowRestored:              "Изменение флоу проекта %s в обход Gentry стало черновиком: в нём ошибки.",
		SyncLibraryRestored:           "Изменение библиотеки субагентов в обход Gentry стало черновиком: в нём ошибки.",
	},
	plurals: map[Key][]string{
		FlowRounds: {"не более %d круга", "не более %d кругов", "не более %d кругов"},
	},
}
