// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry agents sync --json`: the subagents are laid out in every
// worktree of the pool of the project.
type AgentsSyncOutput struct {
	// Whether the layout changed any worktree.
	Changed bool `json:"changed"`

	// Identifier of the project.
	Project string `json:"project"`

	// Every worktree of the pool, the main one first, then by path.
	Worktrees []AgentsWorktree `json:"worktrees"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentsSyncOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["changed"]; raw != nil && !ok {
		return fmt.Errorf("field changed in AgentsSyncOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in AgentsSyncOutput: required")
	}
	if _, ok := raw["worktrees"]; raw != nil && !ok {
		return fmt.Errorf("field worktrees in AgentsSyncOutput: required")
	}
	type Plain AgentsSyncOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = AgentsSyncOutput(plain)
	return nil
}
