// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// What the layout of subagents inside a command did; present only when it changed
// a worktree, met a conflict or failed. The command itself is done either way.
type AgentsLayout struct {
	// Subagents not laid out: a file of their name is there already.
	Conflicts []AgentsConflict `json:"conflicts"`

	// Present if the layout failed, with what went wrong; gentry agents sync repeats
	// it.
	Error *string `json:"error,omitempty,omitzero"`

	// The worktrees the layout changed.
	Worktrees []AgentsWorktree `json:"worktrees"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentsLayout) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["conflicts"]; raw != nil && !ok {
		return fmt.Errorf("field conflicts in AgentsLayout: required")
	}
	if _, ok := raw["worktrees"]; raw != nil && !ok {
		return fmt.Errorf("field worktrees in AgentsLayout: required")
	}
	type Plain AgentsLayout
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AgentsLayout(plain)
	return nil
}
