// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// A subagent that cannot be laid out: a file of its name is in the worktree and
// Gentry did not lay it out.
type AgentsConflict struct {
	// Identifier of the subagent.
	Agent string `json:"agent"`

	// The file, relative to the worktree root with forward slashes.
	File string `json:"file"`

	// tracked: git of the project tracks the file; foreign: the file is not tracked
	// and Gentry did not lay it out. The list is open.
	Reason string `json:"reason"`

	// Absolute path of the worktree.
	Worktree string `json:"worktree"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentsConflict) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent"]; raw != nil && !ok {
		return fmt.Errorf("field agent in AgentsConflict: required")
	}
	if _, ok := raw["file"]; raw != nil && !ok {
		return fmt.Errorf("field file in AgentsConflict: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in AgentsConflict: required")
	}
	if _, ok := raw["worktree"]; raw != nil && !ok {
		return fmt.Errorf("field worktree in AgentsConflict: required")
	}
	type Plain AgentsConflict
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Agent)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "agent", 1)
	}
	if utf8.RuneCountInString(string(plain.File)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "file", 1)
	}
	if utf8.RuneCountInString(string(plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if utf8.RuneCountInString(string(plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = AgentsConflict(plain)
	return nil
}
