// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// The subagents of a worktree after a layout and what the layout changed there.
type AgentsWorktree struct {
	// Subagents whose files the layout wrote anew.
	Added []string `json:"added"`

	// Identifiers of the subagents laid out in the worktree.
	Agents []string `json:"agents"`

	// Present and true if the directory of the worktree does not exist: the worktree
	// is skipped.
	Missing *bool `json:"missing,omitempty,omitzero"`

	// Absolute path of the worktree.
	Path string `json:"path"`

	// Subagents no more in the flow whose files the layout removed.
	Removed []string `json:"removed"`

	// The task the worktree holds, such as SHOP-3; absent for a free worktree, whose
	// subagents are those of the active flow.
	Task *string `json:"task,omitempty,omitzero"`

	// Subagents whose files the layout rewrote.
	Updated []string `json:"updated"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentsWorktree) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["added"]; raw != nil && !ok {
		return fmt.Errorf("field added in AgentsWorktree: required")
	}
	if _, ok := raw["agents"]; raw != nil && !ok {
		return fmt.Errorf("field agents in AgentsWorktree: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in AgentsWorktree: required")
	}
	if _, ok := raw["removed"]; raw != nil && !ok {
		return fmt.Errorf("field removed in AgentsWorktree: required")
	}
	if _, ok := raw["updated"]; raw != nil && !ok {
		return fmt.Errorf("field updated in AgentsWorktree: required")
	}
	type Plain AgentsWorktree
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	*j = AgentsWorktree(plain)
	return nil
}
