// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "time"
import "unicode/utf8"

// The commit of the process repository that made the active variant of a kind of
// the process: the flow of a project or the library of subagents.
type Applied struct {
	// Hash of the commit.
	Commit string `json:"commit"`

	// Time of the commit in UTC, RFC 3339 with milliseconds: when the variant was
	// applied, on this machine or another one.
	Time time.Time `json:"time"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Applied) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["commit"]; raw != nil && !ok {
		return fmt.Errorf("field commit in Applied: required")
	}
	if _, ok := raw["time"]; raw != nil && !ok {
		return fmt.Errorf("field time in Applied: required")
	}
	type Plain Applied
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Commit)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "commit", 1)
	}
	*j = Applied(plain)
	return nil
}
