// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry artifact save --input`: file or url, not both. An unknown field
// is an error. The source is not part of the input: Gentry determines it by who
// calls the command.
type ArtifactSaveInput struct {
	// File to keep a copy of.
	File *string `json:"file,omitempty,omitzero"`

	// Name of the artifact: Latin letters, digits, dot, hyphen and underscore.
	Name string `json:"name"`

	// Address of the artifact, with http:// or https://.
	Url *string `json:"url,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactSaveInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ArtifactSaveInput: required")
	}
	type Plain ArtifactSaveInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.File != nil && utf8.RuneCountInString(string(*plain.File)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "file", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.Url != nil && utf8.RuneCountInString(string(*plain.Url)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "url", 1)
	}
	*j = ArtifactSaveInput(plain)
	return nil
}
