// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry artifact save --json`.
type ArtifactSaveOutput struct {
	// The artifact saved.
	Artifact TaskArtifact `json:"artifact"`

	// An artifact of the same name was replaced.
	Replaced bool `json:"replaced"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactSaveOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["artifact"]; raw != nil && !ok {
		return fmt.Errorf("field artifact in ArtifactSaveOutput: required")
	}
	if _, ok := raw["replaced"]; raw != nil && !ok {
		return fmt.Errorf("field replaced in ArtifactSaveOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in ArtifactSaveOutput: required")
	}
	type Plain ArtifactSaveOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = ArtifactSaveOutput(plain)
	return nil
}
