// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

type Error struct {
	// Stable machine code in English, such as unknown_command. The list is open: a
	// client shows an unknown code as a generic error with its message.
	Code string `json:"code"`

	// Parameters of the error, such as command and flag, for a client to build its
	// own text.
	Details ErrorOutputErrorDetails `json:"details,omitempty,omitzero"`

	// What to do for the action to succeed, in the operator's language.
	Hint *string `json:"hint,omitempty,omitzero"`

	// The reason, in the operator's language.
	Message string `json:"message"`
}

// Output of a failed `--json` command, on stdout; the exit code is not 0.
type ErrorOutput struct {
	// Error corresponds to the JSON schema field "error".
	Error Error `json:"error"`
}

// Parameters of the error, such as command and flag, for a client to build its own
// text.
type ErrorOutputErrorDetails map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in ErrorOutput: required")
	}
	type Plain ErrorOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ErrorOutput(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Error) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in Error: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in Error: required")
	}
	type Plain Error
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Code)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "code", 1)
	}
	if utf8.RuneCountInString(string(plain.Message)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "message", 1)
	}
	*j = Error(plain)
	return nil
}
