// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the stage.exited event: the task in the envelope closed its current
// stage by an exit and took a transition.
type StageExitedData struct {
	// Name of the artifact of an exit of kind artifact.
	Artifact *string `json:"artifact,omitempty,omitzero"`

	// The scenario of the task is passed.
	Finished bool `json:"finished"`

	// Kind of the exit: artifact — an artifact of the task, result — the result of an
	// event, negative — a negative result with where it was looked for.
	Kind StageExitedDataKind `json:"kind"`

	// Node of the pass closed.
	Node string `json:"node"`

	// Why the transition was taken; absent if not given.
	Reason *string `json:"reason,omitempty,omitzero"`

	// Which return by the transition this is, for a return.
	Returns *int `json:"returns,omitempty,omitzero"`

	// Round of the pass closed.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source StageExitedDataSource `json:"source"`

	// Stage of that node.
	Stage string `json:"stage"`

	// Text of the exit.
	Text string `json:"text"`

	// The node taken, or finish.
	To string `json:"to"`
}

type StageExitedDataKind string

const StageExitedDataKindArtifact StageExitedDataKind = "artifact"
const StageExitedDataKindNegative StageExitedDataKind = "negative"
const StageExitedDataKindResult StageExitedDataKind = "result"

var enumValues_StageExitedDataKind = []interface{}{
	"artifact",
	"result",
	"negative",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageExitedDataKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StageExitedDataKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StageExitedDataKind, v)
	}
	*j = StageExitedDataKind(v)
	return nil
}

type StageExitedDataSource string

const StageExitedDataSourceAgent StageExitedDataSource = "agent"
const StageExitedDataSourceOperator StageExitedDataSource = "operator"

var enumValues_StageExitedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageExitedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StageExitedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StageExitedDataSource, v)
	}
	*j = StageExitedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageExitedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["finished"]; raw != nil && !ok {
		return fmt.Errorf("field finished in StageExitedData: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in StageExitedData: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StageExitedData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StageExitedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in StageExitedData: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in StageExitedData: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in StageExitedData: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in StageExitedData: required")
	}
	type Plain StageExitedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Artifact != nil && utf8.RuneCountInString(string(*plain.Artifact)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "artifact", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if plain.Reason != nil && utf8.RuneCountInString(string(*plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if plain.Returns != nil && 1 > *plain.Returns {
		return fmt.Errorf("field %s: must be >= %v", "returns", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	if utf8.RuneCountInString(string(plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = StageExitedData(plain)
	return nil
}
