// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the process.remote_set event: the remote repository of the process is
// connected or its address replaced. The event has no project.
type ProcessRemoteSetData struct {
	// Address of the remote repository.
	Remote string `json:"remote"`

	// What the connection did, as result of ProcessRemoteOutput.
	Result ProcessRemoteSetDataResult `json:"result"`
}

type ProcessRemoteSetDataResult string

const ProcessRemoteSetDataResultMerged ProcessRemoteSetDataResult = "merged"
const ProcessRemoteSetDataResultReceived ProcessRemoteSetDataResult = "received"
const ProcessRemoteSetDataResultSent ProcessRemoteSetDataResult = "sent"
const ProcessRemoteSetDataResultUnchanged ProcessRemoteSetDataResult = "unchanged"

var enumValues_ProcessRemoteSetDataResult = []interface{}{
	"sent",
	"received",
	"merged",
	"unchanged",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessRemoteSetDataResult) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProcessRemoteSetDataResult {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProcessRemoteSetDataResult, v)
	}
	*j = ProcessRemoteSetDataResult(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessRemoteSetData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["remote"]; raw != nil && !ok {
		return fmt.Errorf("field remote in ProcessRemoteSetData: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ProcessRemoteSetData: required")
	}
	type Plain ProcessRemoteSetData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Remote)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "remote", 1)
	}
	*j = ProcessRemoteSetData(plain)
	return nil
}
