// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

// Data of the flow.draft_discarded event: the flow directory of the project in the
// event envelope is back to the active flow. The data is an empty object.
type FlowDraftDiscardedData map[string]interface{}
