// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the operator_decision.recorded event: a decision of the operator was
// recorded for the task in the envelope.
type OperatorDecisionRecordedData struct {
	// The node the decision allows one more return to from node; absent if it allows
	// none.
	AllowReturn *string `json:"allow_return,omitempty,omitzero"`

	// The words of the operator as given.
	Answer string `json:"answer"`

	// Node of the pass the decision was recorded at.
	Node string `json:"node"`

	// Number of the decision.
	Number int `json:"number"`

	// Options of the answer offered with the question; absent if none were.
	Options []QuestionOption `json:"options,omitempty,omitzero"`

	// The question the operator answered; absent for words given without one.
	Question *string `json:"question,omitempty,omitzero"`

	// Round of that pass.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source OperatorDecisionRecordedDataSource `json:"source"`
}

type OperatorDecisionRecordedDataSource string

const OperatorDecisionRecordedDataSourceAgent OperatorDecisionRecordedDataSource = "agent"
const OperatorDecisionRecordedDataSourceOperator OperatorDecisionRecordedDataSource = "operator"

var enumValues_OperatorDecisionRecordedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorDecisionRecordedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OperatorDecisionRecordedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OperatorDecisionRecordedDataSource, v)
	}
	*j = OperatorDecisionRecordedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorDecisionRecordedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["answer"]; raw != nil && !ok {
		return fmt.Errorf("field answer in OperatorDecisionRecordedData: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in OperatorDecisionRecordedData: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in OperatorDecisionRecordedData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in OperatorDecisionRecordedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in OperatorDecisionRecordedData: required")
	}
	type Plain OperatorDecisionRecordedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AllowReturn != nil && utf8.RuneCountInString(string(*plain.AllowReturn)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "allow_return", 1)
	}
	if utf8.RuneCountInString(string(plain.Answer)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "answer", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if plain.Options != nil && len(plain.Options) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "options", 2)
	}
	if plain.Question != nil && utf8.RuneCountInString(string(*plain.Question)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "question", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	*j = OperatorDecisionRecordedData(plain)
	return nil
}
