// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the artifact.saved event: an artifact of the task in the envelope was
// saved.
type ArtifactSavedData struct {
	// Kind of the artifact: file or link.
	Kind ArtifactSavedDataKind `json:"kind"`

	// Name of the artifact.
	Name string `json:"name"`

	// An artifact of the same name was replaced.
	Replaced bool `json:"replaced"`

	// Who did it: operator or agent.
	Source ArtifactSavedDataSource `json:"source"`

	// Address of a link.
	Url *string `json:"url,omitempty,omitzero"`
}

type ArtifactSavedDataKind string

const ArtifactSavedDataKindFile ArtifactSavedDataKind = "file"
const ArtifactSavedDataKindLink ArtifactSavedDataKind = "link"

var enumValues_ArtifactSavedDataKind = []interface{}{
	"file",
	"link",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactSavedDataKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ArtifactSavedDataKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ArtifactSavedDataKind, v)
	}
	*j = ArtifactSavedDataKind(v)
	return nil
}

type ArtifactSavedDataSource string

const ArtifactSavedDataSourceAgent ArtifactSavedDataSource = "agent"
const ArtifactSavedDataSourceOperator ArtifactSavedDataSource = "operator"

var enumValues_ArtifactSavedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactSavedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ArtifactSavedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ArtifactSavedDataSource, v)
	}
	*j = ArtifactSavedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactSavedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in ArtifactSavedData: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ArtifactSavedData: required")
	}
	if _, ok := raw["replaced"]; raw != nil && !ok {
		return fmt.Errorf("field replaced in ArtifactSavedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in ArtifactSavedData: required")
	}
	type Plain ArtifactSavedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.Url != nil && utf8.RuneCountInString(string(*plain.Url)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "url", 1)
	}
	*j = ArtifactSavedData(plain)
	return nil
}
