// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Data of the project.added event: a project was connected on this machine. The
// project is in the event envelope.
type ProjectAddedData struct {
	// Absolute path of the project knowledge repository.
	Knowledge string `json:"knowledge"`

	// Whether the project knowledge was created by this connection.
	KnowledgeCreated bool `json:"knowledge_created"`

	// Prefix of task numbers.
	Prefix string `json:"prefix"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProjectAddedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["knowledge"]; raw != nil && !ok {
		return fmt.Errorf("field knowledge in ProjectAddedData: required")
	}
	if _, ok := raw["knowledge_created"]; raw != nil && !ok {
		return fmt.Errorf("field knowledge_created in ProjectAddedData: required")
	}
	if _, ok := raw["prefix"]; raw != nil && !ok {
		return fmt.Errorf("field prefix in ProjectAddedData: required")
	}
	type Plain ProjectAddedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Knowledge)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "knowledge", 1)
	}
	if utf8.RuneCountInString(string(plain.Prefix)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "prefix", 1)
	}
	*j = ProjectAddedData(plain)
	return nil
}
