// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the stage.skipped event: the task in the envelope skipped its current
// stage and took a transition.
type StageSkippedData struct {
	// The scenario of the task is passed.
	Finished bool `json:"finished"`

	// Node of the pass skipped.
	Node string `json:"node"`

	// Why the stage was skipped.
	Reason string `json:"reason"`

	// Which return by the transition this is, for a return.
	Returns *int `json:"returns,omitempty,omitzero"`

	// Round of the pass skipped.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source StageSkippedDataSource `json:"source"`

	// Stage of that node.
	Stage string `json:"stage"`

	// The node taken, or finish.
	To string `json:"to"`
}

type StageSkippedDataSource string

const StageSkippedDataSourceAgent StageSkippedDataSource = "agent"
const StageSkippedDataSourceOperator StageSkippedDataSource = "operator"

var enumValues_StageSkippedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageSkippedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StageSkippedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StageSkippedDataSource, v)
	}
	*j = StageSkippedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageSkippedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["finished"]; raw != nil && !ok {
		return fmt.Errorf("field finished in StageSkippedData: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StageSkippedData: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in StageSkippedData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StageSkippedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in StageSkippedData: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in StageSkippedData: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in StageSkippedData: required")
	}
	type Plain StageSkippedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if utf8.RuneCountInString(string(plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if plain.Returns != nil && 1 > *plain.Returns {
		return fmt.Errorf("field %s: must be >= %v", "returns", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	if utf8.RuneCountInString(string(plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = StageSkippedData(plain)
	return nil
}
