// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the task.cancelled event: the task in the event envelope was cancelled
// and released its worktree.
type TaskCancelledData struct {
	// Attempt of the task.
	Attempt int `json:"attempt"`

	// Node the task was cancelled at; finish if its scenario was passed.
	Node string `json:"node"`

	// Why the task was cancelled; absent if not given.
	Reason *string `json:"reason,omitempty,omitzero"`

	// Who did it: operator or agent.
	Source TaskCancelledDataSource `json:"source"`

	// Absolute path of the worktree the task released.
	Worktree string `json:"worktree"`
}

type TaskCancelledDataSource string

const TaskCancelledDataSourceAgent TaskCancelledDataSource = "agent"
const TaskCancelledDataSourceOperator TaskCancelledDataSource = "operator"

var enumValues_TaskCancelledDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCancelledDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskCancelledDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskCancelledDataSource, v)
	}
	*j = TaskCancelledDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCancelledData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["attempt"]; raw != nil && !ok {
		return fmt.Errorf("field attempt in TaskCancelledData: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in TaskCancelledData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskCancelledData: required")
	}
	if _, ok := raw["worktree"]; raw != nil && !ok {
		return fmt.Errorf("field worktree in TaskCancelledData: required")
	}
	type Plain TaskCancelledData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Attempt {
		return fmt.Errorf("field %s: must be >= %v", "attempt", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if plain.Reason != nil && utf8.RuneCountInString(string(*plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if utf8.RuneCountInString(string(plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskCancelledData(plain)
	return nil
}
