// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Data of the worktree.added event: a worktree was added to the pool of the
// project in the event envelope.
type WorktreeAddedData struct {
	// Whether this is the main worktree of the project.
	Main bool `json:"main"`

	// Absolute path of the worktree root.
	Path string `json:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorktreeAddedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["main"]; raw != nil && !ok {
		return fmt.Errorf("field main in WorktreeAddedData: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in WorktreeAddedData: required")
	}
	type Plain WorktreeAddedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	*j = WorktreeAddedData(plain)
	return nil
}
