// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Data of the flow.draft_created event: a flow draft was created for the project
// in the event envelope. Continuing an open draft gives no event.
type FlowDraftCreatedData struct {
	// Number of the version the draft was made from; absent if the project had no
	// flow.
	BaseVersion *int `json:"base_version,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDraftCreatedData) UnmarshalJSON(value []byte) error {
	type Plain FlowDraftCreatedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.BaseVersion != nil && 1 > *plain.BaseVersion {
		return fmt.Errorf("field %s: must be >= %v", "base_version", 1)
	}
	*j = FlowDraftCreatedData(plain)
	return nil
}
