// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Data of the process.synced event: a synchronization of the process received,
// sent or restored something, or met a conflict; a change made on another machine
// is known by it. The event has no project.
type ProcessSyncedData struct {
	// Kinds changed on both machines that could not be brought together.
	Conflicts []ProcessItem `json:"conflicts"`

	// Kinds changed on another machine and taken.
	Received []ProcessItem `json:"received"`

	// Kinds changed around Gentry with problems, restored to the last checked
	// variant.
	Restored []ProcessItem `json:"restored"`

	// Kinds changed on this machine and sent.
	Sent []ProcessItem `json:"sent"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessSyncedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["conflicts"]; raw != nil && !ok {
		return fmt.Errorf("field conflicts in ProcessSyncedData: required")
	}
	if _, ok := raw["received"]; raw != nil && !ok {
		return fmt.Errorf("field received in ProcessSyncedData: required")
	}
	if _, ok := raw["restored"]; raw != nil && !ok {
		return fmt.Errorf("field restored in ProcessSyncedData: required")
	}
	if _, ok := raw["sent"]; raw != nil && !ok {
		return fmt.Errorf("field sent in ProcessSyncedData: required")
	}
	type Plain ProcessSyncedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProcessSyncedData(plain)
	return nil
}
