// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the step.dropped event: a step of the current stage of the task in the
// envelope was dropped.
type StepDroppedData struct {
	// Node of the current pass.
	Node string `json:"node"`

	// Number of the step.
	Number int `json:"number"`

	// Why the step was dropped.
	Reason string `json:"reason"`

	// Round of the current pass.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source StepDroppedDataSource `json:"source"`
}

type StepDroppedDataSource string

const StepDroppedDataSourceAgent StepDroppedDataSource = "agent"
const StepDroppedDataSourceOperator StepDroppedDataSource = "operator"

var enumValues_StepDroppedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepDroppedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StepDroppedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StepDroppedDataSource, v)
	}
	*j = StepDroppedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepDroppedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StepDroppedData: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in StepDroppedData: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in StepDroppedData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StepDroppedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in StepDroppedData: required")
	}
	type Plain StepDroppedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if utf8.RuneCountInString(string(plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	*j = StepDroppedData(plain)
	return nil
}
