// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the step.added event: steps were added to the current stage of the task
// in the envelope.
type StepAddedData struct {
	// Node of the current pass.
	Node string `json:"node"`

	// Round of the current pass.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source StepAddedDataSource `json:"source"`

	// Steps added, in order.
	Steps []StepAddedStep `json:"steps"`
}

type StepAddedDataSource string

const StepAddedDataSourceAgent StepAddedDataSource = "agent"
const StepAddedDataSourceOperator StepAddedDataSource = "operator"

var enumValues_StepAddedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepAddedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StepAddedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StepAddedDataSource, v)
	}
	*j = StepAddedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepAddedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StepAddedData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StepAddedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in StepAddedData: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in StepAddedData: required")
	}
	type Plain StepAddedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	*j = StepAddedData(plain)
	return nil
}

type StepAddedStep struct {
	// Number of the step.
	Number int `json:"number"`

	// The step.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepAddedStep) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in StepAddedStep: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in StepAddedStep: required")
	}
	type Plain StepAddedStep
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = StepAddedStep(plain)
	return nil
}
