// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Data of the flow.applied event: the flow draft of the project in the event
// envelope was applied as a new version and deleted.
type FlowAppliedData struct {
	// Number of the new flow version.
	Version int `json:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowAppliedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in FlowAppliedData: required")
	}
	type Plain FlowAppliedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Version {
		return fmt.Errorf("field %s: must be >= %v", "version", 1)
	}
	*j = FlowAppliedData(plain)
	return nil
}
