// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

// Data of the library.draft_discarded event: the library directory is back to the
// active library. The event has no project; the data is an empty object.
type LibraryDraftDiscardedData map[string]interface{}
