// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

// Data of the flow.draft_discarded event: the flow draft of the project in the
// event envelope was deleted; the active flow is unchanged. The data is an empty
// object.
type FlowDraftDiscardedData map[string]interface{}
