// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Data of the library.applied event: the draft of the library of subagents became
// active on this machine. The event has no project.
type LibraryAppliedData struct {
	// Hash of the commit of the process repository that applied the library.
	Commit string `json:"commit"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryAppliedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["commit"]; raw != nil && !ok {
		return fmt.Errorf("field commit in LibraryAppliedData: required")
	}
	type Plain LibraryAppliedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Commit)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "commit", 1)
	}
	*j = LibraryAppliedData(plain)
	return nil
}
