// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the task.closed event: the task in the event envelope passed its
// scenario, was closed and released its worktree.
type TaskClosedData struct {
	// Attempt of the task.
	Attempt int `json:"attempt"`

	// Who did it: operator or agent.
	Source TaskClosedDataSource `json:"source"`

	// Absolute path of the worktree the task released.
	Worktree string `json:"worktree"`
}

type TaskClosedDataSource string

const TaskClosedDataSourceAgent TaskClosedDataSource = "agent"
const TaskClosedDataSourceOperator TaskClosedDataSource = "operator"

var enumValues_TaskClosedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskClosedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskClosedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskClosedDataSource, v)
	}
	*j = TaskClosedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskClosedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["attempt"]; raw != nil && !ok {
		return fmt.Errorf("field attempt in TaskClosedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskClosedData: required")
	}
	if _, ok := raw["worktree"]; raw != nil && !ok {
		return fmt.Errorf("field worktree in TaskClosedData: required")
	}
	type Plain TaskClosedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Attempt {
		return fmt.Errorf("field %s: must be >= %v", "attempt", 1)
	}
	if utf8.RuneCountInString(string(plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskClosedData(plain)
	return nil
}
