// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "regexp"
import "time"
import "unicode/utf8"

// An event of the journal, one JSON line per event in the output of `gentry events
// --json`.
type Event struct {
	// Details of the event; each type defines its own schema.
	Data EventData `json:"data"`

	// Project the event belongs to; absent for events without a project, such as a
	// change of a setting for all projects.
	Project *string `json:"project,omitempty,omitzero"`

	// Event number: grows on the machine without gaps in the order of writing. A
	// client resumes reading after the last number it has processed.
	Seq int `json:"seq"`

	// Task the event belongs to; absent for events without a task.
	Task *string `json:"task,omitempty,omitzero"`

	// Time in UTC, RFC 3339 with milliseconds.
	Time time.Time `json:"time"`

	// Event type as object.action in the past tense, such as task.taken.
	Type string `json:"type"`
}

// Details of the event; each type defines its own schema.
type EventData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Event) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in Event: required")
	}
	if _, ok := raw["seq"]; raw != nil && !ok {
		return fmt.Errorf("field seq in Event: required")
	}
	if _, ok := raw["time"]; raw != nil && !ok {
		return fmt.Errorf("field time in Event: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Event: required")
	}
	type Plain Event
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Project != nil && utf8.RuneCountInString(string(*plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if 1 > plain.Seq {
		return fmt.Errorf("field %s: must be >= %v", "seq", 1)
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z_]*[.][a-z][a-z_]*$`, string(plain.Type)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Type", `^[a-z][a-z_]*[.][a-z][a-z_]*$`)
	}
	*j = Event(plain)
	return nil
}
