// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the task.taken event: the task in the event envelope was taken in a
// worktree of the project in the envelope.
type TaskTakenData struct {
	// Hash of the commit that applied the flow of the task.
	FlowCommit string `json:"flow_commit"`

	// Start node of the scenario: the task is at it.
	Node string `json:"node"`

	// Identifier of the scenario.
	Scenario string `json:"scenario"`

	// Who passed the title and the statement: operator or agent.
	Source TaskTakenDataSource `json:"source"`

	// Title of the task.
	Title string `json:"title"`

	// Absolute path of the worktree the task holds.
	Worktree string `json:"worktree"`
}

type TaskTakenDataSource string

const TaskTakenDataSourceAgent TaskTakenDataSource = "agent"
const TaskTakenDataSourceOperator TaskTakenDataSource = "operator"

var enumValues_TaskTakenDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskTakenDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskTakenDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskTakenDataSource, v)
	}
	*j = TaskTakenDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskTakenData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["flow_commit"]; raw != nil && !ok {
		return fmt.Errorf("field flow_commit in TaskTakenData: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in TaskTakenData: required")
	}
	if _, ok := raw["scenario"]; raw != nil && !ok {
		return fmt.Errorf("field scenario in TaskTakenData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskTakenData: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskTakenData: required")
	}
	if _, ok := raw["worktree"]; raw != nil && !ok {
		return fmt.Errorf("field worktree in TaskTakenData: required")
	}
	type Plain TaskTakenData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.FlowCommit)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "flow_commit", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if utf8.RuneCountInString(string(plain.Scenario)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "scenario", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if utf8.RuneCountInString(string(plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskTakenData(plain)
	return nil
}
