// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the step.done event: a step of the current stage of the task in the
// envelope was marked done.
type StepDoneData struct {
	// How the result was checked; absent if not given.
	Check *string `json:"check,omitempty,omitzero"`

	// Node of the current pass.
	Node string `json:"node"`

	// Number of the step.
	Number int `json:"number"`

	// Round of the current pass.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source StepDoneDataSource `json:"source"`
}

type StepDoneDataSource string

const StepDoneDataSourceAgent StepDoneDataSource = "agent"
const StepDoneDataSourceOperator StepDoneDataSource = "operator"

var enumValues_StepDoneDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepDoneDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StepDoneDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StepDoneDataSource, v)
	}
	*j = StepDoneDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepDoneData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StepDoneData: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in StepDoneData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StepDoneData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in StepDoneData: required")
	}
	type Plain StepDoneData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Check != nil && utf8.RuneCountInString(string(*plain.Check)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "check", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	*j = StepDoneData(plain)
	return nil
}
