// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Data of the note.added event: a note was added to the task in the envelope.
type NoteAddedData struct {
	// Node of the pass the note was added at.
	Node string `json:"node"`

	// Number of the note.
	Number int `json:"number"`

	// Round of that pass.
	Round int `json:"round"`

	// Who did it: operator or agent.
	Source NoteAddedDataSource `json:"source"`

	// Text of the note.
	Text string `json:"text"`
}

type NoteAddedDataSource string

const NoteAddedDataSourceAgent NoteAddedDataSource = "agent"
const NoteAddedDataSourceOperator NoteAddedDataSource = "operator"

var enumValues_NoteAddedDataSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoteAddedDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NoteAddedDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NoteAddedDataSource, v)
	}
	*j = NoteAddedDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoteAddedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in NoteAddedData: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in NoteAddedData: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in NoteAddedData: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in NoteAddedData: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in NoteAddedData: required")
	}
	type Plain NoteAddedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	*j = NoteAddedData(plain)
	return nil
}
