// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

type FlowNode struct {
	// Identifier of the node, unique within the scenario. One stage may stand in
	// several nodes.
	Id string `json:"id"`

	// Transitions from the node, always a list, even when the scenario file has one
	// node identifier. At most one is without a condition: the default path.
	Next []FlowTransition `json:"next"`

	// Identifier of the stage of the node.
	Stage string `json:"stage"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowNode) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowNode: required")
	}
	if _, ok := raw["next"]; raw != nil && !ok {
		return fmt.Errorf("field next in FlowNode: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in FlowNode: required")
	}
	type Plain FlowNode
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	*j = FlowNode(plain)
	return nil
}

type FlowScenario struct {
	// Identifier of the scenario, the name of its file.
	Id string `json:"id"`

	// Nodes of the scenario graph in the order of the scenario file.
	Nodes []FlowNode `json:"nodes"`

	// Identifier of the start node.
	Start string `json:"start"`

	// Name of the scenario shown to the operator.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowScenario) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowScenario: required")
	}
	if _, ok := raw["nodes"]; raw != nil && !ok {
		return fmt.Errorf("field nodes in FlowScenario: required")
	}
	if _, ok := raw["start"]; raw != nil && !ok {
		return fmt.Errorf("field start in FlowScenario: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in FlowScenario: required")
	}
	type Plain FlowScenario
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Start)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "start", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = FlowScenario(plain)
	return nil
}

// Output of `gentry flow show --json`: the flow of the project. With a scenario
// named, scenarios has only it, stages only its stages and parts only the parts
// they include.
type FlowShowOutput struct {
	// Absolute path of the flow directory.
	Dir string `json:"dir"`

	// Identifiers of the parts by identifier.
	Parts []string `json:"parts"`

	// Identifier of the project.
	Project string `json:"project"`

	// Scenarios by identifier.
	Scenarios []FlowScenario `json:"scenarios"`

	// Stages by identifier.
	Stages []FlowStage `json:"stages"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowShowOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in FlowShowOutput: required")
	}
	if _, ok := raw["parts"]; raw != nil && !ok {
		return fmt.Errorf("field parts in FlowShowOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowShowOutput: required")
	}
	if _, ok := raw["scenarios"]; raw != nil && !ok {
		return fmt.Errorf("field scenarios in FlowShowOutput: required")
	}
	if _, ok := raw["stages"]; raw != nil && !ok {
		return fmt.Errorf("field stages in FlowShowOutput: required")
	}
	type Plain FlowShowOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = FlowShowOutput(plain)
	return nil
}

type FlowStage struct {
	// Who carries out the stage: orchestrator for the main agent session, operator
	// for the operator, otherwise the identifier of a subagent of the project or a
	// shared one.
	Executor string `json:"executor"`

	// Exit of the stage: what must be true to close it.
	Exit string `json:"exit"`

	// Identifier of the stage, the name of its files.
	Id string `json:"id"`

	// Identifiers of the parts included in the instruction of the stage, in the order
	// of the stage file; empty if none.
	Include []string `json:"include"`

	// Name of the stage shown to the operator.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowStage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["executor"]; raw != nil && !ok {
		return fmt.Errorf("field executor in FlowStage: required")
	}
	if _, ok := raw["exit"]; raw != nil && !ok {
		return fmt.Errorf("field exit in FlowStage: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowStage: required")
	}
	if _, ok := raw["include"]; raw != nil && !ok {
		return fmt.Errorf("field include in FlowStage: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in FlowStage: required")
	}
	type Plain FlowStage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Executor)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "executor", 1)
	}
	if utf8.RuneCountInString(string(plain.Exit)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "exit", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = FlowStage(plain)
	return nil
}

type FlowTransition struct {
	// Condition of the transition as text, evaluated by the agent; absent for the
	// transition of the default path.
	If *string `json:"if,omitempty,omitzero"`

	// Limit of rounds of the loop the transition closes; absent when the transition
	// closes no loop.
	MaxRounds *int `json:"max_rounds,omitempty,omitzero"`

	// Identifier of the target node, or finish for the end of the scenario.
	To string `json:"to"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowTransition) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in FlowTransition: required")
	}
	type Plain FlowTransition
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.If != nil && utf8.RuneCountInString(string(*plain.If)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "if", 1)
	}
	if plain.MaxRounds != nil && 1 > *plain.MaxRounds {
		return fmt.Errorf("field %s: must be >= %v", "max_rounds", 1)
	}
	if utf8.RuneCountInString(string(plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = FlowTransition(plain)
	return nil
}
