// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type FlowAgent struct {
	// What the subagent may do, in the order of its file.
	Capabilities []FlowShowOutputAgentsElemCapabilitiesElem `json:"capabilities"`

	// Identifier of the subagent, the name of its files.
	Id string `json:"id"`

	// Instruction of the subagent in markdown, as written.
	Instruction string `json:"instruction"`

	// What the subagent is for.
	Purpose string `json:"purpose"`

	// Where the subagent comes from: project for a subagent of the flow, library for
	// a copy of a subagent of the library taken into the version.
	Source FlowShowOutputAgentsElemSource `json:"source"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowAgent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["capabilities"]; raw != nil && !ok {
		return fmt.Errorf("field capabilities in FlowAgent: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowAgent: required")
	}
	if _, ok := raw["instruction"]; raw != nil && !ok {
		return fmt.Errorf("field instruction in FlowAgent: required")
	}
	if _, ok := raw["purpose"]; raw != nil && !ok {
		return fmt.Errorf("field purpose in FlowAgent: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in FlowAgent: required")
	}
	type Plain FlowAgent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Purpose)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "purpose", 1)
	}
	*j = FlowAgent(plain)
	return nil
}

// The open draft of the flow; absent if there is none.
type FlowDraftInfo struct {
	// Number of the version the draft was made from; absent if the project had no
	// flow.
	BaseVersion *int `json:"base_version,omitempty,omitzero"`

	// Absolute path of the draft directory.
	Dir string `json:"dir"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDraftInfo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in FlowDraftInfo: required")
	}
	type Plain FlowDraftInfo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.BaseVersion != nil && 1 > *plain.BaseVersion {
		return fmt.Errorf("field %s: must be >= %v", "base_version", 1)
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	*j = FlowDraftInfo(plain)
	return nil
}

type FlowNode struct {
	// Identifier of the node, unique within the scenario. One stage may stand in
	// several nodes.
	Id string `json:"id"`

	// Transitions from the node, always a list, even when the scenario file has one
	// node identifier. At most one is without a condition: the default path.
	Next []FlowTransition `json:"next"`

	// Identifier of the stage of the node.
	Stage string `json:"stage"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowNode) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowNode: required")
	}
	if _, ok := raw["next"]; raw != nil && !ok {
		return fmt.Errorf("field next in FlowNode: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in FlowNode: required")
	}
	type Plain FlowNode
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	*j = FlowNode(plain)
	return nil
}

type FlowPart struct {
	// Identifier of the part, the name of its file.
	Id string `json:"id"`

	// Text of the part in markdown, as written.
	Text string `json:"text"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowPart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowPart: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in FlowPart: required")
	}
	type Plain FlowPart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = FlowPart(plain)
	return nil
}

type FlowScenario struct {
	// Identifier of the scenario, the name of its file.
	Id string `json:"id"`

	// Nodes of the scenario graph in the order of the scenario file.
	Nodes []FlowNode `json:"nodes"`

	// Identifier of the start node.
	Start string `json:"start"`

	// Name of the scenario shown to the operator.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowScenario) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowScenario: required")
	}
	if _, ok := raw["nodes"]; raw != nil && !ok {
		return fmt.Errorf("field nodes in FlowScenario: required")
	}
	if _, ok := raw["start"]; raw != nil && !ok {
		return fmt.Errorf("field start in FlowScenario: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in FlowScenario: required")
	}
	type Plain FlowScenario
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Start)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "start", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = FlowScenario(plain)
	return nil
}

// Output of `gentry flow show --json`: the active flow of the project with its
// texts, or with --draft the draft. With an object flag the arrays narrow to the
// object and what it refers to: for a scenario its stages, their parts and
// subagents; for a stage its parts and subagent; for a part or a subagent the
// object alone.
type FlowShowOutput struct {
	// Subagents by identifier: those of the project and those of the library the
	// stages name. A project subagent replaces a library one of the same identifier.
	Agents []FlowAgent `json:"agents"`

	// The open draft of the flow; absent if there is none.
	Draft *FlowDraftInfo `json:"draft,omitempty,omitzero"`

	// Parts by identifier.
	Parts []FlowPart `json:"parts"`

	// Identifier of the project.
	Project string `json:"project"`

	// Scenarios by identifier.
	Scenarios []FlowScenario `json:"scenarios"`

	// Stages by identifier.
	Stages []FlowStage `json:"stages"`

	// Number of the active flow version; absent if the project has no flow yet, which
	// only the draft can show.
	Version *int `json:"version,omitempty,omitzero"`
}

type FlowShowOutputAgentsElemCapabilitiesElem string

const FlowShowOutputAgentsElemCapabilitiesElemEdit FlowShowOutputAgentsElemCapabilitiesElem = "edit"
const FlowShowOutputAgentsElemCapabilitiesElemRead FlowShowOutputAgentsElemCapabilitiesElem = "read"
const FlowShowOutputAgentsElemCapabilitiesElemRun FlowShowOutputAgentsElemCapabilitiesElem = "run"
const FlowShowOutputAgentsElemCapabilitiesElemSearch FlowShowOutputAgentsElemCapabilitiesElem = "search"
const FlowShowOutputAgentsElemCapabilitiesElemWeb FlowShowOutputAgentsElemCapabilitiesElem = "web"

var enumValues_FlowShowOutputAgentsElemCapabilitiesElem = []interface{}{
	"read",
	"search",
	"edit",
	"run",
	"web",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowShowOutputAgentsElemCapabilitiesElem) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowShowOutputAgentsElemCapabilitiesElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowShowOutputAgentsElemCapabilitiesElem, v)
	}
	*j = FlowShowOutputAgentsElemCapabilitiesElem(v)
	return nil
}

type FlowShowOutputAgentsElemSource string

const FlowShowOutputAgentsElemSourceLibrary FlowShowOutputAgentsElemSource = "library"
const FlowShowOutputAgentsElemSourceProject FlowShowOutputAgentsElemSource = "project"

var enumValues_FlowShowOutputAgentsElemSource = []interface{}{
	"project",
	"library",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowShowOutputAgentsElemSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowShowOutputAgentsElemSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowShowOutputAgentsElemSource, v)
	}
	*j = FlowShowOutputAgentsElemSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowShowOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agents"]; raw != nil && !ok {
		return fmt.Errorf("field agents in FlowShowOutput: required")
	}
	if _, ok := raw["parts"]; raw != nil && !ok {
		return fmt.Errorf("field parts in FlowShowOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowShowOutput: required")
	}
	if _, ok := raw["scenarios"]; raw != nil && !ok {
		return fmt.Errorf("field scenarios in FlowShowOutput: required")
	}
	if _, ok := raw["stages"]; raw != nil && !ok {
		return fmt.Errorf("field stages in FlowShowOutput: required")
	}
	type Plain FlowShowOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if plain.Version != nil && 1 > *plain.Version {
		return fmt.Errorf("field %s: must be >= %v", "version", 1)
	}
	*j = FlowShowOutput(plain)
	return nil
}

type FlowStage struct {
	// Who carries out the stage: orchestrator for the main agent session, operator
	// for the operator, otherwise the identifier of a subagent of the project or of
	// the library.
	Executor string `json:"executor"`

	// Exit of the stage: what must be true to close it.
	Exit string `json:"exit"`

	// Identifier of the stage, the name of its files.
	Id string `json:"id"`

	// Identifiers of the parts included in the instruction of the stage, in the order
	// of the stage file; empty if none.
	Include []string `json:"include"`

	// Instruction of the stage in markdown, as written.
	Instruction string `json:"instruction"`

	// Name of the stage shown to the operator.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowStage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["executor"]; raw != nil && !ok {
		return fmt.Errorf("field executor in FlowStage: required")
	}
	if _, ok := raw["exit"]; raw != nil && !ok {
		return fmt.Errorf("field exit in FlowStage: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in FlowStage: required")
	}
	if _, ok := raw["include"]; raw != nil && !ok {
		return fmt.Errorf("field include in FlowStage: required")
	}
	if _, ok := raw["instruction"]; raw != nil && !ok {
		return fmt.Errorf("field instruction in FlowStage: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in FlowStage: required")
	}
	type Plain FlowStage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Executor)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "executor", 1)
	}
	if utf8.RuneCountInString(string(plain.Exit)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "exit", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = FlowStage(plain)
	return nil
}

type FlowTransition struct {
	// Condition of the transition as text, evaluated by the agent; absent for the
	// transition of the default path.
	If *string `json:"if,omitempty,omitzero"`

	// Limit of rounds of the loop the transition closes; absent when the transition
	// closes no loop.
	MaxRounds *int `json:"max_rounds,omitempty,omitzero"`

	// Identifier of the target node, or finish for the end of the scenario.
	To string `json:"to"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowTransition) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in FlowTransition: required")
	}
	type Plain FlowTransition
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.If != nil && utf8.RuneCountInString(string(*plain.If)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "if", 1)
	}
	if plain.MaxRounds != nil && 1 > *plain.MaxRounds {
		return fmt.Errorf("field %s: must be >= %v", "max_rounds", 1)
	}
	if utf8.RuneCountInString(string(plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = FlowTransition(plain)
	return nil
}
