// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry flow discard --json`: the draft is deleted; the active flow is
// unchanged.
type FlowDiscardOutput struct {
	// Absolute path of the deleted draft directory.
	Dir string `json:"dir"`

	// Identifier of the project.
	Project string `json:"project"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiscardOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in FlowDiscardOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowDiscardOutput: required")
	}
	type Plain FlowDiscardOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = FlowDiscardOutput(plain)
	return nil
}
