// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry flow apply --json`: the draft became the new version of the
// flow and is deleted.
type FlowApplyOutput struct {
	// Identifier of the project.
	Project string `json:"project"`

	// Number of the new flow version, now the active one.
	Version int `json:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowApplyOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowApplyOutput: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in FlowApplyOutput: required")
	}
	type Plain FlowApplyOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if 1 > plain.Version {
		return fmt.Errorf("field %s: must be >= %v", "version", 1)
	}
	*j = FlowApplyOutput(plain)
	return nil
}
