// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// A problem of a flow, in the details of the errors flow_invalid and
// flow_draft_invalid.
type FlowProblem struct {
	// Kind of the problem, such as unknown_stage. The list is open: a client shows an
	// unknown kind by its message.
	Code string `json:"code"`

	// Path of the file inside the flow, with forward slashes, such as
	// scenarios/bug.yaml; absent when the problem is of the whole flow or of a
	// subagent of the library.
	File *string `json:"file,omitempty,omitzero"`

	// Line of the file, from 1; absent when unknown.
	Line *int `json:"line,omitempty,omitzero"`

	// The problem, in the operator's language. It names the object, such as a
	// scenario, a node, a stage or a subagent, and not the file.
	Message string `json:"message"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowProblem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in FlowProblem: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in FlowProblem: required")
	}
	type Plain FlowProblem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Code)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "code", 1)
	}
	if plain.File != nil && utf8.RuneCountInString(string(*plain.File)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "file", 1)
	}
	if plain.Line != nil && 1 > *plain.Line {
		return fmt.Errorf("field %s: must be >= %v", "line", 1)
	}
	if utf8.RuneCountInString(string(plain.Message)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "message", 1)
	}
	*j = FlowProblem(plain)
	return nil
}
