// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry flow apply --json`: the draft became the active flow with a
// commit of the process repository.
type FlowApplyOutput struct {
	// What the layout of subagents in the free worktrees of the project did; present
	// only when there is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// The commit that applied the flow.
	Applied Applied `json:"applied"`

	// Identifier of the project.
	Project string `json:"project"`

	// Whether the commit is sent to the remote repository; false without one or when
	// it did not answer, and then it is sent by a later command.
	Sent bool `json:"sent"`

	// What the synchronization of the command did; present only when there is
	// something to tell.
	Sync *Sync `json:"sync,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowApplyOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["applied"]; raw != nil && !ok {
		return fmt.Errorf("field applied in FlowApplyOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowApplyOutput: required")
	}
	if _, ok := raw["sent"]; raw != nil && !ok {
		return fmt.Errorf("field sent in FlowApplyOutput: required")
	}
	type Plain FlowApplyOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = FlowApplyOutput(plain)
	return nil
}
