// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type FlowChange struct {
	// What happened to the object.
	Change FlowDiffOutputChangesElemChange `json:"change"`

	// Identifier of the object; absent for the common rules.
	Id *string `json:"id,omitempty,omitzero"`

	// Kind of the object: common for the common rules of the flow, scenario, stage,
	// part or agent for a subagent of the project.
	Object FlowDiffOutputChangesElemObject `json:"object"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowChange) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["change"]; raw != nil && !ok {
		return fmt.Errorf("field change in FlowChange: required")
	}
	if _, ok := raw["object"]; raw != nil && !ok {
		return fmt.Errorf("field object in FlowChange: required")
	}
	type Plain FlowChange
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Id != nil && utf8.RuneCountInString(string(*plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = FlowChange(plain)
	return nil
}

// Output of `gentry flow diff --json`: the objects of the draft that differ from
// the active flow.
type FlowDiffOutput struct {
	// The commit that applied the active flow the draft is compared with; absent if
	// the project has no flow, and then every object of the draft is added.
	Applied *Applied `json:"applied,omitempty,omitzero"`

	// Changed objects: the common rules first, then scenarios, stages, parts and
	// subagents of the project, each kind by identifier. Not empty: without changes
	// there is no draft.
	Changes []FlowChange `json:"changes"`

	// Identifier of the project.
	Project string `json:"project"`

	// What the synchronization before the command did; present only when there is
	// something to tell.
	Sync *Sync `json:"sync,omitempty,omitzero"`
}

type FlowDiffOutputChangesElemChange string

const FlowDiffOutputChangesElemChangeAdded FlowDiffOutputChangesElemChange = "added"
const FlowDiffOutputChangesElemChangeModified FlowDiffOutputChangesElemChange = "modified"
const FlowDiffOutputChangesElemChangeRemoved FlowDiffOutputChangesElemChange = "removed"

var enumValues_FlowDiffOutputChangesElemChange = []interface{}{
	"added",
	"modified",
	"removed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutputChangesElemChange) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowDiffOutputChangesElemChange {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowDiffOutputChangesElemChange, v)
	}
	*j = FlowDiffOutputChangesElemChange(v)
	return nil
}

type FlowDiffOutputChangesElemObject string

const FlowDiffOutputChangesElemObjectAgent FlowDiffOutputChangesElemObject = "agent"
const FlowDiffOutputChangesElemObjectCommon FlowDiffOutputChangesElemObject = "common"
const FlowDiffOutputChangesElemObjectPart FlowDiffOutputChangesElemObject = "part"
const FlowDiffOutputChangesElemObjectScenario FlowDiffOutputChangesElemObject = "scenario"
const FlowDiffOutputChangesElemObjectStage FlowDiffOutputChangesElemObject = "stage"

var enumValues_FlowDiffOutputChangesElemObject = []interface{}{
	"common",
	"scenario",
	"stage",
	"part",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutputChangesElemObject) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowDiffOutputChangesElemObject {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowDiffOutputChangesElemObject, v)
	}
	*j = FlowDiffOutputChangesElemObject(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["changes"]; raw != nil && !ok {
		return fmt.Errorf("field changes in FlowDiffOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowDiffOutput: required")
	}
	type Plain FlowDiffOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = FlowDiffOutput(plain)
	return nil
}
