// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry flow edit --json`: the draft the operator or the agent edits.
type FlowEditOutput struct {
	// Number of the version the draft was made from; absent if the project had no
	// flow and the draft was created empty.
	BaseVersion *int `json:"base_version,omitempty,omitzero"`

	// Whether this call created the draft; false if the draft was open already and
	// the edit continues in it.
	Created bool `json:"created"`

	// Absolute path of the draft directory.
	Dir string `json:"dir"`

	// Identifier of the project.
	Project string `json:"project"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowEditOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created"]; raw != nil && !ok {
		return fmt.Errorf("field created in FlowEditOutput: required")
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in FlowEditOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowEditOutput: required")
	}
	type Plain FlowEditOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.BaseVersion != nil && 1 > *plain.BaseVersion {
		return fmt.Errorf("field %s: must be >= %v", "base_version", 1)
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = FlowEditOutput(plain)
	return nil
}
