// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type FlowChange struct {
	// What happened to the object.
	Change FlowDiffOutputChangesElemChange `json:"change"`

	// Identifier of the object; absent for the common rules.
	Id *string `json:"id,omitempty,omitzero"`

	// Kind of the object: common for the common rules of the flow, scenario, stage,
	// part or agent for a subagent.
	Object FlowDiffOutputChangesElemObject `json:"object"`

	// Where a subagent comes from: project, or library for a subagent of the library
	// the flow names, whose copy in the version changes on apply. Only for a
	// subagent.
	Source *FlowDiffOutputChangesElemSource `json:"source,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowChange) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["change"]; raw != nil && !ok {
		return fmt.Errorf("field change in FlowChange: required")
	}
	if _, ok := raw["object"]; raw != nil && !ok {
		return fmt.Errorf("field object in FlowChange: required")
	}
	type Plain FlowChange
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Id != nil && utf8.RuneCountInString(string(*plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = FlowChange(plain)
	return nil
}

// Output of `gentry flow diff --json`: the objects of the draft that differ from
// the active flow.
type FlowDiffOutput struct {
	// Changed objects: the common rules first, then scenarios, stages, parts, project
	// subagents and library subagents, each kind by identifier. Empty if the draft is
	// the same as the active flow.
	Changes []FlowChange `json:"changes"`

	// Identifier of the project.
	Project string `json:"project"`

	// Number of the active flow version the draft is compared with; absent if the
	// project has no flow, and then every object of the draft is added.
	Version *int `json:"version,omitempty,omitzero"`
}

type FlowDiffOutputChangesElemChange string

const FlowDiffOutputChangesElemChangeAdded FlowDiffOutputChangesElemChange = "added"
const FlowDiffOutputChangesElemChangeModified FlowDiffOutputChangesElemChange = "modified"
const FlowDiffOutputChangesElemChangeRemoved FlowDiffOutputChangesElemChange = "removed"

var enumValues_FlowDiffOutputChangesElemChange = []interface{}{
	"added",
	"modified",
	"removed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutputChangesElemChange) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowDiffOutputChangesElemChange {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowDiffOutputChangesElemChange, v)
	}
	*j = FlowDiffOutputChangesElemChange(v)
	return nil
}

type FlowDiffOutputChangesElemObject string

const FlowDiffOutputChangesElemObjectAgent FlowDiffOutputChangesElemObject = "agent"
const FlowDiffOutputChangesElemObjectCommon FlowDiffOutputChangesElemObject = "common"
const FlowDiffOutputChangesElemObjectPart FlowDiffOutputChangesElemObject = "part"
const FlowDiffOutputChangesElemObjectScenario FlowDiffOutputChangesElemObject = "scenario"
const FlowDiffOutputChangesElemObjectStage FlowDiffOutputChangesElemObject = "stage"

var enumValues_FlowDiffOutputChangesElemObject = []interface{}{
	"common",
	"scenario",
	"stage",
	"part",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutputChangesElemObject) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowDiffOutputChangesElemObject {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowDiffOutputChangesElemObject, v)
	}
	*j = FlowDiffOutputChangesElemObject(v)
	return nil
}

type FlowDiffOutputChangesElemSource string

const FlowDiffOutputChangesElemSourceLibrary FlowDiffOutputChangesElemSource = "library"
const FlowDiffOutputChangesElemSourceProject FlowDiffOutputChangesElemSource = "project"

var enumValues_FlowDiffOutputChangesElemSource = []interface{}{
	"project",
	"library",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutputChangesElemSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FlowDiffOutputChangesElemSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FlowDiffOutputChangesElemSource, v)
	}
	*j = FlowDiffOutputChangesElemSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FlowDiffOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["changes"]; raw != nil && !ok {
		return fmt.Errorf("field changes in FlowDiffOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in FlowDiffOutput: required")
	}
	type Plain FlowDiffOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if plain.Version != nil && 1 > *plain.Version {
		return fmt.Errorf("field %s: must be >= %v", "version", 1)
	}
	*j = FlowDiffOutput(plain)
	return nil
}
