// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry library discard --json`: the library directory is back to the
// active library, and the variants of another machine of a conflict are removed.
type LibraryDiscardOutput struct {
	// Absolute path of the library directory.
	Dir string `json:"dir"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryDiscardOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in LibraryDiscardOutput: required")
	}
	type Plain LibraryDiscardOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	*j = LibraryDiscardOutput(plain)
	return nil
}
