// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type LibraryChange struct {
	// What happened to the subagent.
	Change LibraryDiffOutputChangesElemChange `json:"change"`

	// Identifier of the subagent, the name of its files.
	Id string `json:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryChange) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["change"]; raw != nil && !ok {
		return fmt.Errorf("field change in LibraryChange: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LibraryChange: required")
	}
	type Plain LibraryChange
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = LibraryChange(plain)
	return nil
}

// Output of `gentry library diff --json`: the subagents of the library directory
// that differ from the active library.
type LibraryDiffOutput struct {
	// The commit that applied the active library; absent if the library has never
	// been applied.
	Applied *Applied `json:"applied,omitempty,omitzero"`

	// Changed subagents by identifier. Not empty: without changes there is no draft.
	Changes []LibraryChange `json:"changes"`

	// Absolute path of the library directory.
	Dir string `json:"dir"`

	// What the synchronization of the command did; present only when there is
	// something to tell.
	Sync *Sync `json:"sync,omitempty,omitzero"`
}

type LibraryDiffOutputChangesElemChange string

const LibraryDiffOutputChangesElemChangeAdded LibraryDiffOutputChangesElemChange = "added"
const LibraryDiffOutputChangesElemChangeModified LibraryDiffOutputChangesElemChange = "modified"
const LibraryDiffOutputChangesElemChangeRemoved LibraryDiffOutputChangesElemChange = "removed"

var enumValues_LibraryDiffOutputChangesElemChange = []interface{}{
	"added",
	"modified",
	"removed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryDiffOutputChangesElemChange) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LibraryDiffOutputChangesElemChange {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LibraryDiffOutputChangesElemChange, v)
	}
	*j = LibraryDiffOutputChangesElemChange(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryDiffOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["changes"]; raw != nil && !ok {
		return fmt.Errorf("field changes in LibraryDiffOutput: required")
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in LibraryDiffOutput: required")
	}
	type Plain LibraryDiffOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	*j = LibraryDiffOutput(plain)
	return nil
}
