// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Output of `gentry library apply --json`: the draft of the library became active
// with a commit of the process repository.
type LibraryApplyOutput struct {
	// What the layout of subagents in the free worktrees of every project did;
	// present only when there is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// The commit that applied the library.
	Applied Applied `json:"applied"`

	// Whether the commit is sent to the remote repository; false without one or when
	// it did not answer, and then it is sent by a later command.
	Sent bool `json:"sent"`

	// What the synchronization of the command did; present only when there is
	// something to tell.
	Sync *Sync `json:"sync,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryApplyOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["applied"]; raw != nil && !ok {
		return fmt.Errorf("field applied in LibraryApplyOutput: required")
	}
	if _, ok := raw["sent"]; raw != nil && !ok {
		return fmt.Errorf("field sent in LibraryApplyOutput: required")
	}
	type Plain LibraryApplyOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LibraryApplyOutput(plain)
	return nil
}
