// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Details of the error library_draft_invalid: the draft of the library of
// subagents has problems, so it is not applied.
type LibraryDraftInvalidDetails struct {
	// Absolute path of the library directory.
	Dir string `json:"dir"`

	// All problems of the draft by subagent, and files that do not belong to the
	// library last. The file of a problem is its path inside the library.
	Problems []FlowProblem `json:"problems"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryDraftInvalidDetails) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in LibraryDraftInvalidDetails: required")
	}
	if _, ok := raw["problems"]; raw != nil && !ok {
		return fmt.Errorf("field problems in LibraryDraftInvalidDetails: required")
	}
	type Plain LibraryDraftInvalidDetails
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	if plain.Problems != nil && len(plain.Problems) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "problems", 1)
	}
	*j = LibraryDraftInvalidDetails(plain)
	return nil
}
