// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry note add --json`.
type NoteAddOutput struct {
	// The note added.
	Note TaskNote `json:"note"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoteAddOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["note"]; raw != nil && !ok {
		return fmt.Errorf("field note in NoteAddOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in NoteAddOutput: required")
	}
	type Plain NoteAddOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = NoteAddOutput(plain)
	return nil
}
