// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry note list --json`.
type NoteListOutput struct {
	// Notes of the task by number.
	Notes []TaskNote `json:"notes"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoteListOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["notes"]; raw != nil && !ok {
		return fmt.Errorf("field notes in NoteListOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in NoteListOutput: required")
	}
	type Plain NoteListOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = NoteListOutput(plain)
	return nil
}
