// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry note add --input`. An unknown field is an error. The source is
// not part of the input: Gentry determines it by who calls the command.
type NoteAddInput struct {
	// Text of the note; may have several lines.
	Text string `json:"text"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoteAddInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in NoteAddInput: required")
	}
	type Plain NoteAddInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	*j = NoteAddInput(plain)
	return nil
}
