// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry operator record --json`.
type OperatorRecordOutput struct {
	// The decision recorded.
	Decision OperatorDecision `json:"decision"`

	// The return the decision allows, after the record; only with allow_return.
	Return *OperatorRecordOutputReturn `json:"return,omitempty,omitzero"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`
}

// The return the decision allows, after the record; only with allow_return.
type OperatorRecordOutputReturn struct {
	// Returns of the limit the operator allowed beyond the flow.
	AllowedReturns int `json:"allowed_returns"`

	// Limit of returns by the transition with the returns the operator allowed.
	MaxReturns int `json:"max_returns"`

	// Node the return is from: the current node of the task.
	Node string `json:"node"`

	// Returns made by the transition, counted anew after a return by an outer loop.
	Returns int `json:"returns"`

	// Node the return goes back to.
	To string `json:"to"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorRecordOutputReturn) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["allowed_returns"]; raw != nil && !ok {
		return fmt.Errorf("field allowed_returns in OperatorRecordOutputReturn: required")
	}
	if _, ok := raw["max_returns"]; raw != nil && !ok {
		return fmt.Errorf("field max_returns in OperatorRecordOutputReturn: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in OperatorRecordOutputReturn: required")
	}
	if _, ok := raw["returns"]; raw != nil && !ok {
		return fmt.Errorf("field returns in OperatorRecordOutputReturn: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in OperatorRecordOutputReturn: required")
	}
	type Plain OperatorRecordOutputReturn
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.AllowedReturns {
		return fmt.Errorf("field %s: must be >= %v", "allowed_returns", 1)
	}
	if 1 > plain.MaxReturns {
		return fmt.Errorf("field %s: must be >= %v", "max_returns", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 0 > plain.Returns {
		return fmt.Errorf("field %s: must be >= %v", "returns", 0)
	}
	if utf8.RuneCountInString(string(plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = OperatorRecordOutputReturn(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorRecordOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["decision"]; raw != nil && !ok {
		return fmt.Errorf("field decision in OperatorRecordOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in OperatorRecordOutput: required")
	}
	type Plain OperatorRecordOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = OperatorRecordOutput(plain)
	return nil
}
