// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

// A decision of the operator: the words of the operator given in conversation,
// with the question they answer if there was one. Decisions are only added; a
// later one cancels an earlier one by its words.
type OperatorDecision struct {
	// The node the decision allows one more return to from node, beyond the limit;
	// absent if it allows none.
	AllowReturn *string `json:"allow_return,omitempty,omitzero"`

	// The words of the operator as given; may have several lines.
	Answer string `json:"answer"`

	// Node of the pass the decision was recorded at.
	Node string `json:"node"`

	// Number of the decision within the task, from 1.
	Number int `json:"number"`

	// Options of the answer offered with the question; absent if none were.
	Options []QuestionOption `json:"options,omitempty,omitzero"`

	// The question the operator answered; absent for words given without one.
	Question *string `json:"question,omitempty,omitzero"`

	// Time the decision was recorded in UTC, RFC 3339 with milliseconds.
	Recorded time.Time `json:"recorded"`

	// Round of that pass.
	Round int `json:"round"`

	// Who recorded the decision: operator, or agent from the words of the operator.
	Source OperatorDecisionSource `json:"source"`

	// Stage of that node.
	Stage string `json:"stage"`
}

type OperatorDecisionSource string

const OperatorDecisionSourceAgent OperatorDecisionSource = "agent"
const OperatorDecisionSourceOperator OperatorDecisionSource = "operator"

var enumValues_OperatorDecisionSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorDecisionSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OperatorDecisionSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OperatorDecisionSource, v)
	}
	*j = OperatorDecisionSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorDecision) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["answer"]; raw != nil && !ok {
		return fmt.Errorf("field answer in OperatorDecision: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in OperatorDecision: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in OperatorDecision: required")
	}
	if _, ok := raw["recorded"]; raw != nil && !ok {
		return fmt.Errorf("field recorded in OperatorDecision: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in OperatorDecision: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in OperatorDecision: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in OperatorDecision: required")
	}
	type Plain OperatorDecision
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AllowReturn != nil && utf8.RuneCountInString(string(*plain.AllowReturn)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "allow_return", 1)
	}
	if utf8.RuneCountInString(string(plain.Answer)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "answer", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if plain.Options != nil && len(plain.Options) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "options", 2)
	}
	if plain.Question != nil && utf8.RuneCountInString(string(*plain.Question)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "question", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	*j = OperatorDecision(plain)
	return nil
}
