// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry operator record --input`. An unknown field is an error. The
// source is not part of the input: Gentry determines it by who calls the command.
type OperatorRecordInput struct {
	// The node the operator allows one more return to from the current stage, beyond
	// its limit.
	AllowReturn *string `json:"allow_return,omitempty,omitzero"`

	// The words of the operator as given; may have several lines.
	Answer string `json:"answer"`

	// Options of the answer offered with the question: only with the question, at
	// least two, at most one recommended.
	Options []QuestionOption `json:"options,omitempty,omitzero"`

	// The question the operator answered; absent for words given without one. May
	// have several lines.
	Question *string `json:"question,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OperatorRecordInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["answer"]; raw != nil && !ok {
		return fmt.Errorf("field answer in OperatorRecordInput: required")
	}
	type Plain OperatorRecordInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AllowReturn != nil && utf8.RuneCountInString(string(*plain.AllowReturn)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "allow_return", 1)
	}
	if utf8.RuneCountInString(string(plain.Answer)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "answer", 1)
	}
	if plain.Options != nil && len(plain.Options) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "options", 2)
	}
	if plain.Question != nil && utf8.RuneCountInString(string(*plain.Question)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "question", 1)
	}
	*j = OperatorRecordInput(plain)
	return nil
}
