// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "time"
import "unicode/utf8"

// Output of `gentry process status --json`: the state of the process on this
// machine, as known without the network.
type ProcessStatusOutput struct {
	// Kinds in conflict: the variants of another machine are in their conflict
	// directory.
	Conflicts []ProcessItem `json:"conflicts"`

	// Kinds whose directory differs from the active variant.
	Drafts []ProcessItem `json:"drafts"`

	// Address of the remote repository; absent if none is connected.
	Remote *string `json:"remote,omitempty,omitzero"`

	// Time of the last successful synchronization in UTC, RFC 3339 with milliseconds;
	// absent if there was none.
	Synced *time.Time `json:"synced,omitempty,omitzero"`

	// Kinds changed by commits the remote repository does not have yet; empty without
	// a remote repository.
	Unsent []ProcessItem `json:"unsent"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessStatusOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["conflicts"]; raw != nil && !ok {
		return fmt.Errorf("field conflicts in ProcessStatusOutput: required")
	}
	if _, ok := raw["drafts"]; raw != nil && !ok {
		return fmt.Errorf("field drafts in ProcessStatusOutput: required")
	}
	if _, ok := raw["unsent"]; raw != nil && !ok {
		return fmt.Errorf("field unsent in ProcessStatusOutput: required")
	}
	type Plain ProcessStatusOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Remote != nil && utf8.RuneCountInString(string(*plain.Remote)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "remote", 1)
	}
	*j = ProcessStatusOutput(plain)
	return nil
}
