// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// A kind of the process of the operator: the flow of a project or the library of
// subagents.
type ProcessItem struct {
	// flow for the flow of a project, library for the library of subagents.
	Kind ProcessItemKind `json:"kind"`

	// Identifier of the project; only for a flow.
	Project *string `json:"project,omitempty,omitzero"`
}

type ProcessItemKind string

const ProcessItemKindFlow ProcessItemKind = "flow"
const ProcessItemKindLibrary ProcessItemKind = "library"

var enumValues_ProcessItemKind = []interface{}{
	"flow",
	"library",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessItemKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProcessItemKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProcessItemKind, v)
	}
	*j = ProcessItemKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessItem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in ProcessItem: required")
	}
	type Plain ProcessItem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Project != nil && utf8.RuneCountInString(string(*plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = ProcessItem(plain)
	return nil
}
