// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Output of `gentry process remote --json`: the remote repository of the process
// is connected and synchronized with.
type ProcessRemoteOutput struct {
	// Kinds whose variant of this machine became a draft over the remote one; empty
	// if none.
	Drafts []ProcessItem `json:"drafts"`

	// Address of the remote repository.
	Remote string `json:"remote"`

	// sent: the remote repository was empty and got the process of this machine;
	// received: this machine had no process and got the remote one; merged: both had
	// one and they are brought together; unchanged: both had the same.
	Result ProcessRemoteOutputResult `json:"result"`
}

type ProcessRemoteOutputResult string

const ProcessRemoteOutputResultMerged ProcessRemoteOutputResult = "merged"
const ProcessRemoteOutputResultReceived ProcessRemoteOutputResult = "received"
const ProcessRemoteOutputResultSent ProcessRemoteOutputResult = "sent"
const ProcessRemoteOutputResultUnchanged ProcessRemoteOutputResult = "unchanged"

var enumValues_ProcessRemoteOutputResult = []interface{}{
	"sent",
	"received",
	"merged",
	"unchanged",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessRemoteOutputResult) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProcessRemoteOutputResult {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProcessRemoteOutputResult, v)
	}
	*j = ProcessRemoteOutputResult(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessRemoteOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["drafts"]; raw != nil && !ok {
		return fmt.Errorf("field drafts in ProcessRemoteOutput: required")
	}
	if _, ok := raw["remote"]; raw != nil && !ok {
		return fmt.Errorf("field remote in ProcessRemoteOutput: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ProcessRemoteOutput: required")
	}
	type Plain ProcessRemoteOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Remote)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "remote", 1)
	}
	*j = ProcessRemoteOutput(plain)
	return nil
}
