// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Output of `gentry process sync --json`: the process is synchronized with the
// remote repository.
type ProcessSyncOutput struct {
	// Kinds changed on both machines that could not be brought together: the variant
	// of the other machine is active, the changes of this machine are a draft.
	Conflicts []ProcessItem `json:"conflicts"`

	// Kinds changed on another machine and taken.
	Received []ProcessItem `json:"received"`

	// Kinds changed around Gentry with problems: the last checked variant is active
	// again, the change is a draft.
	Restored []ProcessItem `json:"restored"`

	// Kinds changed on this machine and sent.
	Sent []ProcessItem `json:"sent"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProcessSyncOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["conflicts"]; raw != nil && !ok {
		return fmt.Errorf("field conflicts in ProcessSyncOutput: required")
	}
	if _, ok := raw["received"]; raw != nil && !ok {
		return fmt.Errorf("field received in ProcessSyncOutput: required")
	}
	if _, ok := raw["restored"]; raw != nil && !ok {
		return fmt.Errorf("field restored in ProcessSyncOutput: required")
	}
	if _, ok := raw["sent"]; raw != nil && !ok {
		return fmt.Errorf("field sent in ProcessSyncOutput: required")
	}
	type Plain ProcessSyncOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProcessSyncOutput(plain)
	return nil
}
