// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry project add --json`.
type ProjectAddOutput struct {
	// What happened: added or unchanged. The list is open: a client shows an unknown
	// value as is.
	Action string `json:"action"`

	// What the layout of subagents in the worktrees added did; present only when
	// there is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// Absolute path of the project knowledge repository.
	Knowledge string `json:"knowledge"`

	// Whether this call created the project knowledge: wrote and committed its
	// project information.
	KnowledgeCreated bool `json:"knowledge_created"`

	// Absolute path of the main worktree of the project.
	MainWorktree string `json:"main_worktree"`

	// Prefix of task numbers; a personal setting of the operator.
	Prefix string `json:"prefix"`

	// Project identifier shared by the team, as recorded in the project knowledge.
	Project string `json:"project"`

	// Worktrees this call added to the pool: the main one and the one the command ran
	// in; empty when nothing changed.
	Worktrees []string `json:"worktrees"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProjectAddOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in ProjectAddOutput: required")
	}
	if _, ok := raw["knowledge"]; raw != nil && !ok {
		return fmt.Errorf("field knowledge in ProjectAddOutput: required")
	}
	if _, ok := raw["knowledge_created"]; raw != nil && !ok {
		return fmt.Errorf("field knowledge_created in ProjectAddOutput: required")
	}
	if _, ok := raw["main_worktree"]; raw != nil && !ok {
		return fmt.Errorf("field main_worktree in ProjectAddOutput: required")
	}
	if _, ok := raw["prefix"]; raw != nil && !ok {
		return fmt.Errorf("field prefix in ProjectAddOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in ProjectAddOutput: required")
	}
	if _, ok := raw["worktrees"]; raw != nil && !ok {
		return fmt.Errorf("field worktrees in ProjectAddOutput: required")
	}
	type Plain ProjectAddOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Action)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "action", 1)
	}
	if utf8.RuneCountInString(string(plain.Knowledge)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "knowledge", 1)
	}
	if utf8.RuneCountInString(string(plain.MainWorktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "main_worktree", 1)
	}
	if utf8.RuneCountInString(string(plain.Prefix)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "prefix", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = ProjectAddOutput(plain)
	return nil
}
