// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

type ProjectListItem struct {
	// Absolute path of the project knowledge repository.
	Knowledge string `json:"knowledge"`

	// Absolute path of the main worktree of the project.
	MainWorktree string `json:"main_worktree"`

	// Prefix of task numbers.
	Prefix string `json:"prefix"`

	// Project identifier.
	Project string `json:"project"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProjectListItem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["knowledge"]; raw != nil && !ok {
		return fmt.Errorf("field knowledge in ProjectListItem: required")
	}
	if _, ok := raw["main_worktree"]; raw != nil && !ok {
		return fmt.Errorf("field main_worktree in ProjectListItem: required")
	}
	if _, ok := raw["prefix"]; raw != nil && !ok {
		return fmt.Errorf("field prefix in ProjectListItem: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in ProjectListItem: required")
	}
	type Plain ProjectListItem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Knowledge)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "knowledge", 1)
	}
	if utf8.RuneCountInString(string(plain.MainWorktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "main_worktree", 1)
	}
	if utf8.RuneCountInString(string(plain.Prefix)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "prefix", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = ProjectListItem(plain)
	return nil
}

// Output of `gentry project list --json`.
type ProjectListOutput struct {
	// Projects connected on this machine, by identifier.
	Projects []ProjectListItem `json:"projects"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProjectListOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["projects"]; raw != nil && !ok {
		return fmt.Errorf("field projects in ProjectListOutput: required")
	}
	type Plain ProjectListOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProjectListOutput(plain)
	return nil
}
