// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// An option of an answer to a question of the agent to the operator.
type QuestionOption struct {
	// What the option means; may have several lines.
	Description *string `json:"description,omitempty,omitzero"`

	// Name of the option: one line, up to 120 characters.
	Label string `json:"label"`

	// The agent recommends the option; at most one option of a question is.
	Recommended *bool `json:"recommended,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *QuestionOption) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in QuestionOption: required")
	}
	type Plain QuestionOption
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "description", 1)
	}
	if utf8.RuneCountInString(string(plain.Label)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "label", 1)
	}
	if utf8.RuneCountInString(string(plain.Label)) > 120 {
		return fmt.Errorf("field %s length: must be <= %d", "label", 120)
	}
	*j = QuestionOption(plain)
	return nil
}
