// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry setup <tool> --json`.
type SetupOutput struct {
	// What happened in the tool: installed, updated, unchanged or switched (the
	// plugin was served from another directory, see previous_dir). The list is open:
	// a client shows an unknown value as is.
	Action string `json:"action"`

	// Directory of the integration files built for the tool.
	Dir string `json:"dir"`

	// Whether the plugin is enabled in the tool; Gentry does not enable a plugin the
	// operator disabled.
	Enabled bool `json:"enabled"`

	// The rule that allows the tools of Gentry in the user settings of the tool:
	// added, present (the settings had it) or failed (the settings cannot be read and
	// are left as they are). The list is open: a client shows an unknown value as is.
	Permission *string `json:"permission,omitempty,omitzero"`

	// Version of the built plugin; it changes whenever the plugin content does.
	PluginVersion string `json:"plugin_version"`

	// Directory the tool served the plugin from before it was switched to dir; only
	// with the action switched.
	PreviousDir *string `json:"previous_dir,omitempty,omitzero"`

	// The file of the user settings of the tool the rule is in.
	Settings *string `json:"settings,omitempty,omitzero"`

	// The tool Gentry was set up for, such as claude.
	Tool string `json:"tool"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetupOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in SetupOutput: required")
	}
	if _, ok := raw["dir"]; raw != nil && !ok {
		return fmt.Errorf("field dir in SetupOutput: required")
	}
	if _, ok := raw["enabled"]; raw != nil && !ok {
		return fmt.Errorf("field enabled in SetupOutput: required")
	}
	if _, ok := raw["plugin_version"]; raw != nil && !ok {
		return fmt.Errorf("field plugin_version in SetupOutput: required")
	}
	if _, ok := raw["tool"]; raw != nil && !ok {
		return fmt.Errorf("field tool in SetupOutput: required")
	}
	type Plain SetupOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Action)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "action", 1)
	}
	if utf8.RuneCountInString(string(plain.Dir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "dir", 1)
	}
	if plain.Permission != nil && utf8.RuneCountInString(string(*plain.Permission)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "permission", 1)
	}
	if utf8.RuneCountInString(string(plain.PluginVersion)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "plugin_version", 1)
	}
	if plain.PreviousDir != nil && utf8.RuneCountInString(string(*plain.PreviousDir)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "previous_dir", 1)
	}
	if plain.Settings != nil && utf8.RuneCountInString(string(*plain.Settings)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "settings", 1)
	}
	if utf8.RuneCountInString(string(plain.Tool)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "tool", 1)
	}
	*j = SetupOutput(plain)
	return nil
}
