// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Input of `gentry stage exit --input`: the fields as one object, in a file or on
// the standard input. An unknown field is an error. The source is not part of the
// input: Gentry determines it by who calls the command.
type StageExitInput struct {
	// Name of the artifact of the task; only for an exit of kind artifact.
	Artifact *string `json:"artifact,omitempty,omitzero"`

	// Kind of the exit: artifact — an artifact of the task, result — the result of an
	// event, negative — a negative result with where it was looked for.
	Kind StageExitInputKind `json:"kind"`

	// Why the transition is taken; required at a fork and for a single transition
	// with a condition.
	Reason *string `json:"reason,omitempty,omitzero"`

	// Text of the exit.
	Text string `json:"text"`

	// The node to go to, or finish; required at a fork.
	To *string `json:"to,omitempty,omitzero"`
}

type StageExitInputKind string

const StageExitInputKindArtifact StageExitInputKind = "artifact"
const StageExitInputKindNegative StageExitInputKind = "negative"
const StageExitInputKindResult StageExitInputKind = "result"

var enumValues_StageExitInputKind = []interface{}{
	"artifact",
	"result",
	"negative",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageExitInputKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_StageExitInputKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_StageExitInputKind, v)
	}
	*j = StageExitInputKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageExitInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in StageExitInput: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in StageExitInput: required")
	}
	type Plain StageExitInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Artifact != nil && utf8.RuneCountInString(string(*plain.Artifact)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "artifact", 1)
	}
	if plain.Reason != nil && utf8.RuneCountInString(string(*plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	if plain.To != nil && utf8.RuneCountInString(string(*plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = StageExitInput(plain)
	return nil
}
