// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry stage show --json`: the current stage of the task from the
// snapshot of its flow.
type StageShowOutput struct {
	// Node of the scenario the task is at.
	Node string `json:"node"`

	// Number of the pass of the node in the task, from 1.
	Round int `json:"round"`

	// The stage of the node.
	Stage StageShowStage `json:"stage"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`

	// Transitions from the node in the order of the scenario.
	Transitions []StageShowTransition `json:"transitions"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageShowOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StageShowOutput: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StageShowOutput: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in StageShowOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in StageShowOutput: required")
	}
	if _, ok := raw["transitions"]; raw != nil && !ok {
		return fmt.Errorf("field transitions in StageShowOutput: required")
	}
	type Plain StageShowOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = StageShowOutput(plain)
	return nil
}

type StageShowPart struct {
	// Identifier of the part.
	Id string `json:"id"`

	// Text of the part in markdown.
	Text string `json:"text"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageShowPart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in StageShowPart: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in StageShowPart: required")
	}
	type Plain StageShowPart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = StageShowPart(plain)
	return nil
}

// The stage of the node.
type StageShowStage struct {
	// Who does the stage: orchestrator, operator or a subagent.
	Executor string `json:"executor"`

	// What the stage must end with.
	Exit string `json:"exit"`

	// Identifier of the stage.
	Id string `json:"id"`

	// Instruction of the stage in markdown.
	Instruction string `json:"instruction"`

	// Parts the stage includes, in the order of include.
	Parts []StageShowPart `json:"parts"`

	// Title of the stage.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageShowStage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["executor"]; raw != nil && !ok {
		return fmt.Errorf("field executor in StageShowStage: required")
	}
	if _, ok := raw["exit"]; raw != nil && !ok {
		return fmt.Errorf("field exit in StageShowStage: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in StageShowStage: required")
	}
	if _, ok := raw["instruction"]; raw != nil && !ok {
		return fmt.Errorf("field instruction in StageShowStage: required")
	}
	if _, ok := raw["parts"]; raw != nil && !ok {
		return fmt.Errorf("field parts in StageShowStage: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in StageShowStage: required")
	}
	type Plain StageShowStage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Executor)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "executor", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = StageShowStage(plain)
	return nil
}

type StageShowTransition struct {
	// Condition of the transition; absent for one without.
	If *string `json:"if,omitempty,omitzero"`

	// Limit of returns by the transition; only for a return.
	MaxReturns *int `json:"max_returns,omitempty,omitzero"`

	// Returns made by the transition, counted anew after a return by an outer loop;
	// only for a return.
	Returns *int `json:"returns,omitempty,omitzero"`

	// Stage of that node; absent for finish.
	Stage *string `json:"stage,omitempty,omitzero"`

	// Title of that stage; absent for finish.
	Title *string `json:"title,omitempty,omitzero"`

	// The node of the transition, or finish for the end of the scenario.
	To string `json:"to"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageShowTransition) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in StageShowTransition: required")
	}
	type Plain StageShowTransition
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.If != nil && utf8.RuneCountInString(string(*plain.If)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "if", 1)
	}
	if plain.MaxReturns != nil && 1 > *plain.MaxReturns {
		return fmt.Errorf("field %s: must be >= %v", "max_returns", 1)
	}
	if plain.Returns != nil && 0 > *plain.Returns {
		return fmt.Errorf("field %s: must be >= %v", "returns", 0)
	}
	if plain.Stage != nil && utf8.RuneCountInString(string(*plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	if utf8.RuneCountInString(string(plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = StageShowTransition(plain)
	return nil
}
