// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry stage skip --input`. An unknown field is an error. The source
// is not part of the input: Gentry determines it by who calls the command.
type StageSkipInput struct {
	// Why the stage is skipped; at a fork, also why the transition is taken.
	Reason string `json:"reason"`

	// The node to go to, or finish; required at a fork.
	To *string `json:"to,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageSkipInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in StageSkipInput: required")
	}
	type Plain StageSkipInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if plain.To != nil && utf8.RuneCountInString(string(*plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = StageSkipInput(plain)
	return nil
}
