// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Output of `gentry stage exit --json` and `gentry stage skip --json`.
type StageCloseOutput struct {
	// The pass closed, as an element of the path.
	Closed TaskPass `json:"closed"`

	// The task after the transition.
	Task Task `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StageCloseOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["closed"]; raw != nil && !ok {
		return fmt.Errorf("field closed in StageCloseOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in StageCloseOutput: required")
	}
	type Plain StageCloseOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StageCloseOutput(plain)
	return nil
}
