// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry step add`, `gentry step done` and `gentry step drop` with
// --json: the steps of the current pass.
type StepListOutput struct {
	// Numbers of the steps added; only for step add.
	Added []int `json:"added,omitempty,omitzero"`

	// Node of the current pass.
	Node string `json:"node"`

	// Round of the current pass.
	Round int `json:"round"`

	// Steps of the current pass in the order added.
	Steps []TaskStep `json:"steps"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepListOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in StepListOutput: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in StepListOutput: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in StepListOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in StepListOutput: required")
	}
	type Plain StepListOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = StepListOutput(plain)
	return nil
}
