// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry step done --input`. An unknown field is an error. The source is
// not part of the input: Gentry determines it by who calls the command.
type StepDoneInput struct {
	// How the result of the step was checked.
	Check *string `json:"check,omitempty,omitzero"`

	// Number of the step of the current stage.
	Step int `json:"step"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepDoneInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["step"]; raw != nil && !ok {
		return fmt.Errorf("field step in StepDoneInput: required")
	}
	type Plain StepDoneInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Check != nil && utf8.RuneCountInString(string(*plain.Check)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "check", 1)
	}
	if 1 > plain.Step {
		return fmt.Errorf("field %s: must be >= %v", "step", 1)
	}
	*j = StepDoneInput(plain)
	return nil
}
