// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Input of `gentry step add --input`. An unknown field is an error. The source is
// not part of the input: Gentry determines it by who calls the command.
type StepAddInput struct {
	// Steps to add after the steps of the current stage: each one line of up to 120
	// characters.
	Steps []string `json:"steps"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepAddInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in StepAddInput: required")
	}
	type Plain StepAddInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Steps != nil && len(plain.Steps) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "steps", 1)
	}
	*j = StepAddInput(plain)
	return nil
}
