// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry step drop --input`. An unknown field is an error. The source is
// not part of the input: Gentry determines it by who calls the command.
type StepDropInput struct {
	// Why the step is dropped.
	Reason string `json:"reason"`

	// Number of the step of the current stage.
	Step int `json:"step"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StepDropInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in StepDropInput: required")
	}
	if _, ok := raw["step"]; raw != nil && !ok {
		return fmt.Errorf("field step in StepDropInput: required")
	}
	type Plain StepDropInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if 1 > plain.Step {
		return fmt.Errorf("field %s: must be >= %v", "step", 1)
	}
	*j = StepDropInput(plain)
	return nil
}
