// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

// What the synchronization with the remote repository of the process did inside a
// command. Only the fields with something to tell are present.
type Sync struct {
	// What the layout of subagents in the free worktrees of the projects whose flow
	// or library was received did; present only when there is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// Kinds changed on both machines that could not be brought together: the variant
	// of the other machine is active, the changes of this machine are a draft.
	Conflicts []ProcessItem `json:"conflicts,omitempty,omitzero"`

	// Kinds changed on another machine and taken.
	Received []ProcessItem `json:"received,omitempty,omitzero"`

	// Kinds changed around Gentry with problems: the last checked variant is active
	// again, the change is a draft.
	Restored []ProcessItem `json:"restored,omitempty,omitzero"`

	// Kinds changed on this machine and sent.
	Sent []ProcessItem `json:"sent,omitempty,omitzero"`

	// Present and true if the remote repository did not answer: the command worked
	// with what the machine has.
	Unavailable *bool `json:"unavailable,omitempty,omitzero"`
}
