// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Output of `gentry task take --json`: the task is taken in the worktree.
type TaskTakeOutput struct {
	// What the layout of subagents in the worktree of the task did; present only when
	// there is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// What the synchronization of the command did; present only when there is
	// something to tell.
	Sync *Sync `json:"sync,omitempty,omitzero"`

	// The task taken.
	Task Task `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskTakeOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in TaskTakeOutput: required")
	}
	type Plain TaskTakeOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TaskTakeOutput(plain)
	return nil
}
