// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

// A pass of a task through a node of its scenario: one per entry into the node.
// The current pass has no fields of closing.
type TaskPass struct {
	// Time the pass was closed in UTC, RFC 3339 with milliseconds.
	Closed *time.Time `json:"closed,omitempty,omitzero"`

	// Time the task entered the node in UTC, RFC 3339 with milliseconds.
	Entered time.Time `json:"entered"`

	// The exit of a pass closed by an exit.
	Exit *TaskPassExit `json:"exit,omitempty,omitzero"`

	// Node of the scenario.
	Node string `json:"node"`

	// How the pass was closed: exit — by an exit, skip — the stage was skipped.
	Outcome *TaskPassOutcome `json:"outcome,omitempty,omitzero"`

	// Why the transition was taken, at a fork; why the stage was skipped, for a skip.
	Reason *string `json:"reason,omitempty,omitzero"`

	// Number of the pass of the node in the task, from 1.
	Round int `json:"round"`

	// Who closed the pass: operator or agent.
	Source *TaskPassSource `json:"source,omitempty,omitzero"`

	// Stage of the node.
	Stage string `json:"stage"`

	// Steps of the pass in the order added.
	Steps []TaskStep `json:"steps"`

	// The node taken from the node, or finish for the end of the scenario.
	To *string `json:"to,omitempty,omitzero"`
}

// The exit of a pass closed by an exit.
type TaskPassExit struct {
	// Name of the artifact of an exit of kind artifact.
	Artifact *string `json:"artifact,omitempty,omitzero"`

	// Kind of the exit: artifact — an artifact of the task, result — the result of an
	// event, negative — a negative result with where it was looked for.
	Kind TaskPassExitKind `json:"kind"`

	// Text of the exit.
	Text string `json:"text"`
}

type TaskPassExitKind string

const TaskPassExitKindArtifact TaskPassExitKind = "artifact"
const TaskPassExitKindNegative TaskPassExitKind = "negative"
const TaskPassExitKindResult TaskPassExitKind = "result"

var enumValues_TaskPassExitKind = []interface{}{
	"artifact",
	"result",
	"negative",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPassExitKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskPassExitKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskPassExitKind, v)
	}
	*j = TaskPassExitKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPassExit) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in TaskPassExit: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in TaskPassExit: required")
	}
	type Plain TaskPassExit
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Artifact != nil && utf8.RuneCountInString(string(*plain.Artifact)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "artifact", 1)
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	*j = TaskPassExit(plain)
	return nil
}

type TaskPassOutcome string

const TaskPassOutcomeExit TaskPassOutcome = "exit"
const TaskPassOutcomeSkip TaskPassOutcome = "skip"

var enumValues_TaskPassOutcome = []interface{}{
	"exit",
	"skip",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPassOutcome) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskPassOutcome {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskPassOutcome, v)
	}
	*j = TaskPassOutcome(v)
	return nil
}

type TaskPassSource string

const TaskPassSourceAgent TaskPassSource = "agent"
const TaskPassSourceOperator TaskPassSource = "operator"

var enumValues_TaskPassSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPassSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskPassSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskPassSource, v)
	}
	*j = TaskPassSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPass) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["entered"]; raw != nil && !ok {
		return fmt.Errorf("field entered in TaskPass: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in TaskPass: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in TaskPass: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in TaskPass: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in TaskPass: required")
	}
	type Plain TaskPass
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if plain.Reason != nil && utf8.RuneCountInString(string(*plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	if plain.To != nil && utf8.RuneCountInString(string(*plain.To)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "to", 1)
	}
	*j = TaskPass(plain)
	return nil
}
