// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Output of `gentry task show --json`. The path is always full: --path changes
// only the text output.
type TaskShowOutput struct {
	// Artifacts of the task by name.
	Artifacts []TaskArtifact `json:"artifacts"`

	// Notes of the task by number.
	Notes []TaskNote `json:"notes"`

	// Decisions of the operator by number; empty if there are none. --statement
	// changes only the text output.
	OperatorDecisions []OperatorDecision `json:"operator_decisions"`

	// The passes of the task in the order entered; the last one is current unless the
	// scenario is passed, and holds the steps of the current stage.
	Path []TaskPass `json:"path"`

	// The task named, or the task of the current worktree.
	Task Task `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskShowOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["artifacts"]; raw != nil && !ok {
		return fmt.Errorf("field artifacts in TaskShowOutput: required")
	}
	if _, ok := raw["notes"]; raw != nil && !ok {
		return fmt.Errorf("field notes in TaskShowOutput: required")
	}
	if _, ok := raw["operator_decisions"]; raw != nil && !ok {
		return fmt.Errorf("field operator_decisions in TaskShowOutput: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in TaskShowOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in TaskShowOutput: required")
	}
	type Plain TaskShowOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TaskShowOutput(plain)
	return nil
}
