// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

// An artifact of a task: a copy of a file kept by Gentry, or a link Gentry does
// not visit.
type TaskArtifact struct {
	// Kind of the artifact: file — a copy of a file, link — an address.
	Kind TaskArtifactKind `json:"kind"`

	// Name of the artifact: Latin letters, digits, dot, hyphen and underscore.
	Name string `json:"name"`

	// Absolute path of the copy of a file.
	Path *string `json:"path,omitempty,omitzero"`

	// Time the artifact was saved in UTC, RFC 3339 with milliseconds.
	Saved time.Time `json:"saved"`

	// Who saved the artifact: operator or agent.
	Source TaskArtifactSource `json:"source"`

	// Address of a link.
	Url *string `json:"url,omitempty,omitzero"`
}

type TaskArtifactKind string

const TaskArtifactKindFile TaskArtifactKind = "file"
const TaskArtifactKindLink TaskArtifactKind = "link"

var enumValues_TaskArtifactKind = []interface{}{
	"file",
	"link",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskArtifactKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskArtifactKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskArtifactKind, v)
	}
	*j = TaskArtifactKind(v)
	return nil
}

type TaskArtifactSource string

const TaskArtifactSourceAgent TaskArtifactSource = "agent"
const TaskArtifactSourceOperator TaskArtifactSource = "operator"

var enumValues_TaskArtifactSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskArtifactSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskArtifactSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskArtifactSource, v)
	}
	*j = TaskArtifactSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskArtifact) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in TaskArtifact: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in TaskArtifact: required")
	}
	if _, ok := raw["saved"]; raw != nil && !ok {
		return fmt.Errorf("field saved in TaskArtifact: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskArtifact: required")
	}
	type Plain TaskArtifact
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.Path != nil && utf8.RuneCountInString(string(*plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	if plain.Url != nil && utf8.RuneCountInString(string(*plain.Url)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "url", 1)
	}
	*j = TaskArtifact(plain)
	return nil
}
