// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

type TaskListItem struct {
	// The scenario of the task is passed, as in Task.
	Finished bool `json:"finished"`

	// Identifier of the task, such as SHOP-1.
	Id string `json:"id"`

	// Progress of the task, as in Task.
	Progress TaskProgress `json:"progress"`

	// Identifier of the project.
	Project string `json:"project"`

	// Scenario of the task.
	Scenario TaskScenario `json:"scenario"`

	// Current stage of the task; absent once the scenario is passed.
	Stage *TaskStage `json:"stage,omitempty,omitzero"`

	// State of the task, as in Task.
	State TaskListOutputTasksElemState `json:"state"`

	// Time the task was taken in UTC, RFC 3339 with milliseconds.
	Taken time.Time `json:"taken"`

	// Title of the task.
	Title string `json:"title"`

	// Absolute path of the worktree the task holds; absent once the task released it.
	Worktree *string `json:"worktree,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskListItem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["finished"]; raw != nil && !ok {
		return fmt.Errorf("field finished in TaskListItem: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TaskListItem: required")
	}
	if _, ok := raw["progress"]; raw != nil && !ok {
		return fmt.Errorf("field progress in TaskListItem: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in TaskListItem: required")
	}
	if _, ok := raw["scenario"]; raw != nil && !ok {
		return fmt.Errorf("field scenario in TaskListItem: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in TaskListItem: required")
	}
	if _, ok := raw["taken"]; raw != nil && !ok {
		return fmt.Errorf("field taken in TaskListItem: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskListItem: required")
	}
	type Plain TaskListItem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if plain.Worktree != nil && utf8.RuneCountInString(string(*plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskListItem(plain)
	return nil
}

// Output of `gentry task list --json`.
type TaskListOutput struct {
	// Tasks that match the flags: by project, then by number.
	Tasks []TaskListItem `json:"tasks"`
}

type TaskListOutputTasksElemState string

const TaskListOutputTasksElemStateActive TaskListOutputTasksElemState = "active"
const TaskListOutputTasksElemStateCancelled TaskListOutputTasksElemState = "cancelled"
const TaskListOutputTasksElemStateClosed TaskListOutputTasksElemState = "closed"
const TaskListOutputTasksElemStateWaiting TaskListOutputTasksElemState = "waiting"

var enumValues_TaskListOutputTasksElemState = []interface{}{
	"active",
	"waiting",
	"closed",
	"cancelled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskListOutputTasksElemState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskListOutputTasksElemState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskListOutputTasksElemState, v)
	}
	*j = TaskListOutputTasksElemState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskListOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["tasks"]; raw != nil && !ok {
		return fmt.Errorf("field tasks in TaskListOutput: required")
	}
	type Plain TaskListOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TaskListOutput(plain)
	return nil
}
