// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"

// Output of `gentry task show --json`.
type TaskShowOutput struct {
	// The task named, or the task of the current worktree.
	Task Task `json:"task"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskShowOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in TaskShowOutput: required")
	}
	type Plain TaskShowOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TaskShowOutput(plain)
	return nil
}
