// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

// A task of a project.
type Task struct {
	// The scenario of the task is passed: the task stays in work until it is closed,
	// and has no stage.
	Finished bool `json:"finished"`

	// The commit that applied the flow of the task: the task follows that flow to its
	// end, whatever is applied later.
	Flow Applied `json:"flow"`

	// Identifier of the task: the prefix of the project and the number, such as
	// SHOP-1. The event envelope names the task by it.
	Id string `json:"id"`

	// Progress of the task through its scenario.
	Progress TaskProgress `json:"progress"`

	// Identifier of the project.
	Project string `json:"project"`

	// Scenario of the task in the flow of the task.
	Scenario TaskScenario `json:"scenario"`

	// Current stage of the task; absent once the scenario is passed. Its exit,
	// instruction and transitions are given by `gentry stage show`.
	Stage *TaskStage `json:"stage,omitempty,omitzero"`

	// State of the task: active — in work, waiting — waits for the operator, closed —
	// done, cancelled — given up.
	State TaskState `json:"state"`

	// Statement of the task as passed, with its source.
	Statement TaskStatement `json:"statement"`

	// Time the task was taken in UTC, RFC 3339 with milliseconds.
	Taken time.Time `json:"taken"`

	// Title of the task: one line of up to 80 characters.
	Title string `json:"title"`

	// Absolute path of the worktree the task holds; absent once the task released it.
	Worktree *string `json:"worktree,omitempty,omitzero"`
}

// Progress of a task: stages passed of all stages of its way to the end. Ahead of
// a fork the total is a range, from the shortest way to the longest.
type TaskProgress struct {
	// Number of the nodes of the scenario closed by an exit or a skip; a return does
	// not lower it.
	Passed int `json:"passed"`

	// passed plus the nodes not passed yet on the longest way to the end, without
	// returns; equals total_min unless a fork is ahead.
	TotalMax int `json:"total_max"`

	// passed plus the nodes not passed yet on the shortest way to the end, without
	// returns.
	TotalMin int `json:"total_min"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskProgress) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["passed"]; raw != nil && !ok {
		return fmt.Errorf("field passed in TaskProgress: required")
	}
	if _, ok := raw["total_max"]; raw != nil && !ok {
		return fmt.Errorf("field total_max in TaskProgress: required")
	}
	if _, ok := raw["total_min"]; raw != nil && !ok {
		return fmt.Errorf("field total_min in TaskProgress: required")
	}
	type Plain TaskProgress
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Passed {
		return fmt.Errorf("field %s: must be >= %v", "passed", 0)
	}
	if 0 > plain.TotalMax {
		return fmt.Errorf("field %s: must be >= %v", "total_max", 0)
	}
	if 0 > plain.TotalMin {
		return fmt.Errorf("field %s: must be >= %v", "total_min", 0)
	}
	*j = TaskProgress(plain)
	return nil
}

// Scenario of the task in the flow of the task.
type TaskScenario struct {
	// Identifier of the scenario.
	Id string `json:"id"`

	// Title of the scenario.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskScenario) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TaskScenario: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskScenario: required")
	}
	type Plain TaskScenario
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = TaskScenario(plain)
	return nil
}

// Current stage of the task. Its exit, instruction and transitions are given by
// `gentry stage show`.
type TaskStage struct {
	// Identifier of the stage of the node.
	Id string `json:"id"`

	// Node of the scenario the task is at.
	Node string `json:"node"`

	// Number of the pass of the node in the task, from 1: a return to the node starts
	// the next round.
	Round int `json:"round"`

	// Title of the stage.
	Title string `json:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TaskStage: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in TaskStage: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in TaskStage: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskStage: required")
	}
	type Plain TaskStage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	*j = TaskStage(plain)
	return nil
}

type TaskState string

const TaskStateActive TaskState = "active"
const TaskStateCancelled TaskState = "cancelled"
const TaskStateClosed TaskState = "closed"
const TaskStateWaiting TaskState = "waiting"

var enumValues_TaskState = []interface{}{
	"active",
	"waiting",
	"closed",
	"cancelled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskState, v)
	}
	*j = TaskState(v)
	return nil
}

// Statement of the task as passed, with its source.
type TaskStatement struct {
	// Who passed the title and the statement: operator — the operator, agent — the
	// agent wrote them from the words of the operator.
	Source TaskStatementSource `json:"source"`

	// Text of the statement.
	Text string `json:"text"`
}

type TaskStatementSource string

const TaskStatementSourceAgent TaskStatementSource = "agent"
const TaskStatementSourceOperator TaskStatementSource = "operator"

var enumValues_TaskStatementSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStatementSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskStatementSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskStatementSource, v)
	}
	*j = TaskStatementSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStatement) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskStatement: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in TaskStatement: required")
	}
	type Plain TaskStatement
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	*j = TaskStatement(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Task) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["finished"]; raw != nil && !ok {
		return fmt.Errorf("field finished in Task: required")
	}
	if _, ok := raw["flow"]; raw != nil && !ok {
		return fmt.Errorf("field flow in Task: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Task: required")
	}
	if _, ok := raw["progress"]; raw != nil && !ok {
		return fmt.Errorf("field progress in Task: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in Task: required")
	}
	if _, ok := raw["scenario"]; raw != nil && !ok {
		return fmt.Errorf("field scenario in Task: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in Task: required")
	}
	if _, ok := raw["statement"]; raw != nil && !ok {
		return fmt.Errorf("field statement in Task: required")
	}
	if _, ok := raw["taken"]; raw != nil && !ok {
		return fmt.Errorf("field taken in Task: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Task: required")
	}
	type Plain Task
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if plain.Worktree != nil && utf8.RuneCountInString(string(*plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = Task(plain)
	return nil
}
