// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

// A step of a pass of a stage: declared ahead, then done or dropped.
type TaskStep struct {
	// Time the step was added in UTC, RFC 3339 with milliseconds.
	Added time.Time `json:"added"`

	// How the result of a done step was checked; absent if not given.
	Check *string `json:"check,omitempty,omitzero"`

	// Time the step was done or dropped in UTC, RFC 3339 with milliseconds.
	Closed *time.Time `json:"closed,omitempty,omitzero"`

	// Who marked the step done or dropped it: operator or agent.
	ClosedSource *TaskStepClosedSource `json:"closed_source,omitempty,omitzero"`

	// Number of the step within the pass, from 1.
	Number int `json:"number"`

	// Why a dropped step was dropped.
	Reason *string `json:"reason,omitempty,omitzero"`

	// Who added the step: operator or agent.
	Source TaskStepSource `json:"source"`

	// State of the step: planned — not done yet, done — done, dropped — dropped with
	// a reason.
	State TaskStepState `json:"state"`

	// The step: one line of up to 120 characters.
	Title string `json:"title"`
}

type TaskStepClosedSource string

const TaskStepClosedSourceAgent TaskStepClosedSource = "agent"
const TaskStepClosedSourceOperator TaskStepClosedSource = "operator"

var enumValues_TaskStepClosedSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStepClosedSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskStepClosedSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskStepClosedSource, v)
	}
	*j = TaskStepClosedSource(v)
	return nil
}

type TaskStepSource string

const TaskStepSourceAgent TaskStepSource = "agent"
const TaskStepSourceOperator TaskStepSource = "operator"

var enumValues_TaskStepSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStepSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskStepSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskStepSource, v)
	}
	*j = TaskStepSource(v)
	return nil
}

type TaskStepState string

const TaskStepStateDone TaskStepState = "done"
const TaskStepStateDropped TaskStepState = "dropped"
const TaskStepStatePlanned TaskStepState = "planned"

var enumValues_TaskStepState = []interface{}{
	"planned",
	"done",
	"dropped",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStepState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskStepState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskStepState, v)
	}
	*j = TaskStepState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskStep) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["added"]; raw != nil && !ok {
		return fmt.Errorf("field added in TaskStep: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in TaskStep: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskStep: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in TaskStep: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskStep: required")
	}
	type Plain TaskStep
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Check != nil && utf8.RuneCountInString(string(*plain.Check)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "check", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if plain.Reason != nil && utf8.RuneCountInString(string(*plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = TaskStep(plain)
	return nil
}
