// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

type TaskAttempt struct {
	// Number of the attempt.
	Attempt int `json:"attempt"`

	// The closing or the cancelling of the attempt; absent while it is in work.
	Ended *TaskEnded `json:"ended,omitempty,omitzero"`

	// Scenario of the attempt.
	Scenario TaskScenario `json:"scenario"`

	// State of the attempt, as in Task.
	State TaskAttemptsOutputAttemptsElemState `json:"state"`

	// Time the attempt was taken in UTC, RFC 3339 with milliseconds.
	Taken time.Time `json:"taken"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskAttempt) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["attempt"]; raw != nil && !ok {
		return fmt.Errorf("field attempt in TaskAttempt: required")
	}
	if _, ok := raw["scenario"]; raw != nil && !ok {
		return fmt.Errorf("field scenario in TaskAttempt: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in TaskAttempt: required")
	}
	if _, ok := raw["taken"]; raw != nil && !ok {
		return fmt.Errorf("field taken in TaskAttempt: required")
	}
	type Plain TaskAttempt
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Attempt {
		return fmt.Errorf("field %s: must be >= %v", "attempt", 1)
	}
	*j = TaskAttempt(plain)
	return nil
}

// Output of `gentry task attempts --json` without an attempt: the attempts of a
// task. With an attempt the command gives that attempt as `gentry task show
// --json` gives a task (TaskShowOutput).
type TaskAttemptsOutput struct {
	// Attempts of the task in order, from 1; a task never cancelled has one.
	Attempts []TaskAttempt `json:"attempts"`

	// Identifier of the task, such as SHOP-1.
	Task string `json:"task"`
}

type TaskAttemptsOutputAttemptsElemState string

const TaskAttemptsOutputAttemptsElemStateActive TaskAttemptsOutputAttemptsElemState = "active"
const TaskAttemptsOutputAttemptsElemStateCancelled TaskAttemptsOutputAttemptsElemState = "cancelled"
const TaskAttemptsOutputAttemptsElemStateClosed TaskAttemptsOutputAttemptsElemState = "closed"
const TaskAttemptsOutputAttemptsElemStateWaiting TaskAttemptsOutputAttemptsElemState = "waiting"

var enumValues_TaskAttemptsOutputAttemptsElemState = []interface{}{
	"active",
	"waiting",
	"closed",
	"cancelled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskAttemptsOutputAttemptsElemState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskAttemptsOutputAttemptsElemState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskAttemptsOutputAttemptsElemState, v)
	}
	*j = TaskAttemptsOutputAttemptsElemState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskAttemptsOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["attempts"]; raw != nil && !ok {
		return fmt.Errorf("field attempts in TaskAttemptsOutput: required")
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in TaskAttemptsOutput: required")
	}
	type Plain TaskAttemptsOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Task)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task", 1)
	}
	*j = TaskAttemptsOutput(plain)
	return nil
}
