// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry task cancel --input`. An unknown field is an error. The task is
// the argument of the command; the source is not part of the input: Gentry
// determines it by who calls the command.
type TaskCancelInput struct {
	// Why the task is cancelled; not required.
	Reason *string `json:"reason,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCancelInput) UnmarshalJSON(value []byte) error {
	type Plain TaskCancelInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Reason != nil && utf8.RuneCountInString(string(*plain.Reason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reason", 1)
	}
	*j = TaskCancelInput(plain)
	return nil
}
