// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry task close --json`: the task is closed and its worktree is
// free.
type TaskCloseOutput struct {
	// What the layout of subagents in the worktree the task released did; present
	// only when there is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// The task closed.
	Task Task `json:"task"`

	// Absolute path of the worktree the task released.
	Worktree string `json:"worktree"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCloseOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in TaskCloseOutput: required")
	}
	if _, ok := raw["worktree"]; raw != nil && !ok {
		return fmt.Errorf("field worktree in TaskCloseOutput: required")
	}
	type Plain TaskCloseOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskCloseOutput(plain)
	return nil
}
