// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry task cancel --json`: the task is cancelled and its worktree is
// free. The task can be taken anew by `gentry task take --task`.
type TaskCancelOutput struct {
	// The task cancelled.
	Task Task `json:"task"`

	// Absolute path of the worktree the task released.
	Worktree string `json:"worktree"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCancelOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["task"]; raw != nil && !ok {
		return fmt.Errorf("field task in TaskCancelOutput: required")
	}
	if _, ok := raw["worktree"]; raw != nil && !ok {
		return fmt.Errorf("field worktree in TaskCancelOutput: required")
	}
	type Plain TaskCancelOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskCancelOutput(plain)
	return nil
}
