// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"
import "time"
import "unicode/utf8"

// A note of a task: what the agent wants to keep in mind. Notes are only added; a
// wrong one is corrected by a new one.
type TaskNote struct {
	// Time the note was added in UTC, RFC 3339 with milliseconds.
	Added time.Time `json:"added"`

	// Node of the pass the note was added at.
	Node string `json:"node"`

	// Number of the note within the task, from 1.
	Number int `json:"number"`

	// Round of that pass.
	Round int `json:"round"`

	// Who added the note: operator or agent.
	Source TaskNoteSource `json:"source"`

	// Stage of that node.
	Stage string `json:"stage"`

	// Text of the note; may have several lines.
	Text string `json:"text"`
}

type TaskNoteSource string

const TaskNoteSourceAgent TaskNoteSource = "agent"
const TaskNoteSourceOperator TaskNoteSource = "operator"

var enumValues_TaskNoteSource = []interface{}{
	"operator",
	"agent",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskNoteSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskNoteSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskNoteSource, v)
	}
	*j = TaskNoteSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskNote) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["added"]; raw != nil && !ok {
		return fmt.Errorf("field added in TaskNote: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in TaskNote: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in TaskNote: required")
	}
	if _, ok := raw["round"]; raw != nil && !ok {
		return fmt.Errorf("field round in TaskNote: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in TaskNote: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in TaskNote: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in TaskNote: required")
	}
	type Plain TaskNote
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if 1 > plain.Round {
		return fmt.Errorf("field %s: must be >= %v", "round", 1)
	}
	if utf8.RuneCountInString(string(plain.Stage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "stage", 1)
	}
	if utf8.RuneCountInString(string(plain.Text)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "text", 1)
	}
	*j = TaskNote(plain)
	return nil
}
