// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Input of `gentry task take --input`: the fields of the task as one object, in a
// file or on the standard input. An unknown field is an error. The source of the
// statement is not part of the input: Gentry determines it by who calls the
// command.
type TaskTakeInput struct {
	// Identifier of the scenario of the task.
	Scenario string `json:"scenario"`

	// Statement of the task, kept as passed.
	Statement string `json:"statement"`

	// Title of the task: one line of up to 80 characters.
	Title string `json:"title"`

	// Worktree of the task; the current directory by default.
	Worktree *string `json:"worktree,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskTakeInput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["scenario"]; raw != nil && !ok {
		return fmt.Errorf("field scenario in TaskTakeInput: required")
	}
	if _, ok := raw["statement"]; raw != nil && !ok {
		return fmt.Errorf("field statement in TaskTakeInput: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskTakeInput: required")
	}
	type Plain TaskTakeInput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Scenario)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "scenario", 1)
	}
	if utf8.RuneCountInString(string(plain.Statement)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "statement", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) > 80 {
		return fmt.Errorf("field %s length: must be <= %d", "title", 80)
	}
	if plain.Worktree != nil && utf8.RuneCountInString(string(*plain.Worktree)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "worktree", 1)
	}
	*j = TaskTakeInput(plain)
	return nil
}
