// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry version --json`.
type VersionOutput struct {
	// Contract version. It grows only on an incompatible change; 0 until the first
	// release.
	Contract int `json:"contract"`

	// Product version in semver, without the leading v: 0.1.0 for a release, a Go
	// pseudo-version for a development build.
	Gentry string `json:"gentry"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VersionOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["contract"]; raw != nil && !ok {
		return fmt.Errorf("field contract in VersionOutput: required")
	}
	if _, ok := raw["gentry"]; raw != nil && !ok {
		return fmt.Errorf("field gentry in VersionOutput: required")
	}
	type Plain VersionOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Contract {
		return fmt.Errorf("field %s: must be >= %v", "contract", 0)
	}
	if utf8.RuneCountInString(string(plain.Gentry)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "gentry", 1)
	}
	*j = VersionOutput(plain)
	return nil
}
