// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

// Output of `gentry worktree add --json`.
type WorktreeAddOutput struct {
	// What happened: added or unchanged. The list is open: a client shows an unknown
	// value as is.
	Action string `json:"action"`

	// What the layout of subagents in the worktree added did; present only when there
	// is something to tell.
	Agents *AgentsLayout `json:"agents,omitempty,omitzero"`

	// Whether this is the main worktree of the project.
	Main bool `json:"main"`

	// Absolute path of the worktree root added to the pool; the root, when a
	// directory inside it was given.
	Path string `json:"path"`

	// Identifier of the project whose pool has the worktree.
	Project string `json:"project"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorktreeAddOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in WorktreeAddOutput: required")
	}
	if _, ok := raw["main"]; raw != nil && !ok {
		return fmt.Errorf("field main in WorktreeAddOutput: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in WorktreeAddOutput: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in WorktreeAddOutput: required")
	}
	type Plain WorktreeAddOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Action)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "action", 1)
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = WorktreeAddOutput(plain)
	return nil
}
