// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "unicode/utf8"

type WorktreeListItem struct {
	// Branch checked out in the worktree, read from git at the call; absent when the
	// worktree is not on a branch or its directory does not exist.
	Branch *string `json:"branch,omitempty,omitzero"`

	// Whether the worktree directory exists.
	Exists bool `json:"exists"`

	// Whether this is the main worktree of the project.
	Main bool `json:"main"`

	// Absolute path of the worktree root.
	Path string `json:"path"`

	// Identifier of the project whose pool has the worktree.
	Project string `json:"project"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorktreeListItem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["exists"]; raw != nil && !ok {
		return fmt.Errorf("field exists in WorktreeListItem: required")
	}
	if _, ok := raw["main"]; raw != nil && !ok {
		return fmt.Errorf("field main in WorktreeListItem: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in WorktreeListItem: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in WorktreeListItem: required")
	}
	type Plain WorktreeListItem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Branch != nil && utf8.RuneCountInString(string(*plain.Branch)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "branch", 1)
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	*j = WorktreeListItem(plain)
	return nil
}

// Output of `gentry worktree list --json`.
type WorktreeListOutput struct {
	// Worktrees of the project, or of all projects when none is named or found by the
	// directory: by project, the main worktree first, then by path.
	Worktrees []WorktreeListItem `json:"worktrees"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorktreeListOutput) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["worktrees"]; raw != nil && !ok {
		return fmt.Errorf("field worktrees in WorktreeListOutput: required")
	}
	type Plain WorktreeListOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WorktreeListOutput(plain)
	return nil
}
